import fs from 'node:fs'
import {randomUUID,randomBytes} from 'node:crypto'
import {afterEach,expect,it,vi} from 'vitest'
import {Pool} from 'pg'
import {ManagedPreviewSecrets,ManagedSecretRunnerProvider,type ManagedSecretReference} from './runtime/managedPreviewSecrets'
import {snapshotPreview,type ControlledJob,type RunnerProvider,type RunnerObservation} from './runtime/controlledPreview'
import {HostedLinuxRunnerProvider} from './runtime/hostedLinuxRunner'
import {PostgresLeaseStore} from './runtime/postgresFencing'
import {LOCAL_RESOURCE_BUDGET} from './runtime/runnerContracts'
const clean:Array<()=>unknown>=[];afterEach(async()=>{vi.useRealTimers();for(const f of clean.splice(0).reverse())await f()})
function fixture(){
 const owner={userId:randomUUID(),sessionId:randomUUID(),projectId:randomUUID(),workspaceId:randomUUID()},state={authorized:true,version:'v1',value:'TEST_'+randomBytes(24).toString('hex'),missing:false,refs:[] as ManagedSecretReference[]};state.refs=[{...owner,environment:'preview',runtime:'isolated-browser',name:'WCB_PREVIEW_SAMPLE',key:'test/project/value',version:'v1'}];
 const provider={read:vi.fn(async()=>state.missing?undefined:{version:state.version,value:state.value}),versions:vi.fn(async()=>state.refs.map(()=>state.missing?undefined:state.version))},policy={references:vi.fn(async()=>state.refs)},broker=new ManagedPreviewSecrets(provider,policy,async()=>state.authorized),generation=randomUUID(),expiresAt=Date.now()+60000,job:ControlledJob={generation,origin:'http://wcb-'+generation+'.preview.invalid',revision:'rev_'+randomUUID(),expiresAt,route:'/',network:{external:'deny'},snapshot:snapshotPreview({html:'<h1>Unchanged source</h1>',files:new Map()}),allocation:{owner,idempotencyKey:generation,startupDeadline:Date.now()+15000,executionDeadline:expiresAt,idleMs:60000,budget:LOCAL_RESOURCE_BUDGET}};
 return{owner,state,provider,policy,broker,job}
}
it('keeps default empty grants value-free and never reads the provider',async()=>{const f=fixture();f.state.refs=[];expect(await f.broker.bind(f.owner,f.job.generation)).toBeUndefined();expect(f.provider.read).not.toHaveBeenCalled()})
it('rejects cross-tenant, cross-project, non-preview, private-server, duplicate and malformed grants',async()=>{
 for(const change of [{workspaceId:randomUUID()},{projectId:randomUUID()},{environment:'production'},{runtime:'server'},{name:'AWS_SECRET_ACCESS_KEY'},{version:undefined},{key:undefined}]){const f=fixture();Object.assign(f.state.refs[0],change);await expect(f.broker.bind(f.owner,f.job.generation)).rejects.toThrow();expect(f.provider.read).not.toHaveBeenCalled()}
 const f=fixture();f.state.refs.push(f.state.refs[0]);await expect(f.broker.bind(f.owner,f.job.generation)).rejects.toThrow()
})
it('checks fresh authority, unavailable versions and bounded values before delivery',async()=>{
 const f=fixture();f.state.authorized=false;await expect(f.broker.bind(f.owner,f.job.generation)).rejects.toThrow();f.state.authorized=true;f.state.missing=true;await expect(f.broker.bind(f.owner,f.job.generation)).rejects.toThrow();f.state.missing=false;f.state.version='v2';await expect(f.broker.bind(f.owner,f.job.generation)).rejects.toThrow();f.state.version='v1';f.state.value='short';await expect(f.broker.bind(f.owner,f.job.generation)).rejects.toThrow()
})
it('detects rotation, revocation and missing secrets and removes reachable delivery values',async()=>{
 const f=fixture(),lease=(await f.broker.bind(f.owner,f.job.generation))!;expect(await lease.valid()).toBe(true);f.state.version='v2';expect(await lease.valid()).toBe(false);f.state.version='v1';f.state.refs=[];expect(await lease.valid()).toBe(false);lease.destroy();expect(Object.keys(lease.delivery.values)).toEqual([]);expect(await lease.valid()).toBe(false)
})
it('rejects delayed provider work without exposing its errors or returning late values',async()=>{
 vi.useFakeTimers();const f=fixture();f.provider.read.mockImplementation(()=>new Promise(()=>{}));const result=f.broker.bind(f.owner,f.job.generation),failed=expect(result).rejects.toThrow('unavailable');await vi.advanceTimersByTimeAsync(1600);await failed;expect(vi.getTimerCount()).toBe(0)
})
it('adds delivery only to runner messages, withholds encoded logs, and closes a revoked generation',async()=>{
 const f=fixture();let delivered:ControlledJob|undefined;const closed=vi.fn(async()=>{}),inner:RunnerProvider={open:async job=>{delivered=job;return{capture:async()=>Buffer.from('png'),input:async()=>{},sample:async()=>({bytes:Buffer.from('png'),observation:{logs:[f.state.value.split('').join('-')]}}),close:closed}}},wrapper=new ManagedSecretRunnerProvider(inner,f.broker),execution=await wrapper.open(f.job,new AbortController().signal);clean.push(()=>execution.close());expect(delivered?.secretDelivery?.values.WCB_PREVIEW_SAMPLE).toBe(f.state.value);expect(JSON.stringify(f.job)).not.toContain(f.state.value);expect((await execution.sample!()).observation).toEqual({logs:['Runtime logs withheld for managed preview values.']});f.state.authorized=false;await expect(execution.capture()).rejects.toThrow('unavailable');expect(closed).toHaveBeenCalledTimes(1);expect(Object.keys(delivered!.secretDelivery!.values)).toEqual([])
})
it('rejects caller-supplied delivery and never gives the semantic compiler managed values',async()=>{
 const f=fixture(),inner={open:vi.fn(async(_job:ControlledJob)=>({capture:async()=>Buffer.from(''),input:async()=>{},close:async()=>{}}))},wrapper=new ManagedSecretRunnerProvider(inner,f.broker);await expect(wrapper.open({...f.job,secretDelivery:{generation:f.job.generation,runtime:'isolated-browser',values:{}}},new AbortController().signal)).rejects.toThrow('forbidden');await wrapper.open({...f.job,purpose:'semantic-typescript-v1'},new AbortController().signal);expect(f.policy.references).not.toHaveBeenCalled();expect(inner.open.mock.calls[0][0].secretDelivery).toBeUndefined()
})
it.skipIf(process.env.WCB_HOSTED_RUNNER_TEST!=='1')('delivers and rotates generated TEST values through real fenced mTLS and native sandbox without source or log exposure',async()=>{
 const f=fixture(),config=JSON.parse(fs.readFileSync('.webcanbe/runner/qa-phase2g2/gateway-client.json','utf8')),pool=new Pool(config.postgres),base=new HostedLinuxRunnerProvider(new PostgresLeaseStore(pool),[{...config.host,lookup:(_h:any,_o:any,cb:any)=>cb(null,[{address:'127.0.0.1',family:4}])}],async()=>f.state.authorized);clean.push(()=>pool.end());clean.push(()=>base.close());await base.recover();const wrapper=new ManagedSecretRunnerProvider(base,f.broker),digest=(text:string)=>[...text].reduce((n,c)=>(Math.imul(n,31)+c.charCodeAt(0))>>>0,7);
 const job=()=>{const generation=randomUUID(),expiresAt=Date.now()+60000;return{...f.job,generation,origin:'http://wcb-'+generation+'.preview.invalid',expiresAt,allocation:{...f.job.allocation!,idempotencyKey:generation,startupDeadline:Date.now()+15000,executionDeadline:expiresAt},snapshot:snapshotPreview({html:`<h1>Managed preview test</h1><script>const value=globalThis.__WCB_PREVIEW_SECRETS__?.WCB_PREVIEW_SAMPLE||'';const ok=[...value].reduce((n,c)=>(Math.imul(n,31)+c.charCodeAt(0))>>>0,7)===${digest(f.state.value)};location.hash=ok?'delivered':'missing';document.querySelector('h1').textContent=ok?'Managed value delivered':'Missing';console.log(value);console.log([...value].join('-'));</script>`,files:new Map()})}}
 const firstJob=job(),execution=await wrapper.open(firstJob,new AbortController().signal);clean.push(()=>execution.close());const first=await execution.sample!();expect((first.observation as RunnerObservation).route).toBe('/#delivered');expect(JSON.stringify(first.observation)).not.toContain(f.state.value);expect((first.observation as RunnerObservation).logs).toEqual(['Runtime logs withheld for managed preview values.']);expect(JSON.stringify(firstJob)).not.toContain(f.state.value);const row=(await pool.query('SELECT row_to_json(l) AS row FROM wcb_runner_leases l WHERE generation=$1',[firstJob.generation])).rows[0];expect(JSON.stringify(row)).not.toContain(f.state.value);f.state.version='v2';f.state.value='TEST_'+randomBytes(24).toString('hex');await expect(execution.sample!()).rejects.toThrow();expect((await pool.query('SELECT state FROM wcb_runner_leases WHERE generation=$1',[firstJob.generation])).rows[0].state).toBe('stopped');f.state.refs[0]={...f.state.refs[0],version:'v2'};const secondJob=job(),second=await wrapper.open(secondJob,new AbortController().signal);clean.push(()=>second.close());expect(((await second.sample!()).observation as RunnerObservation).route).toBe('/#delivered');f.state.refs=[];await expect(second.sample!()).rejects.toThrow();expect((await pool.query('SELECT state FROM wcb_runner_leases WHERE generation=$1',[secondJob.generation])).rows[0].state).toBe('stopped')
},35000)
