import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import {randomUUID} from 'node:crypto'
import {Pool} from 'pg'
import {afterEach,expect,it} from 'vitest'
import {DurableSource,contentHash,transactionEntry,boundedHistory} from './mutations/durableSource'
import {historyTransactions,historyRevisions,decodeHistoryArchive,appendsCompaction} from './mutations/historyArchive'
import {MutationHistory} from './mutations/sourceMutations'
import {detectProject} from './runtime/projectRegistry'
import {PostgresAccess,PostgresProjectStore} from './runtime/postgresStores'
import {withHostedSource} from './runtime/postgresSourceCheckout'
import type {FileOperation} from './core/types'
const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true})})
function fixture(){const parent=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'wcb-archive-')));roots.push(parent);const root=path.join(parent,'project');fs.mkdirSync(path.join(root,'src'),{recursive:true});fs.copyFileSync('fixtures/compatible-react-vite/package.json',path.join(root,'package.json'));fs.writeFileSync(path.join(root,'src/App.tsx'),'export const App=()=> <h1>Original</h1>');fs.writeFileSync(path.join(root,'src/data.ts'),'export const value=1');const p={id:randomUUID(),name:'AUTHORED history',root,sourceRoot:path.join(root,'src'),imported:true,detection:detectProject(root,process.cwd()),history:new MutationHistory()},storage=path.join(parent,'history'),d=new DurableSource(p,storage);return{p,storage,d}}
function commit(d:DurableSource,operations:FileOperation[],options:{compactHistory?:boolean;fault?:(phase:string)=>void;restoresRevisionId?:string}={}){const revision=d.revision(),key=randomUUID(),entry=transactionEntry(d.history().projectId,revision,options.compactHistory?'system':'code',key,contentHash(key),'Test history transaction',{level:options.compactHistory?'checkpoint':'compile',passed:true,diagnostics:[]});if(options.compactHistory)entry.editType='checkpoint';entry.restoresRevisionId=options.restoresRevisionId;return d.commit({expectedRevision:revision,operations,entry,authorize:()=>{},checkpoint:options.compactHistory,compactHistory:options.compactHistory,fault:options.fault})}
function change(d:DurableSource,file:string,text:string){return commit(d,[{kind:'update',file,expectedHash:contentHash(d.files().get(file)!),content:text}])}
it('compacts losslessly, retains idempotency and selective inverse evidence, and restores an undoable old checkpoint',()=>{
 const {d,p,storage}=fixture(),first=change(d,'src/App.tsx','export const App=()=> <h1>First</h1>'),firstFiles=d.files(),second=change(d,'src/data.ts','export const value=2'),old=d.history();commit(d,[],{compactHistory:true});const compacted=d.history();expect(appendsCompaction(old,compacted)).toBe(true);expect(compacted.transactions).toHaveLength(1);expect(compacted.archives).toHaveLength(1);expect(historyTransactions(compacted).slice(0,-1)).toEqual(old.transactions);expect(d.retry(first.idempotencyKey!,first.requestHash!)).toEqual(first);expect(d.revertOperations(second.id).operations[0]).toMatchObject({file:'src/data.ts',content:'export const value=1'});change(d,'src/App.tsx','export const App=()=> <h1>Later</h1>');const before=d.files(),restore=commit(d,d.restoreOperations(first.newRevisionId!),{restoresRevisionId:first.newRevisionId});expect(d.files()).toEqual(firstFiles);const undo=d.revertOperations(restore.id);commit(d,undo.operations);expect(d.files()).toEqual(before);expect(new DurableSource(p,storage).history().archives).toEqual(compacted.archives);expect(historyRevisions(d.history()).at(-1)?.parentRevisionId).toBe(restore.newRevisionId)
})
it.each(['journal','committed'])('recovers a compaction fault at %s with exact source and verifiable archives',phase=>{
 const {d,p,storage}=fixture();change(d,'src/data.ts','export const value=2');const files=d.files(),before=d.history(),run=()=>commit(d,[],{compactHistory:true,fault:point=>{if(point===phase)throw Error('injected compaction crash')}});if(phase==='journal')expect(run).toThrow();else expect(run().success).toBe(true);const reopened=new DurableSource(p,storage);expect(reopened.files()).toEqual(files);expect(historyTransactions(reopened.history()).slice(0,before.transactions.length)).toEqual(before.transactions);expect(reopened.history().archives?.length??0).toBe(phase==='committed'?1:0)
})
it('rolls back a partially written multi-file restore and rejects missing checkpoints and damaged archives',()=>{
 const {d,p,storage}=fixture(),initial=d.revision();change(d,'src/App.tsx','export const App=()=> <h1>Changed</h1>');change(d,'src/data.ts','export const value=2');commit(d,[],{compactHistory:true});const files=d.files(),history=d.history();expect(()=>commit(d,d.restoreOperations(initial),{fault:phase=>{if(phase==='write')throw Error('injected restore crash')}})).toThrow();expect(new DurableSource(p,storage).files()).toEqual(files);expect(d.history()).toEqual(history);expect(()=>d.restoreOperations('missing')).toThrow('unavailable');const archive=history.archives![0];decodeHistoryArchive(archive,p.id);expect(()=>decodeHistoryArchive({...archive,rawBytes:archive.rawBytes-1},p.id)).toThrow('mismatch');expect(()=>decodeHistoryArchive({...archive,data:archive.data.slice(0,-4)+'AAAA'},p.id)).toThrow();expect(()=>decodeHistoryArchive(archive,randomUUID())).toThrow('scope');expect(()=>boundedHistory({...history,archives:Array(5).fill(archive)})).toThrow('capacity')
})
it.skipIf(process.env.WCB_PG_TEST!=='1')('commits source plus compaction atomically in PG and refuses rewritten archived ancestry, stale restore and revocation',async()=>{
 const f=fixture();change(f.d,'src/data.ts','export const value=2');const initial=f.d.history(),files=new Map(fs.readdirSync(f.p.root,{recursive:true,withFileTypes:true}).filter(e=>e.isFile()).map(e=>{const full=path.join(e.parentPath,e.name);return[path.relative(f.p.root,full),fs.readFileSync(full)]}));const config=JSON.parse(fs.readFileSync('.webcanbe/runner/qa-phase2g2/postgres.json','utf8')),schema='test_'+randomUUID().replace(/-/g,''),admin=new Pool(config);await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({...config,options:`-c search_path=${schema}`});try{
 await pool.query(fs.readFileSync('deployment/hosted/postgres.sql','utf8'));const access=new PostgresAccess(pool),store=new PostgresProjectStore(access),session={sessionId:randomUUID(),userId:randomUUID(),expiresAt:Date.now()+600000},workspace=randomUUID();await access.registerSession(session);await access.workspace(workspace,session.userId,'owner');await store.create(session,workspace,f.p.id,'History',files,initial);const grant=await access.grant(session,f.p.id,'code'),before=await store.read(grant);commit(f.d,[],{compactHistory:true});const proposed=f.d.history();await expect(store.accept(grant,{revision:before.revision,epoch:before.epoch},files,proposed,async()=>{throw Error('transaction fault')})).rejects.toThrow('fault');expect(await store.read(grant)).toEqual(before);await store.accept(grant,{revision:before.revision,epoch:before.epoch},files,proposed);const accepted=await store.read(grant);expect(appendsCompaction(before.history,accepted.history)).toBe(true);await withHostedSource(store,grant,process.cwd(),async(_project,d)=>{expect(d.history().archives).toHaveLength(1);expect(d.restoreOperations(initial.revisions[0].revisionId)).toHaveLength(1)});const forged=structuredClone(proposed);forged.archives![0]={...forged.archives![0],rawBytes:1};await expect(store.accept(grant,{revision:accepted.revision,epoch:accepted.epoch},files,forged)).rejects.toThrow();expect(await store.read(grant)).toEqual(accepted);await expect(store.accept(grant,{revision:before.revision,epoch:before.epoch},files,initial)).rejects.toThrow();await access.revokeSession(session.sessionId);await expect(store.read(grant)).rejects.toThrow()
 }finally{await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end()}
},20000)
