import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import {randomUUID} from 'node:crypto'
import {afterEach,expect,it} from 'vitest'
import {DurableSource,treeHash,legacyEditableSource,transactionEntry,contentHash} from './mutations/durableSource'
import {detectProject} from './runtime/projectRegistry'
import {MutationHistory} from './mutations/sourceMutations'
const roots:string[]=[];afterEach(()=>{for(const r of roots.splice(0))fs.rmSync(r,{recursive:true,force:true})})
function legacy(){const parent=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'wcb-scope-')));roots.push(parent);const root=path.join(parent,'source'),storage=path.join(parent,'history');fs.cpSync('fixtures/independent/vite-react19-ts',root,{recursive:true});fs.writeFileSync(path.join(root,'src/extra.mts'),'export const extra=1');const p={id:randomUUID(),name:'AUTHORED legacy scope',root,sourceRoot:path.join(root,'src'),imported:true,detection:detectProject(root,process.cwd()),history:new MutationHistory()},d=new DurableSource(p,storage),ledger=d.history();delete ledger.sourceScope;ledger.revisions[0].contentHash=treeHash(new Map([...d.files()].filter(([f])=>legacyEditableSource.test(f))));const state=path.join(storage,p.id,'history.json');fs.writeFileSync(state,JSON.stringify(ledger));return{p,storage,state,ledger,d:new DurableSource(p,storage)}}
function migrate(d:DurableSource,fault?:(phase:string)=>void){const revision=d.revision(),key=randomUUID(),entry=transactionEntry('test',revision,'system',key,contentHash(key),'Enable module file editing',{level:'checkpoint',passed:true,diagnostics:[]});entry.editType='checkpoint';return d.commit({expectedRevision:revision,operations:[],entry,authorize:()=>{},checkpoint:true,migrateSourceScope:true,fault})}
it('keeps legacy canonical digests and bytes stable until an explicit accepted scope migration',()=>{
 const {d,p,storage,ledger}=legacy();expect(d.revision()).toBe(ledger.revisions[0].revisionId);expect(d.files().has('src/extra.mts')).toBe(false);expect(()=>d.prepare([{kind:'update',file:'src/extra.mts',expectedHash:contentHash('export const extra=1'),content:'export const extra=2'}])).toThrow('scope');const old=d.history(),entry=migrate(d),now=d.history();expect(now.sourceScope).toBe(2);expect(now.revisions.slice(0,-1)).toEqual(old.revisions);expect(now.transactions.slice(0,-1)).toEqual(old.transactions);expect(now.past).toEqual(old.past);expect(now.revisions.at(-1)?.parentRevisionId).toBe(old.revisions.at(-1)?.revisionId);expect(new DurableSource(p,storage).revision()).toBe(entry.newRevisionId);expect(d.files().get('src/extra.mts')).toBe('export const extra=1');expect(()=>migrate(d)).toThrow('legacy checkpoint')
})
it.each(['journal','committed'])('recovers scope migration after failure at %s without changing source',phase=>{
 const {d,p,storage,ledger}=legacy();const run=()=>migrate(d,point=>{if(point===phase)throw Error('injected failure')});if(phase==='journal')expect(run).toThrow();else expect(run().status).toBe('accepted');const reopened=new DurableSource(p,storage);expect(reopened.history().sourceScope).toBe(phase==='journal'?undefined:2);expect(reopened.history().revisions.slice(0,1)).toEqual(ledger.revisions);expect(reopened.revision()).not.toMatch(/^external_/);expect(fs.readFileSync(path.join(p.root,'src/extra.mts'),'utf8')).toBe('export const extra=1')
})
it('refuses unknown scope versions and external edits instead of adopting them',()=>{
 const {d,p,storage,state}=legacy();fs.appendFileSync(path.join(p.root,'src/App.tsx'),'// outside edit');const stale=d.history().revisions.at(-1)!.revisionId;expect(()=>d.assertBase(stale)).toThrow();const ledger=d.history();(ledger as any).sourceScope=9;fs.writeFileSync(state,JSON.stringify(ledger));expect(()=>new DurableSource(p,storage)).toThrow('scope version')
})

import {Pool} from 'pg'
import {PostgresAccess,PostgresProjectStore} from './runtime/postgresStores'
import {withHostedSource} from './runtime/postgresSourceCheckout'
;(process.env.WCB_PG_TEST==='1'?it:it.skip)('migrates legacy PostgreSQL source atomically; rollback, stale writer, downgrade and revocation stay refused',async()=>{
 const config=JSON.parse(fs.readFileSync('.webcanbe/runner/qa-phase2g2/postgres.json','utf8')),schema='test_scope_'+randomUUID().replace(/-/g,''),admin=new Pool(config);await admin.query(`CREATE SCHEMA ${schema}`);const pool=new Pool({...config,options:`-c search_path=${schema}`});
 try{
  await pool.query(fs.readFileSync('deployment/hosted/postgres.sql','utf8'));const access=new PostgresAccess(pool),store=new PostgresProjectStore(access),workspace=randomUUID(),session={sessionId:randomUUID(),userId:randomUUID(),expiresAt:Date.now()+600000};await access.registerSession(session);await access.workspace(workspace,session.userId,'owner');const {d,p,ledger}=legacy();const files=new Map(fs.readdirSync(p.root,{recursive:true,withFileTypes:true}).filter(e=>e.isFile()).map(e=>{const file=path.join(e.parentPath,e.name);return[path.relative(p.root,file),fs.readFileSync(file)]}));await store.create(session,workspace,p.id,p.name,files,ledger);const grant=await access.grant(session,p.id),before=await store.read(grant);expect(before.history.sourceScope).toBeUndefined();expect(before.files.has('src/extra.mts')).toBe(true);
  migrate(d);const proposed=d.history();await expect(store.accept(grant,{revision:before.revision,epoch:before.epoch},files,proposed,async()=>{throw Error('injected before commit')})).rejects.toThrow('injected');expect(await store.read(grant)).toEqual(before);
  const accepted=await store.accept(grant,{revision:before.revision,epoch:before.epoch},files,proposed);expect(accepted.epoch).not.toBe(before.epoch);const after=await store.read(grant);expect(after.files).toEqual(before.files);expect(after.history.revisions.slice(0,-1)).toEqual(before.history.revisions);expect(after.history.sourceScope).toBe(2);const materialized=await withHostedSource(store,grant,process.cwd(),async(_project,source)=>source.files().get('src/extra.mts'));expect(materialized.value).toBe('export const extra=1');
  const other=structuredClone(proposed);other.revisions.at(-1)!.revisionId='rev_'+randomUUID();other.transactions.at(-1)!.newRevisionId=other.revisions.at(-1)!.revisionId;await expect(store.accept(grant,{revision:before.revision,epoch:before.epoch},files,other)).rejects.toThrow();
  const downgrade=structuredClone(after.history);delete downgrade.sourceScope;downgrade.revisions.at(-1)!.contentHash=ledger.revisions[0].contentHash;await expect(store.accept(grant,{revision:after.revision,epoch:after.epoch},files,downgrade)).rejects.toThrow('scope migration');expect(await store.read(grant)).toEqual(after);await access.revokeSession(session.sessionId);await expect(store.accept(grant,{revision:after.revision,epoch:after.epoch},files,proposed)).rejects.toThrow()
 }finally{await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end()}
},20000)
