import { useEffect, useRef, useState, type CSSProperties } from 'react'
import { ChevronDown, Plus, Type, Play, Download, Link2, Clock3, Code2, Columns2, History, MousePointer2, Settings2, LayoutDashboard, CircleHelp, Check, Search, Home, File, Image, Layers, Box } from 'lucide-react'
import { Avatar, useAccount } from '../../app-shell'
import type { SourceTarget, PreviewElement } from '../core/types'
import { layerDepth, layerName, pageName, type EditorPage } from './editorNavigation'
export type Surface = 'canvas'|'code'|'split'|'history'
export function EditorToolbar({ name, revision, updatedAt, surface, openSurface, connected, previewOnly, onPreview, onExport, onUndo, onRedo, onProject, onShortcuts, onText }: { name?:string; revision:string; updatedAt?:string; surface:Surface; openSurface:(value:Surface)=>void; connected:boolean; previewOnly:boolean; onPreview:()=>void; onExport:()=>void; onUndo:()=>void; onRedo:()=>void; onProject:()=>void; onShortcuts:()=>void; onText:()=>void }) {
  const {account}=useAccount(), [popover,setPopover]=useState<'canvas'|'share'|'export'|'account'|null>(null), [copied,setCopied]=useState(false), [query,setQuery]=useState(''), [copyError,setCopyError]=useState('')
  const root=useRef<HTMLElement>(null)
  useEffect(()=>{const close=(event:globalThis.MouseEvent)=>{if(!root.current?.contains(event.target as Node))setPopover(null)};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')setPopover(null)};document.addEventListener('mousedown',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('mousedown',close);document.removeEventListener('keydown',escape)}},[])
  const actions=[{label:'Visual',icon:MousePointer2,run:()=>openSurface('canvas')},{label:'Code',icon:Code2,run:()=>openSurface('code')},{label:'Split',icon:Columns2,run:()=>openSurface('split')},{label:'History',icon:History,run:()=>openSurface('history')},{label:'Project settings & import',icon:Settings2,run:onProject},{label:'Dashboard',icon:LayoutDashboard,href:'/dashboard'},{label:'Keyboard shortcuts',icon:CircleHelp,run:onShortcuts},{label:'Help Center',icon:CircleHelp,href:'/help'}]
  const toggle=(value:typeof popover)=>{setPopover(current=>current===value?null:value);setCopied(false);setCopyError('')}
  return <header className="compatible-topbar editor-reference-toolbar" ref={root}>
    <span hidden aria-keyshortcuts="Meta+Z Control+Z">Undo</span><span hidden aria-keyshortcuts="Meta+Shift+Z Control+Shift+Z Control+Y">Redo</span>
    <div className="editor-top-left"><button className="editor-canvas-menu" aria-label="Canvas menu" aria-expanded={popover==='canvas'} onClick={()=>toggle('canvas')}><img src="/brand/webcanbe-mark.svg" alt="WebCanBe"/><span>{surface==='canvas'?'Canvas':surface==='code'?'Code':surface==='split'?'Split':'History'}</span><ChevronDown/></button><button aria-label="Open project import" title="Import project" onClick={onProject}><Plus/></button><button aria-label="Edit selected text" title="Edit selected text" onClick={onText}><Type/></button></div>
    <div className="compatible-project-status"><span>{name||'Workspace'}</span>{revision&&<button title="View accepted revision history" onClick={()=>openSurface('history')}>{revision.slice(0,7)}</button>}</div>
    <div className="editor-top-right"><button aria-label={previewOnly?'Back to editor':'Preview'} title={previewOnly?'Back to editor':'Show the full-page preview'} aria-pressed={previewOnly} disabled={!connected} onClick={onPreview}><Play/></button><button aria-expanded={popover==='share'} onClick={()=>toggle('share')}>Share</button><button className="editor-export" aria-expanded={popover==='export'} onClick={()=>toggle('export')}>Export</button></div>
    {popover==='canvas'&&<div className="editor-popover editor-main-menu"><label><Search/><input aria-label="Search editor menu" placeholder="Type to search…" value={query} onChange={event=>setQuery(event.target.value)}/></label>{actions.filter(item=>item.label.toLowerCase().includes(query.toLowerCase())).map(item=>item.href?<a key={item.label} href={item.href}><item.icon/>{item.label}</a>:<button key={item.label} onClick={()=>{item.run?.();setPopover(null)}}><item.icon/>{item.label}</button>)}{!actions.some(item=>item.label.toLowerCase().includes(query.toLowerCase()))&&<p>No matching actions.</p>}<button className="editor-account-menu-trigger" onClick={()=>setPopover('account')}><Avatar account={account}/>Your account</button></div>}
    {popover==='share'&&<div className="editor-popover editor-share-menu"><h2>Project link</h2><p>Access requires permission to this project.</p><label><Link2/><input aria-label="Project link" value={window.location.origin+window.location.pathname} readOnly/></label><button onClick={()=>{void navigator.clipboard.writeText(window.location.origin+window.location.pathname).then(()=>setCopied(true),()=>setCopyError('Copy unavailable. Select the link above.'))}}>{copied?<Check/>:<Link2/>}{copied?'Copied':'Copy project link'}</button>{copyError&&<p role="status">{copyError}</p>}<div className="editor-share-account"><Avatar account={account}/><span>{account.displayName||'Your account'}<small>{account.email||'This browser'}</small></span></div></div>}
    {popover==='export'&&<div className="editor-popover editor-export-menu"><h2>Download source</h2><p>{name||'No project connected'}</p>{revision&&<p><Code2/>Accepted revision {revision.slice(0,12)}</p>}{updatedAt&&<p><Clock3/><time dateTime={updatedAt}>{new Date(updatedAt).toLocaleString()}</time></p>}<p>Includes accepted changes. Save Code drafts before exporting.</p><button disabled={!connected} onClick={()=>{onExport();setPopover(null)}}><Download/>Download ZIP</button><button onClick={()=>{openSurface('history');setPopover(null)}}><History/>View history</button></div>}
    {popover==='account'&&<div className="editor-popover editor-account-menu"><div className="editor-share-account"><Avatar account={account}/><span>{account.displayName||'Your account'}<small>{account.email||'Local editor session'}</small></span></div><a href="/settings"><Settings2/>Settings</a><a href="/plans"><CircleHelp/>Plans</a><a href="/dashboard"><LayoutDashboard/>Dashboard</a></div>}
  </header>
}
export function EditorNavigation({ panel, setPanel, pages, route, onPage, targets, selected, onSelect, files, onFile, connected, onProject }: {panel:'pages'|'layers'|'assets'|'project';setPanel:(value:'pages'|'layers'|'assets'|'project')=>void;pages:EditorPage[];route:string;onPage:(path:string)=>void;targets:SourceTarget[];selected?:PreviewElement;onSelect:(target:SourceTarget)=>void;files:string[];onFile:(file:string)=>void;connected:boolean;onProject:()=>void}) {
  const [query,setQuery]=useState('')
  useEffect(()=>setQuery(''),[panel])
  const currentPage=pages.find(page=>page.path===route) || {path:route,name:pageName(route)}
  const visible=targets.filter(item=>layerName(item).toLowerCase().includes(query.toLowerCase()))
  const assets=files.filter(file=>/\.(?:svg|png|jpe?g|webp|gif|avif|woff2?|ttf|mp4|webm|ico)$/i.test(file))
  const groups=[...new Set(visible.map(item=>item.ownerComponent||'Page'))]
  return <><div className="editor-panel-tabs" role="tablist" aria-label="Project panels">{(['pages','layers','assets'] as const).map(value=><button key={value} role="tab" aria-selected={panel===value} aria-controls={`editor-${value}-panel`} onClick={()=>{setPanel(value);setQuery('')}}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div>{panel!=='project'&&<div className="editor-nav-content" id={`editor-${panel}-panel`} role="tabpanel" aria-label={panel}>
    {panel==='layers'&&<button className="editor-page-selector" onClick={()=>setPanel('pages')}><Home/>{currentPage.name}<ChevronDown/></button>}
    <label className="editor-search"><Search/><input aria-label={`Search ${panel}`} placeholder="Search…" value={query} onChange={event=>setQuery(event.target.value)}/></label>
    {panel==='pages'&&<><div className="editor-nav-section"><span>Design</span><button title="Open project settings" aria-label="Open project settings" onClick={onProject}><Settings2/></button></div><div className="editor-nav-section"><span>Pages</span><button aria-label="Edit page routes in Code" title="Edit routes in Code" onClick={()=>onFile('')}><Code2/></button></div>{connected?pages.filter(page=>`${page.name} ${page.path}`.toLowerCase().includes(query.toLowerCase())).map(page=><button className="editor-tree-row" aria-pressed={page.path===route} key={page.path} onClick={()=>onPage(page.path)}>{page.path==='/'?<Home/>:<File/>}<span>{page.name}</span><small>{page.path==='/'?'':page.path}</small></button>):<div className="editor-source-empty"><p>Connect a project to see its pages.</p><button onClick={onProject}>Connect project</button></div>}</>}
    {panel==='layers'&&<>{groups.map(group=><details className="editor-layer-group" key={group} open><summary><Layers/>{group}</summary>{visible.filter(item=>(item.ownerComponent||'Page')===group).map(item=><button className="editor-tree-row" style={{"--layer-indent":`${12+layerDepth(item,targets)*10}px`} as CSSProperties} title={layerName(item)} key={`${item.identity.file}:${item.identity.elementStart}`} aria-pressed={selected?.identity.elementStart===item.identity.elementStart&&selected.identity.file===item.identity.file} onClick={()=>onSelect(item)}>{item.elementName==='img'?<Image/>:/^h\d$|^p$|^span$/.test(item.elementName)?<Type/>:<Box/>}<span>{layerName(item)}</span></button>)}</details>)}{!visible.length&&<p className="editor-nav-empty">{connected?'No matching layers. Open Code to inspect this project.':'Connect a project to inspect its layers.'}</p>}</>}
    {panel==='assets'&&<><div className="editor-nav-section"><span>Project assets</span><button aria-label="Open assets in Code" onClick={()=>onFile('')}><Code2/></button></div>{assets.filter(file=>file.toLowerCase().includes(query.toLowerCase())).map(file=><button className="editor-tree-row" key={file} title={file} onClick={()=>onFile(file)}><Image/><span>{file.split('/').at(-1)}</span></button>)}{!assets.length&&<p className="editor-nav-empty">No asset files returned by this project. Referenced media remains in its source.</p>}<div className="editor-nav-section"><span>Components</span></div>{[...new Set(targets.map(item=>item.ownerComponent).filter(Boolean))].filter(name=>name!.toLowerCase().includes(query.toLowerCase())).map(name=><button className="editor-tree-row" key={name} onClick={()=>{const target=targets.find(item=>item.ownerComponent===name);if(target)onSelect(target)}}><Box/><span>{name}</span></button>)}<div className="editor-nav-section"><span>Styles</span></div>{files.filter(file=>/\.css$/.test(file)&&file.toLowerCase().includes(query.toLowerCase())).map(file=><button className="editor-tree-row" key={file} onClick={()=>onFile(file)}><File/><span>{file.split('/').at(-1)}</span></button>)}</>}
  </div>}</>
}
