// @vitest-environment jsdom
import {act} from 'react'
import {createRoot, type Root} from 'react-dom/client'
import {beforeEach,afterEach,it,expect,vi} from 'vitest'
import {EditorToolbar,EditorNavigation} from './EditorChrome'
import type {SourceTarget} from '../core/types'
vi.mock('../../app-shell',()=>({useAccount:()=>({account:{displayName:'Verified user',email:'verified@example.test'}}),Avatar:()=> <span>VU</span>}))
let host:HTMLDivElement,root:Root
beforeEach(()=>{vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);host=document.createElement('div');document.body.append(host);root=createRoot(host)})
afterEach(async()=>{await act(async()=>root.unmount());host.remove();vi.unstubAllGlobals()})
const click=async(label:string)=>{const button=[...host.querySelectorAll('button')].find(item=>item.textContent===label||item.getAttribute('aria-label')===label)!;expect(button).toBeTruthy();await act(async()=>button.click())}
it('keeps all four real modes in the Canvas menu',async()=>{const openSurface=vi.fn();await act(async()=>root.render(<EditorToolbar name="Actual project" revision="rev_123456" surface="canvas" openSurface={openSurface} connected interact={false} onPreview={()=>{}} onExport={()=>{}} onUndo={()=>{}} onRedo={()=>{}} onProject={()=>{}} onShortcuts={()=>{}} onText={()=>{}}/>));for(const [label,mode] of [['Visual','canvas'],['Code','code'],['Split','split'],['History','history']]){await click('Canvas menu');await click(label);expect(openSurface).toHaveBeenLastCalledWith(mode)}expect(host.textContent).toContain('Actual project');expect(host.querySelector('time')).toBeNull()})
it('exports accepted source from the status popover and uses the actual project URL',async()=>{const onExport=vi.fn();window.history.replaceState({},'','/workspace/real-project?mode=split');await act(async()=>root.render(<EditorToolbar name="Actual project" revision="rev_123456" updatedAt="2026-09-22T01:00:00Z" surface="split" openSurface={()=>{}} connected interact={false} onPreview={()=>{}} onExport={onExport} onUndo={()=>{}} onRedo={()=>{}} onProject={()=>{}} onShortcuts={()=>{}} onText={()=>{}}/>));await click('Share');expect((host.querySelector('[aria-label="Project link"]') as HTMLInputElement).value).toBe(window.location.origin+'/workspace/real-project');expect(host.textContent).toContain('Access requires permission');expect(host.textContent).toContain('Verified user');await click('Export');expect(host.querySelector('time')?.dateTime).toBe('2026-09-22T01:00:00Z');await click('Download ZIP');expect(onExport).toHaveBeenCalledOnce()})
it('uses page names and real layer selection while keeping filenames out of Layers',async()=>{const onPage=vi.fn(),onSelect=vi.fn(),setPanel=vi.fn();const target={elementName:'h1',text:'Actual title',ownerComponent:'Hero',identity:{file:'src/Hero.tsx',elementStart:10},sourceRange:{start:10,end:50}} as SourceTarget;const props={setPanel,pages:[{path:'/',name:'Home'},{path:'/contact',name:'Contact'}],route:'/',onPage,targets:[target],onSelect,files:[],onFile:()=>{},connected:true,onProject:()=>{}};await act(async()=>root.render(<EditorNavigation {...props} panel="pages"/>));await click('Contact/contact');expect(onPage).toHaveBeenCalledWith('/contact');await act(async()=>root.render(<EditorNavigation {...props} panel="layers"/>));expect(host.textContent).not.toContain('Hero.tsx');await click('Heading · Actual title');expect(onSelect).toHaveBeenCalledWith(target)})

it('keeps account navigation inside the editor popover without legacy account routes',async()=>{await act(async()=>root.render(<EditorToolbar name="Actual project" revision="rev_123456" surface="canvas" openSurface={()=>{}} connected interact={false} onPreview={()=>{}} onExport={()=>{}} onUndo={()=>{}} onRedo={()=>{}} onProject={()=>{}} onShortcuts={()=>{}} onText={()=>{}}/>));await click('Profile: Verified user');expect(host.textContent).toContain('Verified user');expect(host.textContent).toContain('verified@example.test');expect(host.querySelector('a[href="/settings"]')).toBeTruthy();expect(host.querySelector('a[href="/dashboard"]')).toBeTruthy();expect(host.querySelector('a[href="/plans"]')).toBeTruthy();expect(host.querySelector('a[href="/profile"]')).toBeNull();expect(host.querySelector('a[href="/account"]')).toBeNull();expect(host.querySelector('a[href="/billing"]')).toBeNull();await click('Canvas menu');const accountTrigger=host.querySelector<HTMLButtonElement>('.editor-account-menu-trigger');expect(accountTrigger).toBeTruthy();await act(async()=>accountTrigger!.click());expect(host.querySelector('.editor-account-menu')).toBeTruthy()})
