// Frozen original applications. No upstream source/config/dependency changes or filtering.
const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process'),{createHash,randomUUID}=require('node:crypto'),{build}=require('esbuild'),assert=require('node:assert/strict');
(async()=>{
 const root=process.cwd(),dir=path.join(root,'.webcanbe/compatibility-breadth'),sha=b=>createHash('sha256').update(b).digest('hex');fs.mkdirSync(dir,{recursive:true});
 const bundle=path.join(dir,'api.cjs');await build({stdin:{contents:`export {extractSafeZip,detectProject} from './src/webcanbe-engine/runtime/projectRegistry';export {inspectRuntime} from './src/webcanbe-engine/runtime/runtimeCompatibility';export {buildIsolatedHttpPreview} from './src/webcanbe-engine/runtime/isolatedPreview';export {TrustedStaticAssets} from './src/webcanbe-engine/runtime/staticAssets';export {MutationHistory} from './src/webcanbe-engine/mutations/sourceMutations';`,resolveDir:root},bundle:true,platform:'node',format:'cjs',packages:'external',outfile:bundle,logLevel:'silent'});
 const existing=path.join(dir,'applications.json');if(fs.existsSync(existing))fs.copyFileSync(existing,path.join(dir,'applications-prior-'+Date.now()+'.json'));
 const api=require(bundle),old=JSON.parse(fs.readFileSync('docs/reports/phase2g2-evidence/async-corpus-final.json')),selection=JSON.parse(fs.readFileSync('docs/reports/phase2-common-applications-evidence/preselection.json'));
 const candidates=[...old.subjects.filter(c=>['redux-essentials','bulletproof-react','todo-list-react'].includes(c.id)).map(c=>({...c,cache:'.webcanbe/runner/qa-phase2g2/corpus/upstream/'+c.id})),...selection.subjects.filter(c=>c.id==='GroqRecipeBook').map(c=>({...c,subpath:'',cache:'.webcanbe/runner/qa-common-applications/selection/'+c.id}))],results=[];
 for(const c of candidates){
  const git=args=>execFileSync('git',['-C',c.cache,...args],{maxBuffer:40*1024*1024}),archive=git(['archive','--format=zip','--mtime='+c.archiveMtime,c.commit+(c.subpath?':'+c.subpath:'')]);assert.equal(sha(archive),c.archiveSha256);
  const r={id:c.id,commit:c.commit,archiveSha256:sha(archive),stages:{},diagnosticOnly:null};results.push(r);const scratch=path.join(dir,c.id);fs.rmSync(scratch,{recursive:true,force:true});
  try{await api.extractSafeZip(archive,scratch);r.stages.intake={status:'PASS'}}catch(e){r.stages.intake={status:'FAIL',error:e.message};fs.mkdirSync(scratch,{recursive:true});for(const[name,meta]of Object.entries(c.unchangedFiles||c.files)){assert(name.split('/').every(p=>p&&p!=='.'&&p!=='..'));const bytes=git(['show',c.commit+':'+(c.subpath?c.subpath+'/':'')+name]);assert.equal(sha(bytes),meta.sha256);const file=path.join(scratch,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,bytes)}r.diagnosticOnly='Static analysis of separately materialized frozen files; failed intake is never promoted to compilation/runtime.'}
  for(const[name,meta]of Object.entries(c.unchangedFiles||c.files))assert.equal(sha(fs.readFileSync(path.join(scratch,name))),meta.sha256);r.unchangedFileHashesVerified=Object.keys(c.unchangedFiles||c.files).length;
  const p={id:randomUUID(),name:c.id,root:fs.realpathSync(scratch),sourceRoot:path.join(scratch,'src'),imported:true,detection:api.detectProject(scratch,root),history:new api.MutationHistory()},runtime=api.inspectRuntime(p,root);r.profile=runtime.profile;r.issues=runtime.issues;r.configuration=runtime.configuration;
  const configCodes=['executable-config','css-config','css-directive','tsconfig','environment-reference','dynamic-environment','html-entry'];r.stages.dependencies={status:runtime.issues.some(i=>!configCodes.includes(i.code))?'FAIL':'PASS'};r.stages.configuration={status:runtime.issues.some(i=>configCodes.includes(i.code))?'FAIL':'PASS'};
  for(const k of ['compilation','runtime','assets','render'])r.stages[k]={status:'NOT REACHED'};
  if(r.stages.intake.status==='PASS'&&runtime.supported){
   try{const compiled=await api.buildIsolatedHttpPreview(p,root);r.stages.compilation={status:'PASS',files:compiled.files.size};
    const artifact=b=>({html:b.html,files:[...b.files].map(([path,f])=>({path,contentType:f.contentType,base64:f.body.toString('base64')}))});fs.writeFileSync(path.join(dir,c.id+'-uncached-artifact.json'),JSON.stringify(artifact(compiled)));
    try{const materialized=await new api.TrustedStaticAssets().materialize(compiled,{userId:'qa',workspaceId:'qa',projectId:p.id,sessionId:'qa',revision:sha(archive),signal:AbortSignal.timeout(10000),assertCurrent:async()=>{for(const[name,meta]of Object.entries(c.files))assert.equal(sha(fs.readFileSync(path.join(scratch,name))),meta.sha256)}});r.stages.assets={status:'CACHED',audit:materialized.audit};fs.writeFileSync(path.join(dir,c.id+'-artifact.json'),JSON.stringify(artifact(materialized)))}catch(e){r.stages.assets={status:'FAIL',error:e.message,audit:e.staticAssetAudit}}
   }catch(e){r.stages.compilation={status:'FAIL',error:e.message}}
  }
  console.log(JSON.stringify({id:r.id,stages:Object.fromEntries(Object.entries(r.stages).map(([k,v])=>[k,{status:v.status,error:v.error,assets:v.audit?.length}])),issues:r.issues.length}));fs.writeFileSync(path.join(dir,'applications.json'),JSON.stringify({boundary:'Exact frozen archive/intake plus honest stage progression; native render reported separately',results},null,2)+'\n');fs.rmSync(scratch,{recursive:true,force:true});
 }
})().catch(e=>{console.error(e);process.exitCode=1});
