// Real trusted-viewer clipboard/composition and expiry checks; imported JS remains in Linux.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),yazl=require('yazl'),{X509Certificate,createHash}=require('node:crypto'),{setup}=require('./common-hosted.cjs'),{chromium}=require(process.env.WCB_PLAYWRIGHT_MODULE||'playwright');
(async()=>{const h=await setup();let browser,page,latest,p,user;const receipt={diagnosticBuild:process.env.WCB_QA_DIAGNOSTIC_ERRORS==='1',boundary:'Packaged hosted editor / isolated Linux project / native Chromium input events',browserPath:'Browser plugin not available; retained Playwright',checks:[],consoleErrors:[]},check=name=>receipt.checks.push({name,status:'PASS'}),pending=new Set();const saved='.webcanbe/runner/qa-final-internal/input-'+Date.now();fs.mkdirSync(saved,{recursive:true});try{
 user=await h.login('final-input');const files={'package.json':fs.readFileSync('fixtures/compatible-react-vite/package.json'),'index.html':fs.readFileSync('fixtures/compatible-react-vite/index.html'),'src/main.tsx':`import {createRoot} from 'react-dom/client';import {App} from './App';createRoot(document.getElementById('root')!).render(<App/>);`,'src/App.tsx':`import {useState} from 'react';import './App.css';export function App(){const [value,setValue]=useState('');return <main><label>Name<input aria-label="Name" value={value} onChange={e=>setValue(e.target.value)}/></label><button onClick={()=>history.replaceState(null,'','/#'+encodeURIComponent(value))}>Save input</button><p>{value}</p></main>}`,'src/App.css':'body {margin:0;font:18px sans-serif} main {padding:40px} input {display:block;width:280px;height:40px;margin:6px 0 20px} button {height:40px}'};
 const zip=new yazl.ZipFile();for(const[f,b]of Object.entries(files))zip.addBuffer(Buffer.from(b),f);zip.end();const chunks=[];for await(const c of zip.outputStream)chunks.push(c);const imported=await h.call(user,'/__webcanbe/api/projects/import',{workspaceId:user.workspace,name:'AUTHORED source gesture constraints',archive:Buffer.concat(chunks).toString('base64')});assert.equal(imported.status,201,JSON.stringify(imported.body));p=await h.session(user,imported.body.project.id);h.projects.push({...p,user});const db=async()=>(await h.pool.query('SELECT files,history,revision FROM wcb_projects WHERE project_id=$1',[p.id])).rows[0],text=(row,f)=>Buffer.from(row.files[f],'base64').toString();
 const pin=createHash('sha256').update(new X509Certificate(h.ca).publicKey.export({format:'der',type:'spki'})).digest('base64');browser=await chromium.launch({headless:true,chromiumSandbox:true,args:['--host-resolver-rules=MAP app.wcb-app.test 127.0.0.1, MAP viewer.wcb-preview.test 127.0.0.1',`--ignore-certificate-errors-spki-list=${pin}`,'--no-proxy-server']});const context=await browser.newContext({viewport:{width:1600,height:1100}});await context.addCookies([{name:'__Host-wcb-session',value:user.cookie.split('=')[1],domain:'app.wcb-app.test',path:'/',secure:true,httpOnly:true,sameSite:'Strict'}]);page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>receipt.consoleErrors.push(e.message));page.on('request',r=>{if(r.url().endsWith('/preview')&&r.method()==='POST'&&['capture','input'].includes(r.postDataJSON()?.command))pending.add(r)});page.on('requestfinished',r=>pending.delete(r));page.on('requestfailed',r=>pending.delete(r));page.on('response',async r=>{if(r.url().endsWith('/preview'))try{const d=await r.json();if(d.png)latest=d}catch{}});

 const until=async(f,label,ms=16000)=>{const end=Date.now()+ms;while(Date.now()<end){if(await f())return;await new Promise(r=>setTimeout(r,60))}throw Error('Timed out '+label)},image=()=>page.frameLocator('iframe[title="Running imported React/Vite project"]').locator('img'),sink=()=>page.frameLocator('iframe[title="Running imported React/Vite project"]').locator('textarea');
 const click=async(x,y)=>{const prev=latest;await until(()=>latest&&latest!==prev,'fresh pointer');await until(()=>pending.size===0,'idle');const img=image(),b=await img.boundingBox();await img.click({position:{x:x*b.width/latest.observation.viewport.width,y:y*b.height/latest.observation.viewport.height}});await until(()=>pending.size===0,'click response')};
 await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:h.origin});await page.goto(h.origin+'/workspace/'+p.id);await until(()=>!!latest?.png,'first frame');const initial=await db();assert.equal(await page.title(),'WebCanBe');await page.getByRole('button',{name:'Interact with preview',exact:true}).click();await click(180,90);await until(()=>latest.observation.focused?.role==='textbox','remote textbox focus');assert.equal(latest.observation.focused.name,'Name');check('real focused native control has bounded accessible role/name');
 const viewer=page.frames().find(f=>f.parentFrame()===page.mainFrame());assert(viewer,'trusted viewer frame');await viewer.evaluate(()=>{globalThis.qaEvents=[];for(const type of ['compositionstart','compositionupdate','compositionend','input','paste'])document.querySelector('textarea').addEventListener(type,e=>globalThis.qaEvents.push({type,trusted:e.isTrusted,data:e.data||null,inputType:e.inputType||null}))});
 const cdp=await context.newCDPSession(page);await sink().focus();await cdp.send('Input.imeSetComposition',{text:'ㅎ',selectionStart:1,selectionEnd:1});await cdp.send('Input.imeSetComposition',{text:'한글',selectionStart:2,selectionEnd:2});await cdp.send('Input.insertText',{text:'한글'});await until(()=>pending.size===0,'composition commit');await sink().press('Tab');await sink().press('Enter');await until(()=>latest.observation.route==='/#'+encodeURIComponent('한글'),'native composition committed once');receipt.events=await viewer.evaluate(()=>globalThis.qaEvents);assert(receipt.events.some(e=>e.type==='compositionstart'&&e.trusted));assert(receipt.events.some(e=>e.type==='compositionend'));receipt.compositionLimit='Chromium CDP uses trusted composition start/update/input events but its commit compositionend is untrusted; OS input-method validation is not claimed.';check('real Chromium composition pipeline commits Korean text exactly once');
 await click(180,90);await sink().press('End');const pasted=' Café 🧭 العربية';await page.evaluate(text=>navigator.clipboard.writeText(text),pasted);await sink().press('Meta+v');await until(()=>pending.size===0,'native paste');await sink().press('Tab');await sink().press('Enter');const expected='한글'+pasted;await until(()=>latest.observation.route==='/#'+encodeURIComponent(expected),'Unicode clipboard paste');receipt.events=await viewer.evaluate(()=>globalThis.qaEvents);assert(receipt.events.some(e=>e.type==='paste'&&e.trusted));check('native clipboard paste preserves accents, emoji and RTL Unicode');
 await click(180,90);await sink().press('Meta+a');await sink().press('Meta+c');await until(async()=>await page.evaluate(()=>navigator.clipboard.readText())===expected,'real clipboard copy');check('explicit copy returns selected plain text through the current fenced generation');await sink().press('F6');await until(()=>page.getByRole('button',{name:'Select elements',exact:true}).evaluate(e=>e===document.activeElement),'keyboard exit');check('F6 leaves the raster keyboard focus trap');assert.deepEqual(await db(),initial);check('input and clipboard do not change accepted source/history');await page.screenshot({path:path.join(saved,'native-input.png')});fs.writeFileSync(path.join(saved,'native-raster.png'),Buffer.from(latest.png,'base64'));
 const oldGeneration=latest.generation,begin=performance.now();if(process.env.WCB_INPUT_RECONNECT_ONLY!=='1'){await until(()=>page.locator('[data-preview-state="expired"]').count(), 'hard expiry',70000);receipt.expiryWaitMs=performance.now()-begin}else receipt.expiryEvidence='input-1789394581835/receipt.json: hard expiry already passed; this follow-up validates the corrected reconnect route assertion';await page.getByRole('button',{name:'Reconnect session',exact:true}).click();await until(()=>latest.generation!==oldGeneration, 'fresh reconnect');assert.deepEqual(await db(),initial);check('hard bounded expiry and fresh reconnect preserve canonical source/history');await page.getByRole('button',{name:'Interact with preview',exact:true}).count().then(async n=>{if(n)await page.getByRole('button',{name:'Interact with preview',exact:true}).click()});await click(180,90);await sink().press('Tab');await sink().press('Enter');await until(()=>latest.observation.route==='/','fresh runtime has no replayed input');check('expired generation text is never replayed into a new runtime');if(process.env.WCB_INPUT_QUEUE_PROBE==='1'){
 await click(180,90);await sink().focus();let held,release;const gate=new Promise(r=>release=r),requests=[];
 await page.route('**/preview',async route=>{const body=route.request().postDataJSON();if(body?.command==='input'){requests.push({generation:body.generation,type:body.input?.type});if(!held){held=true;await gate}}try{await route.continue()}catch{}});
 await sink().press('x');await until(()=>held,'held native input request');for(let i=0;i<80;i++)await sink().press(i%2?'ArrowLeft':'ArrowRight');await page.getByText('Preview input queue is full. Wait for the frame before continuing.',{exact:true}).waitFor();
 const generationBefore=latest.generation;await page.getByRole('button',{name:'Reconnect session',exact:true}).click();release();await until(()=>latest.generation!==generationBefore,'generation replacement with queued input');await page.unroute('**/preview');receipt.queue={bound:64,nativeKeyEvents:81,submittedBeforeReconnect:requests.filter(r=>r.generation===generationBefore).length};assert.equal(receipt.queue.submittedBeforeReconnect,1);check('native key pressure reaches bounded queue and reconnect discards all queued old-generation events');
 await page.getByRole('button',{name:'Interact with preview',exact:true}).count().then(async n=>{if(n)await page.getByRole('button',{name:'Interact with preview',exact:true}).click()});await click(180,90);await sink().press('Tab');await sink().press('Enter');await until(()=>latest.observation.route==='/','no queued text replay');assert.deepEqual(await db(),initial);check('fresh generation receives no stale queued text or canonical mutation');
 }
 assert.deepEqual(receipt.consoleErrors,[]);receipt.status='PASS';
}catch(e){receipt.failure=e.message;receipt.status='FAIL';process.exitCode=1;receipt.pending=[...pending].map(r=>r.postDataJSON()?.command);if(page)try{await page.screenshot({path:path.join(saved,'failure.png')});fs.writeFileSync(path.join(saved,'dom.txt'),await page.locator('body').innerText())}catch{}}finally{if(browser)await browser.close();await h.close();fs.writeFileSync(path.join(saved,'receipt.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({saved,...receipt}))}})().catch(e=>{console.error(e);process.exitCode=1});
