// One bounded P61 TEST run. No retries, quota changes, or application substitutions.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {execFileSync}=require('node:child_process'),{randomUUID}=require('node:crypto');
const {setup}=require('./common-hosted.cjs');
(async()=>{
 const h=await setup(),started=performance.now(),receipt={boundary:'Packaged HTTPS / PostgreSQL / mTLS / existing isolated local TEST Linux VM; not production capacity',users:2,projects:3,concurrency:2,operations:[],samples:[],updates:[],identityChecks:[],staleDuplicateCrossProjectResults:0};
 const out=path.join(h.root,'.webcanbe/runner/qa-p61');fs.mkdirSync(out,{recursive:true});
 const generations=[],frames=new Map(),lima=path.join(h.root,'.webcanbe/runner/tools/bin/limactl'),env={...process.env,LIMA_HOME:path.join(h.root,'.webcanbe/runner/lima')};
 async function op(p,action,body={},expected=200,user=p.user){const begin=performance.now(),r=await h.api(user,p,action,body);receipt.operations.push({project:p.id,action,command:body.command,ms:performance.now()-begin,status:r.status,expected,error:r.body?.error});assert.equal(r.status,expected,JSON.stringify(receipt.operations.at(-1)));return r.body;}
 async function sample(label){const states=(await h.pool.query('SELECT generation,state FROM wcb_runner_leases WHERE generation=ANY($1::uuid[])',[generations])).rows;const active=states.filter(x=>x.state!=='stopped');
 const units=[];for(const x of active){const s=Object.fromEntries(execFileSync(lima,['shell','--workdir=/','wcb','systemctl','show','wcb-preview-'+x.generation,'-p','MemoryCurrent','-p','MemoryPeak','-p','TasksCurrent','-p','ControlGroup','-p','MainPID','-p','MemoryMax','-p','TasksMax','-p','CPUQuotaPerSecUSec'],{env,timeout:10000}).toString().trim().split('\n').map(x=>x.split('=')));assert.equal(s.MemoryMax,'1610612736');assert.equal(s.TasksMax,'192');assert.equal(s.CPUQuotaPerSecUSec,'1.500000s');assert(Number(s.MemoryCurrent)<Number(s.MemoryMax));assert(Number(s.TasksCurrent)<=192);units.push({generation:x.generation,...s});}
 let processes;
 if(['initial','two jobs','final'].includes(label)){processes=JSON.parse(execFileSync(lima,['shell','--workdir=/','wcb','python3','-c',"import glob,os,json; a=[open(p,'rb').read().split(b'\\0') for p in glob.glob('/proc/[0-9]*/cmdline')]; c=[x for x in a if x and os.path.basename(x[0])==b'chromium']; print(json.dumps(dict(chromiumProcesses=len(c),browsers=sum(not any(y.startswith(b'--type=') for y in x) for x in c),workers=sum(b'/opt/wcb-runtime/worker.cjs' in x for x in a))))"],{env,timeout:10000}).toString());if(label==='initial'||label==='final')assert.deepEqual(processes,{chromiumProcesses:0,browsers:0,workers:0});}
 const ps=execFileSync('ps',['-axo','pid=,ppid=,rss=,command=']).toString().split('\n').map(s=>s.trim().split(/\s+/));const editor=ps.find(v=>Number(v[1])===process.pid&&v.slice(3).join(' ').includes('.webcanbe/hosted-package/editor.cjs'));
 receipt.samples.push({label,processes,elapsedMs:performance.now()-started,activeLeases:active.length,tasks:units.reduce((s,x)=>s+Number(x.TasksCurrent),0),workerMemory:units.reduce((s,x)=>s+Number(x.MemoryCurrent),0),editorRssBytes:editor?Number(editor[2])*1024:null,units});}
 async function capture(p){const b=await op(p,'preview',{command:'capture',generation:p.generation,expectedRevision:p.revision});assert.equal(b.generation,p.generation);assert.equal(b.revision,p.revision);assert(b.sequence>(frames.get(p.generation)||0));frames.set(p.generation,b.sequence);assert(Buffer.from(b.png,'base64').length>1000);p.frame=b;return b;}
 async function start(p){const b=await op(p,'preview',{command:'start',expectedRevision:p.revision});p.generation=b.generation;assert(!generations.includes(p.generation));generations.push(p.generation);await capture(p);}
 async function inspectArtifact(p){const row=(await h.pool.query('SELECT a.project_id,a.workspace_id,a.revision,a.generation,a.digest,l.owner_json,l.epoch,l.session_id,l.state FROM wcb_artifacts a JOIN wcb_runner_leases l USING(generation) WHERE a.generation=$1 AND NOT a.retired',[p.generation])).rows;assert.equal(row.length,1);const x=row[0];assert.equal(x.project_id,p.id);assert.equal(x.workspace_id,p.user.workspace);assert.equal(x.revision,p.revision);assert.equal(x.owner_json.projectId,p.id);assert.equal(x.owner_json.userId,p.user.id);assert.equal(x.owner_json.sessionId,p.previewId);assert.equal(x.state,'running');receipt.identityChecks.push(x);}
 async function update(p){const b=await op(p,'preview',{command:'update',generation:p.generation,expectedRevision:p.revision});assert.equal(b.generation,p.generation);assert.equal(b.revision,p.revision);receipt.updates.push({project:p.id,...b});await capture(p);await inspectArtifact(p);}
 async function edit(p,cycle){const read=await op(p,'files',{file:p.css});assert.equal(read.revision,p.revision);const old=read.source,content=old+'\n:root { --p61-'+p.label+': '+cycle+'; }\n';const b=await op(p,'code',{expectedRevision:p.revision,idempotencyKey:randomUUID(),operations:[{kind:'update',file:p.css,expectedHash:h.sha(Buffer.from(old)),content}]});const previous=p.revision;p.revision=b.revision;assert.notEqual(previous,p.revision);await op(p,'preview',{command:'capture',generation:p.generation,expectedRevision:previous},409);await update(p);const after=await op(p,'files',{file:p.css});assert.equal(after.source,content);assert(!after.source.includes('--p61-'+(p.label==='A'?'B':'A')+':'));}
 try{
  await sample('initial');const users=[await h.login('p61-load-A'),await h.login('p61-load-B')];const kanban=JSON.parse(fs.readFileSync('docs/reports/phase2-common-applications-evidence/preselection.json')).subjects.find(x=>x.id==='kanban-board'),habit=JSON.parse(fs.readFileSync('docs/reports/phase2-final-internal-evidence/preselection.json'));
  const zipA=execFileSync('git',['-C','.webcanbe/runner/qa-common-applications/selection/kanban-board','archive','--format=zip','--mtime='+kanban.archiveMtime,kanban.commit],{maxBuffer:32*1024*1024}),zipB=fs.readFileSync('.webcanbe/runner/qa-final-internal/habit-tracker-frozen.zip');
  for(const [i,c,zip] of [[0,kanban,zipA],[1,habit,zipB],[1,habit,zipB]]){assert.equal(h.sha(zip),c.archiveSha256);const user=users[i],begin=performance.now(),r=await h.call(user,'/__webcanbe/api/projects/import',{workspaceId:user.workspace,name:'P61 '+c.id,archive:zip.toString('base64')});receipt.operations.push({action:'import',status:r.status,expected:201,ms:performance.now()-begin});assert.equal(r.status,201);const p={...await h.session(user,r.body.project.id),user,label:h.projects.length===0?'A':'B'};h.projects.push(p);const row=(await h.pool.query('SELECT revision,files FROM wcb_projects WHERE project_id=$1',[p.id])).rows[0];assert.deepEqual(Object.keys(row.files).sort(),Object.keys(c.files).sort());for(const [f,m] of Object.entries(c.files))assert.equal(h.sha(Buffer.from(row.files[f],'base64')),m.sha256);p.revision=row.revision;p.css=Object.keys(row.files).find(f=>f.startsWith('src/')&&f.endsWith('.css'));assert(p.css);}
  const [a,b,c]=h.projects;await start(a);await start(b);await op(c,'preview',{command:'start',expectedRevision:c.revision},422);await sample('two jobs');
  await op(b,'files',{},403,a.user);await op(a,'preview',{command:'capture',generation:b.generation,expectedRevision:a.revision},422);
  // Required A -> B -> A, independent source, revision, artifact and owner checks.
  for(let round=0;round<9;round++){
   for(const p of round===0?[a,b,a]:[a,b])await edit(p,round);
   await Promise.all([capture(a),capture(b)]);await sample('round-'+round);
   if(round===2||round===5){for(const p of[a,b]){const old=p.generation;await op(p,'preview',{command:'stop'});Object.assign(p,await h.session(p.user,p.id));await start(p);assert.notEqual(old,p.generation);}await sample('turnover-'+round);}
  }
  // Actual source-backed Visual mutation from a native raster selection.
  await capture(a);await op(a,'preview',{command:'input',generation:a.generation,expectedRevision:a.revision,sequence:a.frame.sequence,input:{type:'pointer',action:'select',x:150,y:42}});await capture(a);assert.equal(a.frame.observation.selection?.tagName,'h1');const identity=a.frame.observation.selection.identity;
  const v=await op(a,'mutate',{expectedRevision:a.revision,idempotencyKey:randomUUID(),identity,edit:{type:'text',value:'P61 bounded board',scope:'source'}});a.revision=v.revision;await update(a);assert((await op(a,'files',{file:identity.file})).source.includes('P61 bounded board'));receipt.visualEdit=true;
  for(const p of[a,b])await op(p,'preview',{command:'stop'});await sample('released');await start(c);await capture(c);await op(c,'preview',{command:'stop'});await sample('final');receipt.status='PASS';
 }catch(error){receipt.status='FAIL';receipt.failure=error.message;process.exitCode=1;}
 finally{try{await h.close()}catch(error){receipt.status='FAIL';receipt.cleanupFailure=error.message;process.exitCode=1;}receipt.elapsedMs=performance.now()-started;const values=receipt.operations.filter(x=>x.status===200||x.status===201).map(x=>x.ms).sort((a,b)=>a-b);receipt.latencyMs={p50:values[Math.ceil(values.length*.5)-1],p95:values[Math.ceil(values.length*.95)-1],max:values.at(-1)};receipt.counts={total:receipt.operations.length,success:receipt.operations.filter(x=>x.status<300).length,expectedRefusals:receipt.operations.filter(x=>x.status>=400&&x.status===x.expected).length,unexpected:receipt.operations.filter(x=>x.status!==x.expected).length};fs.writeFileSync(path.join(out,'load.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({status:receipt.status,failure:receipt.failure,counts:receipt.counts,latencyMs:receipt.latencyMs,elapsedMs:receipt.elapsedMs}));}
})();
