import type { InfoPage } from './public-pages'

const link=(label:string,href:string):[string,string]=>[label,href]

export const companyPages:Record<string,InfoPage> = {
  '/about':{
    title:'About Webcanbe',
    intro:'Webcanbe helps people start from a real web project, make an independent working copy, edit the source, and take that source with them.',
    sections:[
      {title:'The problem we work on',paragraphs:['A screenshot, static mockup or locked page builder can show a promising result while leaving the actual project out of reach. Rebuilding that result later costs time and makes every edit depend on the original tool. Webcanbe starts with a source project that can become your own working copy.','A useful starting point needs more than a nice thumbnail. You should be able to inspect the project, understand what the release contains, review its compatibility and license, and see how it behaves before committing to it.'],links:[link('Explore projects','/browse'),link('Marketplace guide','/docs/marketplace')]},
      {title:'From discovery to your working copy',paragraphs:['The Marketplace is for finding projects with a concrete release and a clear use case. A project detail and preview should represent the same release that is offered for use. When access is granted, your working copy is separate from the Creator’s published version.','That separation matters when you test an idea or return days later. Your saved changes belong to the working copy, while the released source remains a stable reference for the listing and license.'],links:[link('Getting started','/docs/getting-started'),link('Working copies','/docs/working-copies')]},
      {title:'One source across editing views',paragraphs:['Visual mode is for supported text and style changes in context. Code mode lets you open and change the files directly. Split keeps rendered work and source in view together. The supported Visual controls are tied to source targets rather than a separate drawing layer.','AI editing is a reviewed proposal flow: a proposed change is not accepted source until you inspect and apply it. History then helps you understand accepted revisions. When a visual target is ambiguous or unsupported, Code is the route to make a deliberate source edit.'],links:[link('Visual editor','/docs/visual-editor'),link('Code editor','/docs/code-editor'),link('AI editing','/docs/ai-editing')]},
      {title:'Source you can continue using',paragraphs:['A working copy can be exported as project files for work outside Webcanbe. The exported project may have its own package dependencies, assets or external services, so its setup instructions and license still matter. The ability to leave with source is part of the product rather than an afterthought.','We aim to make the boundaries visible: what is a preview, what has been saved as accepted source, what requires a third-party account, and what belongs to a specific released license.'],links:[link('Export guide','/docs/export'),link('Licensing','/docs/marketplace/licenses')]},
      {title:'For buyers and Creators',paragraphs:['Buyers can compare projects, inspect their details, and create a copy when the release and their account permit it. A Marketplace purchase is not the same record as a working copy; the product should show the next step when an acquired release has not yet been copied.','Creators prepare source, describe compatibility and rights, submit for review, and publish versioned releases through the Creator workflow when approved. A draft submission is not presented as a published listing.'],links:[link('Purchases guide','/docs/purchases/acquire'),link('Creator guide','/docs/creators'),link('Apply to become a Creator','/seller/apply')]},
      {title:'Meet CEO',body:'SIHOO MIN leads Webcanbe. Learn more about the person behind the product on his own site.',links:[link('Meet SIHOO MIN','https://msihu.com')]},
    ],
  },
  '/updates':{
    title:'Product updates',intro:'A product-focused view of implemented changes and the steps they make possible. Planned work is identified separately from changes available now.',
    sections:[
      {title:'Public discovery and documentation',paragraphs:['The public Marketplace and documentation routes make the product easier to evaluate before sign-in. Visitors can read the project workflow, compatibility notes, legal terms and support guidance directly.','The route and title for each guide are kept separate so a copied link opens the same subject on refresh. Start with the getting-started guide if you are moving from a listing to a working copy for the first time.'],links:[link('Getting started','/docs/getting-started'),link('Marketplace','/browse')]},
      {title:'Working-copy and source verification',paragraphs:['The working-copy path is designed to keep the accepted source, rendered preview, History and export aligned. A supported Visual edit and a Code edit should remain visible after reopening the project and in the exported files.','Use History to inspect accepted changes. A temporary draft or AI proposal is not a saved revision until it is applied and accepted.'],links:[link('History','/docs/history'),link('Export','/docs/export')]},
      {title:'Requests for help',paragraphs:['Support requests have specific categories so account, billing, seller and technical questions can be routed with useful context. The form returns a case reference after successful creation.','A support submission records a request; it does not by itself complete a refund, change an account permission or send a provider email. Signed-in users can revisit their own request status.'],links:[link('Contact','/contact'),link('My Requests','/requests')]},
      {title:'Creator workflow',paragraphs:['Creator access starts with an application and approval. Approved Creators have a separate workspace for project preparation and submission. Published releases are versioned; a draft or a pending review should not appear as a live listing.','The Creator guides cover listing rules, licensing, releases, and fees. Check those before preparing a project for submission.'],links:[link('Creator guide','/docs/creators'),link('Apply','/seller/apply')]},
      {title:'What to verify before relying on a feature',paragraphs:['Availability can depend on account permissions and live configuration. Check the screen you are using for the actual state of a project, plan, order or Creator application.','For implementation history, use the Changelog. For a product issue, a support request is the place to include the affected route and reproducible steps.'],links:[link('Changelog','/changelog'),link('Report an issue','/contact/issues')]},
    ],
  },
  '/changelog':{
    title:'Changelog',intro:'Shipped source and product changes grouped by date. This record describes implemented work without treating a repository commit as proof of a live payment or customer outcome.',
    sections:[
      {title:'23 September 2026 — public navigation and Requests',paragraphs:['Improved: public routes now have dedicated navigation, metadata and support categories. Visitors can use a direct link to reach the intended guide or contact form.','Added: support submissions use persisted Requests and return a case reference. The separate Requests screen lets an authenticated requester revisit their case.','For users: choose the form that matches the question and save the returned reference. A created case is awaiting review.'],links:[link('Contact channels','/contact'),link('Requests','/requests')]},
      {title:'22 September 2026 — Marketplace and documentation shell',paragraphs:['Added: a public Marketplace entry and project category routes. These routes give visitors a way to evaluate project types and read the workflow before account access.','Improved: documentation has its own navigation and search, with direct routes for Visual, Code, AI, History, export and compatibility.','For users: evaluate a particular release and its license from the detail screen before creating a working copy.'],links:[link('Browse projects','/browse'),link('Documentation','/docs')]},
      {title:'21 September 2026 — source-backed editing evidence',paragraphs:['Verified in development: a working-copy flow recorded a supported Visual source change, a Code revision, reopen, and an independent export build. This is evidence for that flow, not a promise that every project or source pattern supports the same controls.','Improved: the guides distinguish accepted source from draft, preview-only selection and an unapplied AI proposal.'],links:[link('Visual editor','/docs/visual-editor'),link('Code editor','/docs/code-editor'),link('Export','/docs/export')]},
      {title:'How to read these notes',paragraphs:['Added describes a new route or capability. Improved describes a changed user path. Fixed describes a specific defect after it is verified. A feature listed in source history can still require account access, a compatible release, or live service configuration.','This page intentionally avoids unpublished security details, invented customers and unverified transaction success. If a listed behavior does not match the live product, report the route, action and visible result.'],links:[link('Report an issue','/contact/issues'),link('Updates','/updates')]},
    ],
  },
  '/github':{
    title:'Webcanbe and GitHub',intro:'Understand where GitHub fits when you own and export a Webcanbe project, and where to take product questions.',
    sections:[
      {title:'Export comes first',paragraphs:['Webcanbe’s source ownership promise is about the files in a working copy. Export produces those files and the project assets that belong to the accepted revision, subject to the release license.','After export, you can inspect the files locally, install the project dependencies and build with the commands in that project. Check any environment variables or external services before deployment.'],links:[link('Export guide','/docs/export'),link('Compatibility','/docs/compatibility')]},
      {title:'Using a repository for your work',paragraphs:['You can place your exported project in a repository you control when its license and included assets permit that use. Review the package manifest, notice files and secrets before committing.','A repository can track later changes and collaboration, but Webcanbe does not claim that exporting automatically creates or synchronizes a GitHub repository.'],links:[link('Buyer License','/legal/buyer-license'),link('Third-Party Notices','/legal/third-party-notices')]},
      {title:'What a Webcanbe integration means',paragraphs:['A GitHub button or account connection in the product should be read according to its current screen state. If it is unavailable, use export and a local repository workflow instead of assuming a push happened.','A successful local build is separate from production deployment. Review the exported project’s own deployment instructions and required secrets.'],links:[link('Integrations','/docs/integrations'),link('Report an issue','/contact/issues')]},
      {title:'Product and account support',paragraphs:['Public issue trackers are the wrong place for private account information, paid orders, project source or a suspected vulnerability. Use the Webcanbe support category that matches the concern.','For a reproducible UI or export problem, include the route, action, expected result and actual result without posting credentials or private source.'],links:[link('Contact Webcanbe','/contact'),link('Security report','/contact/security')]},
    ],
  },
  '/brand':{
    title:'Webcanbe brand assets',intro:'The product name, wordmark and symbol are available here for accurate identification and approved references.',
    sections:[
      {title:'The name',paragraphs:['Write Webcanbe as one word with a capital W. Use the name to identify the source-first project marketplace and workspace accurately.','Do not describe an unrelated project, a Creator listing or a third-party service as an official Webcanbe product.'],links:[link('About Webcanbe','/about')]},
      {title:'Wordmark and symbol',paragraphs:['The wordmark is the preferred full brand signature. The symbol is useful where the product name is clear from the surrounding context. Keep the original SVG proportions and enough clear space for recognition.','Both downloads below are the actual site assets. Open the SVG to inspect it or save it for use in an authorized reference. The provided SVGs do not include a licensed font package for redistribution.'],links:[link('Download wordmark SVG','/brand/webcanbe-logo.svg'),link('Download symbol SVG','/brand/webcanbe-mark.svg')]},
      {title:'Color and background',paragraphs:['Use the existing Webcanbe violet as the primary brand color with readable foreground contrast. On a light background, the mark should remain distinct from surrounding copy and controls.','Do not place the transparent symbol inside an invented white tile or add gradients, outlines, shadows or animation that change the mark. Check both small and large sizes before publishing.']},
      {title:'Clear space and minimum size',paragraphs:['Keep other marks and text away from the logo so its form does not merge with adjacent content. At small sizes, prefer the symbol only when the product name is present nearby.','If the wordmark is no longer legible in the intended medium, increase its displayed size rather than stretching or redrawing the SVG. Use the site asset itself as the reference for its geometry.']},
      {title:'Affiliation and questions',paragraphs:['An accurate mention of Webcanbe is different from claiming endorsement or a formal partnership. Do not change the mark or imply approval of another product without agreement.','For co-branded uses, send the proposed placement and context through Partnerships before publishing.'],links:[link('Partnerships','/contact/partnerships')]},
    ],
  },
}

companyPages['/about'].sections.splice(-1,0,
  {title:'A project journey in practice',paragraphs:['A buyer might begin with Aperture North, inspect the project’s long page in the live preview, and decide whether the editorial sections fit a portfolio. After creating a working copy, they can change a heading in Visual, inspect the actual file in Code, and verify the accepted revision in History. The original first-party template stays unchanged.','The same buyer can export the accepted source and run it in their own environment. Package dependencies and any external service configuration remain part of that project’s setup. This journey is the standard we use to judge whether discovery, editing and export describe one real source rather than disconnected demonstrations.'],links:[link('Explore Aperture North','/project/aperture-north'),link('Getting started','/docs/getting-started')]},
  {title:'What we make explicit',paragraphs:['The product should distinguish a preview from an editable working copy, a Code draft from accepted source, and a payment approval from a captured transaction. Those distinctions help users decide what can be trusted after refresh or export.','Compatibility also has boundaries. A page may render while one Visual control cannot safely map a dynamic expression to source. The editor should show that limit and let the user continue in Code. A Creator listing should state its own stack and external setup rather than implying that every project works without configuration.'],links:[link('Compatibility','/docs/compatibility'),link('Security','/docs/security')]},
)
companyPages['/updates'].sections.push(
  {title:'How to try the public flow',paragraphs:['Start at Marketplace, open a project detail, then open its full preview. Compare the project title, images and visible content across those views. For a first-party template, sign in and create a separate working copy if the action is available to your account.','The getting-started guide walks through a small Visual change, Code inspection, History and export. If a screen differs from the guide, report the exact route and action so the current implementation can be checked.'],links:[link('Aperture North detail','/project/aperture-north'),link('Getting started','/docs/getting-started')]},
  {title:'How to use the Creator improvements',paragraphs:['An applicant begins at the Creator application, not by switching an account flag. A submitted application has a review state. Approved access leads to preparation, validation and submission in the Creator workspace.','A published release is a separate immutable record from the draft that produced it. Creators should compare the public preview and listing against the approved source, then use a new version for future changes.'],links:[link('Creator application','/seller/apply'),link('Release guide','/docs/creators/releases')]},
  {title:'How to interpret account and payment states',paragraphs:['Purchases, project working copies and subscriptions are different screens because they answer different questions. A buyer can have a completed order before creating a working copy. A plan can change account capacity without granting every Marketplace release.','A provider approval is not itself proof of capture or entitlement. The account should show a final server-confirmed state after checkout. Use Billing Help for a transaction that does not reconcile.'],links:[link('Purchases guide','/docs/purchases/acquire'),link('Billing Help','/contact/billing')]},
)
companyPages['/changelog'].sections.push(
  {title:'23 September 2026 — public link measurement',paragraphs:['Improved: navigation from static public routes can be measured with a privacy-safe link event before leaving the page. The event does not replace the destination or make a failed analytics request block the user’s click.','For users: a support or documentation link should still work if measurement is unavailable. This entry describes a source change, not evidence that every production visitor was tracked.'],links:[link('Privacy Policy','/legal/privacy'),link('Documentation','/docs')]},
  {title:'23 September 2026 — published asset consistency',paragraphs:['Improved: generated public pages share footer data, metadata and routes so a direct visit, refresh and internal click identify the same page. The build process generates explicit HTML for public destinations instead of treating a home-page fallback as a real article.','For users: bookmark the exact guide or legal URL. If a link returns the wrong page, use Report an Issue with that address.'],links:[link('Report an Issue','/contact/issues'),link('Legal overview','/legal')]},
  {title:'What these entries do not assert',paragraphs:['A repository change can be built and tested before it reaches the production domain. A paid flow can have UI and server code without a verified live capture. The Changelog does not turn either state into a customer success story.','For account-specific availability, check the live screen and its authoritative record. The Updates page explains how to try current product workflows, while documentation covers detailed steps and boundaries.'],links:[link('Updates','/updates'),link('Billing guide','/docs/billing/plans')]},
)
companyPages['/github'].sections.push(
  {title:'A local source workflow',paragraphs:['After exporting a working copy, unpack it outside the browser and inspect the package manifest. Install dependencies using the project’s documented package manager, run its build command, and preview the result. Keep any required license and NOTICE files alongside the source.','Create a new repository under an account you control only after confirming the project license permits the intended distribution. Add environment variable names to setup instructions, while storing values in the host’s secret settings.'],links:[link('Export guide','/docs/export'),link('Licenses','/legal/licenses')]},
  {title:'What to put in version control',paragraphs:['Commit the source, configuration that is safe to share, lockfile, and documentation needed to reproduce the build. Avoid committing tokens, database exports, private customer content or generated credentials. A `.gitignore` file helps, but review the actual staged diff before a push.','A repository history can make later changes easier to review. It does not replace Webcanbe’s accepted source History for work done in the editor, so compare the exported revision with your first local commit.']},
  {title:'Deployment is a separate check',paragraphs:['A successful local build shows that the exported source compiled in that environment. It does not confirm that a custom domain, worker, API or external service is configured in production. Check the deployed HTML and asset URLs, required environment variables, and a real browser interaction after publishing.','If a project uses a payment or account provider, follow that provider’s own approved verification path. Do not use a screenshot of a dashboard as proof that a live transaction completed.'],links:[link('Compatibility','/docs/compatibility'),link('Integrations','/docs/integrations')]},
  {title:'When to ask Webcanbe',paragraphs:['If export omits an accepted source change, include the project and revision reference in a support request. If the local build requires an undocumented dependency, include the package name and safe error text. Do not send private source or credentials unless a secure channel is explicitly arranged.','For an account connection, check whether the feature is shown as connected, requires configuration or is unavailable. A visible GitHub logo alone is not confirmation that a repository was created or synchronized.'],links:[link('Report an issue','/contact/issues'),link('Account Help','/contact/account')]},
)
companyPages['/brand'].sections.push(
  {title:'Use the real files',paragraphs:['The current site serves a wordmark SVG and a symbol SVG. Inspect their viewBox and shapes rather than rebuilding the mark from a raster screenshot. The files are transparent so they can be placed on a suitable background without a white patch behind the symbol.','If you need a different export format, render from the SVG at the intended size and check edge quality. Do not stretch the mark to fit a banner or generate an unrelated substitute.'],links:[link('Wordmark SVG','/brand/webcanbe-logo.svg'),link('Symbol SVG','/brand/webcanbe-mark.svg')]},
  {title:'Practical placement examples',paragraphs:['In a site header, the full wordmark can link to the Webcanbe home page. In a compact icon slot, the symbol can be used when adjacent text or accessible labeling names Webcanbe. In a written article, plain text is often clearer than a small logo.','Provide a meaningful accessible name for a linked logo. If the same nearby text already names the product, make a decorative duplicate image silent to screen readers. Focus treatment belongs on the interactive link, not as an underline animation across the mark.']},
  {title:'Check contrast and space',paragraphs:['Use the mark against a surface where its violet and dark forms remain clear. Do not rely on a faint outline or shadow to rescue low contrast. Keep surrounding UI controls and other logos far enough away that the mark reads as one unit.','Test at the size it will actually appear on desktop and mobile. If the wordmark becomes hard to read, use a larger size or the symbol with visible product name rather than trimming the letters.']},
  {title:'Requests for co-branding',paragraphs:['A partner proposal should describe the planned context, audience, placement and distribution channels. Ordinary accurate identification does not imply a formal relationship. A joint promotion or endorsement needs agreement before the marks are placed together as if approved.','Do not bundle a site font, third-party icon pack or unrelated creative asset as part of the brand download. The two linked SVGs are the concrete assets offered here.'],links:[link('Partnerships','/contact/partnerships')]},
)

companyPages['/updates'].sections.push({title:'A direct check after an update',paragraphs:['Open a route directly, refresh it, and use its primary action. The page should retain its identity instead of returning home with a success status. In an editor, compare the visible preview, accepted revision and export after a small saved change.','For a billing or account change, rely on the final server state shown in the relevant screen. A brief loading message or provider approval is not the completed result. Report a mismatch with the exact route and safe reference.'],links:[link('Report an issue','/contact/issues'),link('Documentation','/docs')]})
companyPages['/changelog'].sections.push({title:'Verify an entry in the product',paragraphs:['Each entry points to a behavior you can inspect: a public route, a request reference, a working-copy revision or an export. Open the linked screen and check the result in your own account where access is required.','If an entry concerns a backend transaction, source history alone does not prove that a particular order completed. Use Purchases, Billing or the relevant Creator ledger to inspect the authoritative state.'],links:[link('Purchases guide','/docs/purchases/acquire'),link('Contact','/contact')]})
companyPages['/github'].sections.push({title:'Sharing a reproducible change',paragraphs:['If you report a source issue through a public repository that is actually accessible, provide a minimal reproduction using material you are permitted to publish. State the runtime, build command, expected result and actual result.','For a private working copy or paid release, use Webcanbe support and a safe project reference. A public issue should never contain a buyer’s source, account identifier, session data or a live service token.'],links:[link('Report an issue','/contact/issues')]})
companyPages['/brand'].sections.push({title:'An accessibility review before publication',paragraphs:['A logo used as a link needs a destination and an accessible name such as Webcanbe home. A decorative duplicate mark can use empty alternative text when adjacent text already identifies the product.','Check focus appearance on the link itself. Removing a decorative line must not remove keyboard focus. Check hover, focus, active and visited states at the actual size used on the page.'],links:[link('About Webcanbe','/about')]})
