import type { InfoPage } from './public-pages'

const link=(label:string,href:string):[string,string]=>[label,href]

export const companyPages:Record<string,InfoPage> = {
  '/about':{
    title:'About Webcanbe',
    intro:'Webcanbe helps people start from a real web project, make an independent working copy, edit the source, and take that source with them.',
    sections:[
      {title:'The problem we work on',paragraphs:['A screenshot, static mockup or locked page builder can show a promising result while leaving the actual project out of reach. Rebuilding that result later costs time and makes every edit depend on the original tool. Webcanbe starts with a source project that can become your own working copy.','A useful starting point needs more than a nice thumbnail. You should be able to inspect the project, understand what the release contains, review its compatibility and license, and see how it behaves before committing to it.'],links:[link('Explore projects','/browse'),link('Marketplace guide','/docs/marketplace')]},
      {title:'From discovery to your working copy',paragraphs:['The Marketplace is for finding projects with a concrete release and a clear use case. A project detail and preview should represent the same release that is offered for use. When access is granted, your working copy is separate from the Creator’s published version.','That separation matters when you test an idea or return days later. Your saved changes belong to the working copy, while the released source remains a stable reference for the listing and license.'],links:[link('Getting started','/docs/getting-started'),link('Working copies','/docs/working-copies')]},
      {title:'One source across editing views',paragraphs:['Visual mode is for supported text and style changes in context. Code mode lets you open and change the files directly. Split keeps rendered work and source in view together. The supported Visual controls are tied to source targets rather than a separate drawing layer.','AI editing is a reviewed proposal flow: a proposed change is not accepted source until you inspect and apply it. History then helps you understand accepted revisions. When a visual target is ambiguous or unsupported, Code is the route to make a deliberate source edit.'],links:[link('Visual editor','/docs/visual-editor'),link('Code editor','/docs/code-editor'),link('AI editing','/docs/ai-editing')]},
      {title:'Source you can continue using',paragraphs:['A working copy can be exported as project files for work outside Webcanbe. The exported project may have its own package dependencies, assets or external services, so its setup instructions and license still matter. The ability to leave with source is part of the product rather than an afterthought.','We aim to make the boundaries visible: what is a preview, what has been saved as accepted source, what requires a third-party account, and what belongs to a specific released license.'],links:[link('Export guide','/docs/export'),link('Licensing','/docs/marketplace/licenses')]},
      {title:'For buyers and Creators',paragraphs:['Buyers can compare projects, inspect their details, and create a copy when the release and their account permit it. A Marketplace purchase is not the same record as a working copy; the product should show the next step when an acquired release has not yet been copied.','Creators prepare source, describe compatibility and rights, submit for review, and publish versioned releases through the Creator workflow when approved. A draft submission is not presented as a published listing.'],links:[link('Purchases guide','/docs/purchases/acquire'),link('Creator guide','/docs/creators'),link('Apply to become a Creator','/seller/apply')]},
      {title:'Meet CEO',body:'SIHOO MIN leads Webcanbe. Learn more about the person behind the product on his own site.',links:[link('Meet SIHOO MIN','https://msihu.com')]},
    ],
  },
  '/updates':{
    title:'Product updates',intro:'A product-focused view of implemented changes and the steps they make possible. Planned work is identified separately from changes available now.',
    sections:[
      {title:'Public discovery and documentation',paragraphs:['The public Marketplace and documentation routes make the product easier to evaluate before sign-in. Visitors can read the project workflow, compatibility notes, legal terms and support guidance directly.','The route and title for each guide are kept separate so a copied link opens the same subject on refresh. Start with the getting-started guide if you are moving from a listing to a working copy for the first time.'],links:[link('Getting started','/docs/getting-started'),link('Marketplace','/browse')]},
      {title:'Working-copy and source verification',paragraphs:['The working-copy path is designed to keep the accepted source, rendered preview, History and export aligned. A supported Visual edit and a Code edit should remain visible after reopening the project and in the exported files.','Use History to inspect accepted changes. A temporary draft or AI proposal is not a saved revision until it is applied and accepted.'],links:[link('History','/docs/history'),link('Export','/docs/export')]},
      {title:'Requests for help',paragraphs:['Support requests have specific categories so account, billing, seller and technical questions can be routed with useful context. The form returns a case reference after successful creation.','A support submission records a request; it does not by itself complete a refund, change an account permission or send a provider email. Signed-in users can revisit their own request status.'],links:[link('Contact','/contact'),link('My Requests','/requests')]},
      {title:'Creator workflow',paragraphs:['Creator access starts with an application and approval. Approved Creators have a separate workspace for project preparation and submission. Published releases are versioned; a draft or a pending review should not appear as a live listing.','The Creator guides cover listing rules, licensing, releases, and fees. Check those before preparing a project for submission.'],links:[link('Creator guide','/docs/creators'),link('Apply','/seller/apply')]},
      {title:'What to verify before relying on a feature',paragraphs:['Availability can depend on account permissions and live configuration. Check the screen you are using for the actual state of a project, plan, order or Creator application.','For implementation history, use the Changelog. For a product issue, a support request is the place to include the affected route and reproducible steps.'],links:[link('Changelog','/changelog'),link('Report an issue','/contact/issues')]},
    ],
  },
  '/changelog':{
    title:'Changelog',intro:'Shipped source and product changes grouped by date. This record describes implemented work without treating a repository commit as proof of a live payment or customer outcome.',
    sections:[
      {title:'23 September 2026 — public navigation and Requests',paragraphs:['Improved: public routes now have dedicated navigation, metadata and support categories. Visitors can use a direct link to reach the intended guide or contact form.','Added: support submissions use persisted Requests and return a case reference. The separate Requests screen lets an authenticated requester revisit their case.','For users: choose the form that matches the question and save the returned reference. A created case is awaiting review.'],links:[link('Contact channels','/contact'),link('Requests','/requests')]},
      {title:'22 September 2026 — Marketplace and documentation shell',paragraphs:['Added: a public Marketplace entry and project category routes. These routes give visitors a way to evaluate project types and read the workflow before account access.','Improved: documentation has its own navigation and search, with direct routes for Visual, Code, AI, History, export and compatibility.','For users: evaluate a particular release and its license from the detail screen before creating a working copy.'],links:[link('Browse projects','/browse'),link('Documentation','/docs')]},
      {title:'21 September 2026 — source-backed editing evidence',paragraphs:['Verified in development: a working-copy flow recorded a supported Visual source change, a Code revision, reopen, and an independent export build. This is evidence for that flow, not a promise that every project or source pattern supports the same controls.','Improved: the guides distinguish accepted source from draft, preview-only selection and an unapplied AI proposal.'],links:[link('Visual editor','/docs/visual-editor'),link('Code editor','/docs/code-editor'),link('Export','/docs/export')]},
      {title:'How to read these notes',paragraphs:['Added describes a new route or capability. Improved describes a changed user path. Fixed describes a specific defect after it is verified. A feature listed in source history can still require account access, a compatible release, or live service configuration.','This page intentionally avoids unpublished security details, invented customers and unverified transaction success. If a listed behavior does not match the live product, report the route, action and visible result.'],links:[link('Report an issue','/contact/issues'),link('Updates','/updates')]},
    ],
  },
  '/github':{
    title:'Webcanbe and GitHub',intro:'Understand where GitHub fits when you own and export a Webcanbe project, and where to take product questions.',
    sections:[
      {title:'Export comes first',paragraphs:['Webcanbe’s source ownership promise is about the files in a working copy. Export produces those files and the project assets that belong to the accepted revision, subject to the release license.','After export, you can inspect the files locally, install the project dependencies and build with the commands in that project. Check any environment variables or external services before deployment.'],links:[link('Export guide','/docs/export'),link('Compatibility','/docs/compatibility')]},
      {title:'Using a repository for your work',paragraphs:['You can place your exported project in a repository you control when its license and included assets permit that use. Review the package manifest, notice files and secrets before committing.','A repository can track later changes and collaboration, but Webcanbe does not claim that exporting automatically creates or synchronizes a GitHub repository.'],links:[link('Buyer License','/legal/buyer-license'),link('Third-Party Notices','/legal/third-party-notices')]},
      {title:'What a Webcanbe integration means',paragraphs:['A GitHub button or account connection in the product should be read according to its current screen state. If it is unavailable, use export and a local repository workflow instead of assuming a push happened.','A successful local build is separate from production deployment. Review the exported project’s own deployment instructions and required secrets.'],links:[link('Integrations','/docs/integrations'),link('Report an issue','/contact/issues')]},
      {title:'Product and account support',paragraphs:['Public issue trackers are the wrong place for private account information, paid orders, project source or a suspected vulnerability. Use the Webcanbe support category that matches the concern.','For a reproducible UI or export problem, include the route, action, expected result and actual result without posting credentials or private source.'],links:[link('Contact Webcanbe','/contact'),link('Security report','/contact/security')]},
    ],
  },
  '/brand':{
    title:'Webcanbe brand assets',intro:'The product name, wordmark and symbol are available here for accurate identification and approved references.',
    sections:[
      {title:'The name',paragraphs:['Write Webcanbe as one word with a capital W. Use the name to identify the source-first project marketplace and workspace accurately.','Do not describe an unrelated project, a Creator listing or a third-party service as an official Webcanbe product.'],links:[link('About Webcanbe','/about')]},
      {title:'Wordmark and symbol',paragraphs:['The wordmark is the preferred full brand signature. The symbol is useful where the product name is clear from the surrounding context. Keep the original SVG proportions and enough clear space for recognition.','Both downloads below are the actual site assets. Open the SVG to inspect it or save it for use in an authorized reference. The provided SVGs do not include a licensed font package for redistribution.'],links:[link('Download wordmark SVG','/brand/webcanbe-logo.svg'),link('Download symbol SVG','/brand/webcanbe-mark.svg')]},
      {title:'Color and background',paragraphs:['Use the existing Webcanbe violet as the primary brand color with readable foreground contrast. On a light background, the mark should remain distinct from surrounding copy and controls.','Do not place the transparent symbol inside an invented white tile or add gradients, outlines, shadows or animation that change the mark. Check both small and large sizes before publishing.']},
      {title:'Clear space and minimum size',paragraphs:['Keep other marks and text away from the logo so its form does not merge with adjacent content. At small sizes, prefer the symbol only when the product name is present nearby.','If the wordmark is no longer legible in the intended medium, increase its displayed size rather than stretching or redrawing the SVG. Use the site asset itself as the reference for its geometry.']},
      {title:'Affiliation and questions',paragraphs:['An accurate mention of Webcanbe is different from claiming endorsement or a formal partnership. Do not change the mark or imply approval of another product without agreement.','For co-branded uses, send the proposed placement and context through Partnerships before publishing.'],links:[link('Partnerships','/contact/partnerships')]},
    ],
  },
}
