export type ExtendedGuideSection = {title:string;paragraphs:string[];steps?:string[]}

export const expandedGuideSections:Record<string,ExtendedGuideSection[]> = {
  '/docs/split-view':[
    {title:'Choose Split for a source question',paragraphs:['Split is useful when a rendered element and its implementation need to be considered together. Start with a working copy that has a successful preview and an accepted revision. Open the file related to the part of the page you want to change, then move to Split. The preview and Code pane should refer to the same project, even though a local Code draft is not yet accepted.','Use Visual selection to find a source-backed target when the control is supported. If selection is unavailable, open the file in Code and search for the text, component or style rule. Do not treat a highlighted preview element as a saved source change.'],steps:['Open an existing working copy and note its current accepted revision.','Enter Split and select a visible element or the corresponding file.','Compare the rendered value with the source before editing.']},
    {title:'Scroll each pane independently',paragraphs:['Place the pointer over the preview and scroll toward the bottom of the project. The project page should move while the Code pane and Webcanbe toolbar stay available. Next place the pointer over a long source file and scroll to its last line; the preview should keep its position. A file tree, layers panel and Inspector have their own scroll area when their contents exceed the pane.','When changing preview width or zoom, recheck the selected element after the layout settles. A visible outline must track the real element, including after scrolling. If wheel input appears to do nothing, distinguish an overlay that captured it from a project whose page genuinely has no more content.'],steps:['Scroll the preview to its last meaningful section and confirm the editor toolbar remains visible.','Scroll the Code pane to the last source line without changing the preview position.','Repeat once after switching to a narrow preview width.']},
    {title:'Keep a draft separate from accepted source',paragraphs:['Typing in Code changes a draft. The accepted preview and export should remain tied to the last validated revision until the draft is saved successfully. Save the current file or all drafts through the supported command, then wait for validation and the accepted revision state. A syntax error should keep the draft available for correction instead of replacing the working project with invalid source.','If a Visual change is accepted while Code contains a draft, inspect both states before saving. Do not assume that simply switching tabs committed the Code work or that a preview refresh discarded it.'],steps:['Make a small Code change and inspect the dirty state.','Save and confirm a new accepted revision appears.','Reopen the project and verify that the rendered change and source agree.']},
    {title:'Move between Visual and Code deliberately',paragraphs:['A supported Visual edit should appear as an actual source change. In Split, compare the selected element with the file and source range reported by the editor. Make one small Visual text or style change, accept it, then inspect the corresponding Code diff. This is more reliable than inferring a source change from a temporary preview overlay.','For a value produced by props, shared components or a dynamic expression, the Inspector may be read-only. Use Code to change the relevant definition with knowledge of its scope. Check other instances of a shared component before treating the result as local to one element.']},
    {title:'Recover from a mismatch',paragraphs:['If the preview remains on an older revision, first check whether the Code change is still a draft, validation failed, or the preview connection is reconnecting. Preserve the draft before retrying. If another tab accepted a newer revision, inspect the conflict instead of overwriting it with stale source.','History is the place to inspect accepted revisions. It cannot be used to prove that unsaved typing or an unapplied AI proposal was accepted. If the result is still inconsistent, include the project reference, active mode, revision and safe error text in a support request without sending private source.'],steps:['Check the current accepted revision and the draft indicator.','Correct validation or stale-revision errors before retrying save.','Confirm the preview, History and exported source after acceptance.']},
  ],
  '/docs/getting-started':[
    {title:'Find a starting point that matches your task',paragraphs:['Open Marketplace and compare a project by purpose, included files, visible preview, license and compatibility. A thumbnail tells you what a release looks like, but the full detail should tell you what it contains and what you may do with it. Use the preview to scroll beyond the hero and try the interactions relevant to your use case.','Aperture North and Stillform are Webcanbe first-party source templates. They have distinct layouts and can be used to practice the working-copy flow. A Creator-published release has its own immutable version, rights record and price; inspect that listing separately before purchase.'],steps:['Choose a listing whose source and license fit your intended use.','Inspect its detail, gallery or preview and the compatibility information.','Keep the listing or release reference before signing in.']},
    {title:'Sign in and create your own copy',paragraphs:['Use the project’s action to create a working copy or begin its actual purchase path. If sign-in is required, the app should return you to the intended destination afterward. A paid release may require provider approval and server-confirmed entitlement before a working copy can be made. A free first-party template can follow a different acquisition path.','Your working copy is independent of the released source. Giving it a name and opening it in your workspace should not change the original listing or another project. If a checkout return is uncertain, check Purchases rather than clicking Pay again blindly.'],steps:['Follow the project action and complete required sign-in or checkout.','Confirm the resulting purchase or template access state.','Open the new project in your workspace.']},
    {title:'Make a first source-backed Visual edit',paragraphs:['Open Visual and choose a supported text element. Make a small, recognizable change, such as a heading in a first-party template. Inspect the control’s scope before applying: a shared component can appear more than once. Save the change and wait for acceptance, then refresh the page to make sure the value returns from the stored project.','If the text control is unavailable, read the reason. The source can still be changed in Code when a Visual target is dynamic or ambiguous. Do not replace the template with a screenshot or isolated demo string to make one control appear editable.'],steps:['Select a supported heading and check its source context.','Change the text and save it as an accepted revision.','Refresh or reopen and confirm the edited text remains.']},
    {title:'Inspect the actual files in Code',paragraphs:['Switch to Code and locate the file that contains your edit. Compare the accepted source with the rendered result. Make another small, valid source change and save it. If validation rejects the draft, correct the error and retry while retaining the last accepted preview.','History should show accepted revisions from the Visual and Code work. It should not claim that unsaved text, a failed save or a proposal was applied. The same source is the basis for export, so inspecting it here is a direct check on what you will take away.'],steps:['Open the changed file and find your Visual edit.','Make a small Code change, validate and save.','Review the accepted revision in History.']},
    {title:'Export and continue locally',paragraphs:['Export the accepted working copy as project files. Keep the license and any notice files with the project. After download, unpack into a new directory and read the project package manifest and setup instructions before installing dependencies. A project can also require service keys or environment variables that are not included in a portable archive.','Build and run the exported source independently to confirm your edits traveled with it. If a local build fails, inspect the package scripts, runtime version and missing external-service setup. Report an export mismatch with the project and accepted revision, not with secrets or private source pasted into a public issue.'],steps:['Download and unpack the export.','Run the project’s documented install and build commands locally.','Compare the final rendered result with the saved working copy.']},
  ],
  '/docs/creators/rules':[
    {title:'Prepare a project a buyer can actually use',paragraphs:['A Marketplace project needs a functioning source release, not a screenshot of a page or a compiled artifact with no editable implementation. Organize the source so a buyer can understand where content, styles, assets and configuration live. Provide a preview that corresponds to the release you submit.','A clear listing describes the project’s purpose and supported stack. It should not promise that every visible element is Visual-editable if dynamic logic, external services or CSS patterns limit some controls. Buyers can use Code for those cases, but they need to know what is included.'],steps:['Open the source in the supported runtime.','Build and preview the result at desktop and mobile widths.','Compare the listing claims with the actual source and interactions.']},
    {title:'Account for rights in every asset',paragraphs:['Review images, fonts, icons, packages and any copied code before submission. You must have the right to distribute what the buyer will receive under the relevant license. A link to an asset is not proof of redistribution rights. Record attribution and third-party terms in files that ship with the release.','Avoid including credentials, private data, paid API keys or another customer’s content. Where an external service is required, document the setup and use safe placeholders rather than embedding a live secret in source.'],steps:['List every asset and its origin.','Include accurate package manifests and license or NOTICE files.','Remove live secrets and private data before upload.']},
    {title:'Make the preview honest',paragraphs:['The detail, gallery and live preview must identify the same project and release. A decorative image can help explain the project, but it must not substitute for a working preview or imply interactions the source does not contain.','If a template has a filter, tab, gallery, contact form or dashboard control, confirm that it changes real state as described. Do not show a success message for a submission that has no backend. If an interaction needs external configuration, identify that requirement on the listing.']},
    {title:'Expect review and possible revision',paragraphs:['Submitting a project does not publish it immediately. Validation can report source, compatibility, licensing or metadata issues. A reviewer may return a submission for corrections; the Creator should keep the reason associated with that submission and resubmit a corrected version.','A published release is immutable for buyers who acquired it. Later improvements belong in a new release with its own version and changelog. Do not silently replace files or change the license grant tied to an earlier completed order.'],steps:['Review validation findings for the submitted revision.','Correct the affected source or metadata and submit the revised version.','Verify publication only after the approved release appears in the catalog.']},
    {title:'Know which record is authoritative',paragraphs:['Creator drafts, submissions, reviews, releases, listings, orders and payout records have different meanings. A saved project is not proof of publication. A listed price is not proof of a completed order. The Creator workspace should show each state from the server record rather than relying on a locally changed role flag.','For a listing or submission question, contact Seller Support with the safe reference and visible status. For a suspected rights issue, stop distribution of the problematic material while the case is reviewed.']},
  ],
  '/docs/creators/fees-payouts':[
    {title:'Read the order and ledger separately',paragraphs:['A listing price is the buyer-facing amount selected for a release. A checkout attempt, provider approval, capture, entitlement, fee allocation and Creator ledger entry are distinct events. Do not count an abandoned or failed approval as a sale.','Creator revenue should be read from the authoritative ledger for completed eligible transactions. The actual fee schedule and payout conditions are governed by the current Creator agreement and the values shown in Creator Studio; this guide does not invent a percentage or promise a calendar date.'],steps:['Identify the completed order and its released project.','Compare captured amount, applicable fee and Creator ledger entry.','Check whether any refund, dispute or hold has changed the balance.']},
    {title:'Understand held and available balances',paragraphs:['A captured sale can remain held while the applicable review and dispute conditions are processed. Held does not mean paid out. Available is the amount currently eligible under the payout process, while paid identifies a completed payout record.','A refund or dispute can create a reversing ledger entry rather than erasing the original sale. That history matters when a Creator reconciles a period. If numbers differ from the provider or order view, use the order and payout references to request a review.']},
    {title:'Check payout batch state',paragraphs:['A payout request or batch has its own state and supporting ledger entries. Opening a support case does not create a payout, move funds or mark a batch paid. The Creator workspace should show what is held, available, scheduled or completed according to its real records.','Before reporting a missing payout, compare the relevant period and currency, recent refunds, disputes and any hold. Do not send bank details in the first support message. Use a safe batch reference and the state shown in the product.'],steps:['Open the Creator earnings and payout views.','Compare the dates and USD amounts shown for the relevant orders and payout batches.','Submit a Payout Issue with references if the records still disagree.']},
    {title:'Keep buyer purchase terms distinct',paragraphs:['The buyer’s completed order can grant access to an immutable release under its recorded license. The Creator’s payout entitlement is derived from the applicable sale and agreement; it is not the same as the buyer’s working copy.','Changing a listing or publishing a new version does not retroactively change an earlier captured order or its fee record. Any correction should be auditable in the ledger and linked to the affected transaction.']},
    {title:'Where to ask for help',paragraphs:['Use Seller Support for a submission or listing question and Payout Issue for a batch or ledger discrepancy. Billing Help is for a buyer’s purchase or subscription concern. Providing the right reference lets support reconcile the correct authority without exposing payment credentials.','A support response may explain a ledger state or start a review. It should not be mistaken for provider confirmation or an actual transfer. Check the Creator payout record again after any stated action.']},
  ],
  '/docs/creators/releases':[
    {title:'Separate draft source from a release',paragraphs:['A Creator project can be edited and saved many times before submission. Those working revisions help prepare the product, but buyers acquire a specific approved release, not the Creator’s moving draft.','Before submitting, verify the source, assets, manifest, setup instructions, preview and listing description together. A preview built from a later draft cannot prove that an earlier release contains the same behavior. Record the candidate revision that enters review.'],steps:['Choose the source revision to submit.','Build and preview that revision with its own files.','Check metadata, assets and rights evidence before submission.']},
    {title:'Use review feedback as a versioned change',paragraphs:['Validation and human review can return different findings. A source error may need a new build; an inaccurate listing may need metadata correction; a rights concern may require replacing an asset or providing evidence. Keep each response tied to the submission it addresses.','If you change source after review begins, submit the corrected candidate through the supported workflow instead of silently replacing files behind the reviewer’s reference. The review history explains which version was assessed.']},
    {title:'Publish an immutable buyer reference',paragraphs:['After approval, publication should create a release identifier and a listing that points to that exact source package. Detail, gallery, preview, price and buyer access need to agree on that identity.','A buyer who acquired that release keeps the license and access determined by the completed transaction and the recorded terms. Updating a live listing description must not alter the files already acquired under the earlier release.'],steps:['Confirm the approved release identifier.','Open the public detail and preview as a visitor.','Compare the rendered project and package with the approved source.']},
    {title:'Create the next release',paragraphs:['A subsequent version should explain what changed, including compatibility or migration concerns. Preserve the older release record so orders and working copies remain traceable. A new version can be promoted for new buyers without rewriting previous grants.','Test the new candidate as a fresh acquisition as well as an existing buyer. A buyer may need to choose whether to start from the new release rather than having their working copy overwritten.']},
    {title:'Correct an issue without hiding it',paragraphs:['When a release has a source defect or rights issue, use the Creator and operations workflow to review the impact. A corrected release can be issued, but a silent file replacement would make prior purchases and export evidence unreliable.','For an urgent question, include the listing, release and submission references in Seller Support. Do not use a public issue tracker for private buyer data or confidential source.']},
  ],
  '/docs/creators/licensing':[
    {title:'Know the Creator and buyer roles',paragraphs:['A Creator must have the authority to submit and distribute the source, assets and dependencies in a project release. The buyer receives the usage rights described by the recorded Buyer License and any release-specific terms after the applicable acquisition completes.','These roles are related but not interchangeable. Uploading source does not surrender every right to Webcanbe, and a buyer’s export does not erase third-party licenses or asset restrictions. Review the actual agreements before publishing or deploying derivative work.'],steps:['Review the Creator Distribution Agreement.','Check the Buyer License as a buyer would.','Compare both with the files and terms in the proposed release.']},
    {title:'Inventory source and asset rights',paragraphs:['For each image, icon, font, package and code fragment, identify its origin, license and any required notice. A project that builds successfully can still lack the right to redistribute a font or photograph.','Include manifests and attribution with the release. If an asset license permits display but not source redistribution, replace it with an asset you can ship or change the listing to exclude it clearly. A vague “free asset” label is not adequate evidence.'],steps:['List each nonoriginal asset.','Keep required license and attribution files in the project.','Inspect the exported package to confirm the notices travel with it.']},
    {title:'Describe external services honestly',paragraphs:['Some projects depend on a hosted database, payment provider, font host or image service. A buyer may need their own account and credentials to run the source. The listing should state that dependency and the included setup instructions.','Do not embed a Creator’s live keys or buyer data in the released package. Use documented environment variables and safe examples. The project can be sold as source with a required external setup, but the dependency must be clear before acquisition.']},
    {title:'Keep release terms stable',paragraphs:['A published release is an immutable source and rights reference for its buyers. A new Creator license or project version should not silently narrow rights already granted under a completed order.','When a rights mistake is discovered, use the review and support path so the affected release, orders and remedy are recorded. A replacement asset or new release can solve future distribution, while existing buyers may require a separate remedy.']},
    {title:'Help a buyer use the right files',paragraphs:['The buyer should be able to find the license, notice, manifest and setup instructions in an exported package. If the project includes attribution obligations or restrictions on a specific asset, document them where they can be preserved during deployment.','A buyer with a question about a completed order can use Billing Help; a Creator with a source-rights or submission concern can use Seller Support. Include the release identifier and a safe description of the issue.']},
  ],
  '/docs/integrations':[
    {title:'Start from the project’s actual dependencies',paragraphs:['An exported project can contain package dependencies, external URLs, environment variable names and deployment scripts. Read those files before assuming a Webcanbe account automatically provisions the services they mention.','The project listing and compatibility guidance should distinguish built-in editing capabilities from a service a buyer must configure. A preview can work with safe sample content while a production backend still requires the buyer’s own credentials and data.'],steps:['Open the project manifest and setup instructions.','Identify environment variables and external endpoints.','Confirm which services are required to build, preview and deploy.']},
    {title:'Use your own service accounts',paragraphs:['A database, email provider, payment provider or GitHub repository belongs to the account that configures it. Do not copy a Creator’s token or paste secrets into a public support request. Store production values in the hosting environment recommended by the service.','If a Webcanbe connection control is available for your account, follow its on-screen status and permissions. A button that opens an authorization window is not proof the connection succeeded; verify the resulting account and action.']},
    {title:'Check a connection with a reversible action',paragraphs:['After setting credentials or connecting a service, perform a small non-destructive check that exercises the intended path. For a repository workflow, inspect the resulting branch or export locally. For a deployment, confirm the generated site and asset URLs. For email or payments, use the provider’s approved test path before live traffic.','A successful preview alone may not exercise a backend integration. Compare the product state with the external service’s result rather than assuming a green toast means the remote operation completed.'],steps:['Save the settings in the intended account.','Run a safe test action.','Compare Webcanbe’s result with the provider or deployed output.']},
    {title:'Recover from configuration errors',paragraphs:['An expired token, missing permission, invalid URL or misnamed environment variable can fail at a different step. Check the exact error and whether the external service received anything. Avoid re-running a potentially chargeable action without confirming its first attempt.','For an exported project, follow its own build and runtime logs. For a Webcanbe account connection, recheck scope and account identity. If the issue persists, create a support case with the route and redacted error; never include the credential itself.']},
    {title:'Know what is not a public API',paragraphs:['Webcanbe documentation of an internal editor or marketplace operation is not a public API contract. Do not build against undocumented endpoints or assume a Creator can bypass submission review by calling a private route.','Use the supported product controls and export path for current workflows. If you need a specific integration for a team or published project, ask Sales or Partnerships for the currently supported options and requirements.']},
  ],
}

expandedGuideSections['/docs/creators/rules'].push({title:'A pre-submission review you can repeat',paragraphs:['Before every submission, ask someone unfamiliar with the project to follow its setup instructions in a clean environment. Record where they stop, whether assets load, and whether the listed interactions match the source. This catches assumptions hidden on the Creator’s machine without requiring a buyer to discover them after acquisition.','Then inspect the release package for secrets, private content and missing third-party notices. If the source contains an integration, verify that safe configuration instructions explain what the buyer must supply. Keep the review notes with the candidate submission so corrections can be tied to the same version.']})
expandedGuideSections['/docs/creators/fees-payouts'].push({title:'Reconcile an example without assuming a fee',paragraphs:['Suppose one completed order is visible in Sales but the payout view is lower than the listing price. Compare the captured amount, currency, fee line, refund or dispute entries, hold state and payout batch for that exact order. The difference may be expected under the recorded agreement, or it may require investigation; the listing price alone cannot decide it.','If the order is not captured, treat it as a checkout state rather than revenue. If the ledger and provider disagree, keep their references and timestamps for support. Do not calculate an invented payout rate from a screenshot or report an estimated balance as paid.']})
expandedGuideSections['/docs/creators/releases'].push({title:'Release checklist for buyers returning later',paragraphs:['A buyer may return to a purchased project after the Creator has published a newer version. The account should still identify the release the buyer acquired and the working copy created from it. A new release can be offered as another starting point, but it should not replace the files the buyer already edited.','When documenting a breaking change, explain which files, dependencies or configuration changed and whether an existing working copy can adopt the new version manually. This makes versioning useful without pretending every upgrade is automatic.']})
expandedGuideSections['/docs/creators/releases'].push({title:'A final preview check',paragraphs:['Open the published detail and preview after release. Confirm that the page title, visible interactions and included source version match the approved package. A buyer who starts from this release should see the same starting project before making their own edits.'],steps:['Check the public detail and full preview.','Compare the release identifier and setup instructions.','Open Seller Support if a mismatch needs review.']})
expandedGuideSections['/docs/creators/licensing'].push({title:'Use a rights checklist before pressing Submit',paragraphs:['Open the export or candidate package as a buyer would. Check the top-level license, package manifest, attribution files, included imagery and font files. Compare those files with the project detail claims. If a third-party license requires attribution in a user-facing page or redistributed source, make that obligation discoverable before acquisition.','Keep source provenance evidence in the Creator review record where the workflow permits it. Do not add someone else’s private license text or customer data to a public listing. If a term is uncertain, resolve it before publication rather than relying on a later support correction.']})
expandedGuideSections['/docs/integrations'].push({title:'Document the boundary at handoff',paragraphs:['When handing a project to another developer, include the exported source version, package commands, required environment variable names, and which external accounts must be configured. Leave credential values out of the handoff document.','The recipient should be able to build with safe local defaults, identify which runtime behavior needs a provider, and confirm the final deployment with its own logs. If a specific integration is only planned, label it as planned instead of presenting a decorative button as a completed connection.']})
expandedGuideSections['/docs/security']=[{title:'Security questions during a normal project workflow',paragraphs:['Before importing a project, inspect its source and listed dependencies. A preview can show behavior, but it does not certify that an external package or service is suitable for your organization. Keep production credentials outside project source and use accounts you control for connected services.','When sharing a support case, send the safe project reference, route and observed state. Do not paste a session token, payment credential, private source or another person’s data into the initial form. For a suspected vulnerability, use Security Report rather than a public issue.'],steps:['Review the source and dependencies before running them in your environment.','Use an account with the permissions needed for the action, then confirm the result.','Report a suspected exposure through the private security form with a minimal safe reproduction.']}]
