import legalReview from './legal-review-3.json'
export type InfoSection = { title:string; body?:string; paragraphs?:string[]; links?:[string,string][]; pendingFields?:string[] }
export type InfoPage = { title:string; intro:string; sections:InfoSection[]; version?:string; publicationBlocked?:boolean; unresolvedFields?:string[] }
export const supportChannels: Record<string,{title:string;category:string;intro:string;fields:[string,string][];guidance:string}> = {
 support:{title:'General Support',category:'general_support',intro:'Get help choosing the right workflow, finding a project or understanding an unexpected product state.',fields:[['project','Project reference (optional)']],guidance:'Describe what you were trying to do, what happened, and whether the issue repeats. Use Billing Help for transactions and Security Report for vulnerabilities.'},
 account:{title:'Account Help',category:'account_help',intro:'Get help with sign-in, account identity, provider linking or access to an existing account.',fields:[['account','Account ID (optional)'],['provider','Sign-in provider (optional)']],guidance:'Tell us the sign-in method and where the flow stops. Do not include passwords, verification codes, cookies or authentication callback URLs.'},
 sellers:{title:'Seller Support',category:'seller_support',intro:'Ask about a creator submission, listing, source release, review status or payout record.',fields:[['listing','Listing ID (optional)'],['submission','Submission ID (optional)'],['release','Release ID (optional)']],guidance:'Include the affected reference and the status shown in Creator Studio. Explain whether the question concerns metadata, source validation, rights or a transaction.'},
 billing:{title:'Billing Help',category:'billing',intro:'Resolve questions about orders, missing purchases, subscriptions, AI usage or refund review.',fields:[['order','Order reference (optional)'],['subscription','Subscription reference (optional)'],['plan','Plan or AI request reference (optional)']],guidance:'Include the approximate transaction time and the state you expected. Do not send card details, security codes or payment-provider credentials.'},
 issues:{title:'Report an Issue',category:'bug_report',intro:'Report a reproducible product error with enough context to help us investigate the right route and build.',fields:[['project','Project reference (optional)'],['steps','Reproduction steps'],['expected','Expected result']],guidance:'Include the action, actual result and frequency. Attachments are not currently supported; do not paste private source or secrets.'},
 sales:{title:'Talk to Sales',category:'sales',intro:'Discuss your intended Webcanbe use, project volume and requirements before choosing a plan or commercial arrangement.',fields:[['organization','Organization (optional)'],['needs','Requirements and expected usage']],guidance:'Tell us what you want to build, approximate usage and timing. This channel does not imply that custom features, service levels or pricing have already been agreed.'},
 partnerships:{title:'Partnerships',category:'partnership',intro:'Propose a concrete collaboration involving projects, education, distribution or an integration.',fields:[['organization','Organization (optional)'],['proposal','Partnership proposal']],guidance:'Explain the audience, proposed contribution and a useful first step. Link to public work you are authorized to share; keep confidential agreements out of the initial message.'},
 security:{title:'Security Report',category:'security_report',intro:'Privately report a suspected vulnerability or exposure affecting Webcanbe. Use only accounts and projects you control for a minimal reproduction.',fields:[['affected','Affected route or component'],['steps','Safe reproduction steps'],['impact','Potential impact']],guidance:'Stop testing before accessing another person’s data or disrupting service. Redact all live credentials. This guidance does not authorize unauthorized testing or promise a bounty, safe harbor or response deadline.'},
 privacy:{title:'Privacy Request',category:'privacy_request',intro:'Request access, correction, deletion, or another applicable privacy right.',fields:[['scope','Request scope']],guidance:'Provide only the information needed to identify the affected account. Additional identity verification may be required before any account-specific action.'},
 refunds:{title:'Refund Request',category:'refund_request',intro:'Create a case for transaction-specific refund review.',fields:[['order','Order reference'],['reason','Reason for review']],guidance:'A request does not approve or execute a refund. Do not include payment credentials.'},
 payments:{title:'Payment Dispute',category:'payment_dispute',intro:'Report a duplicate, reversed, disputed, or otherwise unexpected marketplace payment.',fields:[['order','Order reference'],['state','Payment state shown']],guidance:'This creates a case only. Provider reconciliation and any refund remain authoritative payment operations.'},
 payouts:{title:'Payout Issue',category:'payout_issue',intro:'Ask about a creator ledger balance, payout hold, or payout batch.',fields:[['payout','Payout batch reference'],['state','State shown']],guidance:'Sign in with the creator account. A request cannot initiate a payout or change ledger state.'},
}
const links=(...pairs:[string,string][])=>pairs
export const infoPages:Record<string,InfoPage>={
 ...(legalReview as Record<string,InfoPage>),
 '/about':{title:'About Webcanbe',intro:'Webcanbe is a source-first marketplace and workspace for real web projects: discover a usable starting point, make an editable copy, and leave with the code.',sections:[{title:'Discover real web projects',body:'Marketplace listings describe a specific released project rather than a generic template promise. You can review the project, its release information, compatibility notes and license before deciding whether it is a useful starting point for your work.',links:links(['Explore Marketplace','/browse'],['Marketplace guide','/docs/marketplace'])},{title:'Make an editable working copy',body:'Acquiring a project creates a separate working copy for your account. Your edits happen in that copy; they do not rewrite the creator’s released source. This gives you a clear place to build, save accepted revisions and return to later.',links:links(['Working copies','/docs/working-copies'],['Acquire a project','/docs/purchases/acquire'])},{title:'Visual, Code and Split',body:'Visual mode makes supported, source-backed changes through the interface. Code mode exposes the actual files. Split lets you move between both views while working from the same source and revision history. When a change is outside Visual support, Code remains available rather than hiding the source.',links:links(['Visual editor','/docs/visual-editor'],['Code editor','/docs/code-editor'],['Split view','/docs/split-view'])},{title:'Own the source and export it',body:'Webcanbe treats source as the product. History records accepted changes, and export gives you the accepted project files to keep working with outside Webcanbe. The applicable project license and third-party notices still matter; export does not erase them.',links:links(['Saving and history','/docs/history'],['Export','/docs/export'],['Licensing','/docs/marketplace/licenses'])},{title:'A marketplace for creators',body:'Creators can prepare a source project, submit it through Creator Studio, and publish a release when it meets the supported requirements. Their role is to offer useful starting points with accurate release, compatibility and licensing information—not to surrender ownership of the source.',links:links(['Creator application','/docs/creators'],['Creator Studio','/seller'])},{title:'Meet CEO',body:'Meet the person leading Webcanbe and follow their work.',links:links(['Meet CEO','https://msihu.com'])}]},
 '/updates':{title:'Product updates',intro:'Notes about changes that are present in the Webcanbe product and repository—not planned features or release speculation.',sections:[{title:'Requests and Creator operations',body:'Persisted customer Requests and the Creator environment are now separated into focused route assets. Customers receive a request reference after submission, while operations can work from the existing request queue.',links:links(['Contact','/contact'],['Creator Studio','/seller'])},{title:'Public marketplace and docs',body:'The public experience includes marketplace discovery, stable documentation routes, shared navigation and support paths. Documentation remains separate from account and workspace access.',links:links(['Marketplace','/browse'],['Documentation','/docs'])},{title:'Follow verified changes',body:'For implementation-level detail, inspect the public repository and the Changelog. Feature availability in an account continues to depend on the live product state and enabled configuration.',links:links(['Changelog','/changelog'],['Webcanbe on GitHub','/github'])}]},
 '/changelog':{title:'Changelog',intro:'A concise record of shipped repository changes. Entries are based on current project history and avoid claiming unavailable payment or deployment features.',sections:[{title:'2026-09-23 — Creator and Requests routes',body:'Creator route assets and request route assets were split so these product areas can evolve independently while retaining the persisted Requests backend.',links:links(['Contact','/contact'])},{title:'2026-09-22 — Public marketplace and documentation shell',body:'The public marketplace/docs shell and crawlable documentation routes were added, including shared footer navigation and public metadata generation.',links:links(['Marketplace','/browse'],['Documentation','/docs'])},{title:'2026-09-21 — Visual and Code durability proof',body:'The project recorded an integrated working-copy flow covering a source-backed Visual change, a Code revision, reopen, and standalone export/build verification.',links:links(['History guide','/docs/history'],['Export guide','/docs/export'])}]},
 '/github':{title:'Webcanbe on GitHub',intro:'Webcanbe’s public development presence is the Webcanbe/webcanbe-real repository on GitHub.',sections:[{title:'Inspect the project',body:'The repository is where you can inspect source history, public issues and development activity for Webcanbe. It is useful for technical context and contribution discussion; account access, marketplace purchases and workspace permissions are still handled through the Webcanbe product.',links:links(['Open Webcanbe/webcanbe-real','https://github.com/Webcanbe/webcanbe-real'])},{title:'Use product support for account-specific help',body:'Do not put private source, credentials, account details, payment data or security reports in a public issue. Use the appropriate Webcanbe request channel for those matters instead.',links:links(['Contact Webcanbe','/contact'],['Security report','/contact/security'])}]},
 '/contact':{title:'Contact Webcanbe',intro:'Choose the channel that fits your question. Each form creates a persisted case with a reference you can use to track the request.',sections:Object.entries(supportChannels).map(([slug,c])=>({title:c.title,body:c.intro,links:links(['Open '+c.title,'/contact/'+slug])}))},
 '/brand':{title:'Webcanbe brand assets',intro:'Use the Webcanbe name and supplied marks consistently when referring to the product.',sections:[{title:'Product name',body:'Write Webcanbe as one word with a capital W. Describe the product accurately as a source-first web project marketplace with visual and code editing.'},{title:'Downloadable marks',body:'Use these transparent SVG files on a clean background. Preserve their proportions and give the mark breathing room. Do not add a white tile behind the symbol on tinted surfaces.',links:links(['Webcanbe wordmark SVG','/brand/webcanbe-logo.svg'],['Webcanbe symbol SVG','/brand/webcanbe-mark.svg'])},{title:'Usage and affiliation',body:'These assets are provided to identify Webcanbe. Do not imply endorsement, alter the name or claim trademark rights. Contact Partnerships about co-branded uses that need an agreement.',links:links(['Partnerships','/contact/partnerships'])}]},
}
