import { family } from '../doc-types'
export default family('Account & authentication', [
['account/identity','Confirm your account identity','Check the signed-in account before investigating missing projects, purchases or plan access. Different provider identities can lead you to different account contexts.','Have the sign-in method used for the original purchase or working copy available. Do not create another account as the first step in recovering existing work.',[
'Open Settings and inspect the displayed account information and connected provider context.',
'Compare it with the identity used when acquiring the project. If you use multiple provider accounts, check which one was selected during sign-in.',
'Return to Purchases and Projects under the intended account and distinguish loading failures from empty lists.',
'Use Account Help if the identity or access still differs from what you expect. Include a safe account identifier if available.'
],'The account context should explain which private projects and entitlements you can access. Signing into a provider successfully is only useful if it returns to the intended Webcanbe account.','Never send passwords, session cookies, one-time codes or provider tokens to prove identity. A matching display name alone is not sufficient evidence that two accounts are the same. Account linking and recovery must use supported flows rather than manual credential sharing.',['sign-in','account/providers','purchases/missing']],
['account/providers','Sign-in providers','Use the authentication methods offered by the current Webcanbe sign-in screen. Provider availability depends on live configuration and should not be inferred from old documentation or screenshots.','Choose a provider or email method you can continue accessing. If you already have purchases, begin with the original method and account identity.',[
'Open Sign in and select an available method. Read the provider’s account-selection prompt carefully.',
'Complete verification through that provider or email flow and return to Webcanbe.',
'Confirm the resulting account in Settings before acquiring projects or changing account information.',
'If you need to connect another identity, use only an explicit account-linking flow offered by Settings.'
],'A completed flow should establish a Webcanbe session for the intended account. Provider authentication does not automatically move purchases between unrelated accounts.','Do not assume Google, GitHub and email identities merge merely because they display similar names or addresses. Linking may require reauthentication and server checks. If the product reports a conflict, contact Account Help rather than creating repeated alternate accounts.',['account/google','account/github','account/email']],
['account/google','Google sign-in','For Google sign-in, choose the Google account associated with your Webcanbe work and allow the flow to return to the site.','Use the Google option only when it is offered. If your browser already has several Google accounts open, account selection can differ from the identity you expected.',[
'Open Webcanbe Sign in and choose Google. Select the intended account in the provider prompt.',
'Complete any verification required by Google without sharing codes with anyone else.',
'Return to Webcanbe and inspect Settings to confirm the account context.',
'If the flow fails, note the visible error and whether it occurred before or after returning to Webcanbe, then retry from the normal sign-in entry.'
],'The intended account should be signed in and able to access its own purchases and projects. An empty account should prompt an identity check before a new purchase.','Blocked redirects, browser restrictions or provider policy can interrupt authentication. Do not paste the callback URL into support because it may contain sensitive flow data. Send Account Help the provider name, safe error text and approximate time instead.',['troubleshooting/login','account/identity','account/sessions']],
['account/github','GitHub sign-in','GitHub sign-in establishes an account session through the supported provider flow. It does not by itself import repositories or authorize every repository operation.','Use the GitHub option if it is currently offered and confirm which GitHub account is active in your browser. Keep repository access assumptions separate from account authentication.',[
'Choose GitHub on the Webcanbe sign-in screen and review the provider’s request.',
'Complete verification with the intended account, then return to Webcanbe.',
'Confirm the account in Settings and inspect its projects or purchases.',
'If authorization is denied or the return fails, record the visible stage and error, then use Account Help if a clean retry does not resolve it.'
],'You should obtain a Webcanbe session for the expected identity. Private project access should follow that account’s entitlements and workspace state.','Do not assume sign-in creates repository synchronization, imports code or grants a public integration API. Never provide a personal access token to support as a substitute for authentication. Provider restrictions and browser state can affect the flow independently of Webcanbe project compatibility.',['account/providers','integrations','troubleshooting/login']],
['account/email','Email and password sign-in','The current email sign-in flow asks for your email address and then your password. Enter credentials only in the authentication screen, never in a support form.','Use the address associated with your email/password account. If you originally signed in with Google or GitHub, use that provider unless you have completed a supported identity-linking process.',[
'Open Sign in, enter your email address and choose Continue. Check the address before moving to the password step.',
'Enter your password in the password field and choose Continue. For a new email account, use the account-creation flow rather than assuming sign-in creates one.',
'Wait for authentication to complete and inspect Settings to confirm the resulting account. Check Purchases and Projects under that identity.',
'If the password is rejected or access fails, preserve the safe error message and contact Account Help for the supported recovery path.'
],'A successful email/password flow should create the intended Webcanbe session. You should not need to email your password, a session token or a verification credential to anyone.','Do not assume that matching email text silently merges provider accounts. Avoid repeated account creation when a purchase is missing. Password handling belongs to the authentication provider; support should never ask for your plaintext password. Browser restrictions or an unavailable authentication service can also interrupt the session exchange.',['account/identity','account/providers','troubleshooting/login']],
['account/sessions','Manage account sessions','Account sessions allow access to private Webcanbe surfaces after sign-in. Use the account controls offered in Settings and sign out when working on a shared device.','Save important drafts before ending a session. Signing out changes access in the browser; it does not export source or reverse a purchase.',[
'Inspect the account and session controls available in Settings. Confirm the identity before changing session state.',
'Use Sign out when leaving a shared or untrusted device.',
'If you suspect an unwanted session, use the supported session-revocation control when available and secure the underlying provider account.',
'Sign in again through the normal entry point and verify your projects and purchases under the expected identity.'
],'Private pages should require an authorized session after sign-out or revocation takes effect. Your source and entitlements should remain associated with the account.','Never copy session cookies or tokens between browsers to recover access. If you suspect compromise, report it privately through Security Report without including live credentials. A browser storage problem can affect drafts separately from server-side account data.',['security','security/disclosure','history/recovery']],
['account/profile','Account profile information','Use Settings to inspect and update profile information that the product allows you to change. Keep presentation details separate from authentication identity and purchase ownership.','Confirm that you are in the intended account. A display name can be editable while provider identity, verified email and account identifiers follow different rules.',[
'Open Settings and review the displayed profile fields.',
'Change only fields offered by the current form and save through its normal action.',
'Reload or revisit Settings to confirm the accepted values.',
'For an identity, verification or account-linking issue, use Account Help rather than trying to encode a request in a display-name field.'
],'Accepted profile changes should appear in the account UI. They should not be interpreted as transferring projects or changing the legal party associated with past transactions.','Do not put passwords, API keys or sensitive personal records in profile fields. Some values come from a provider or require a separate verification flow. If a change is unavailable, support can explain the appropriate process without requiring you to share authentication credentials.',['account/identity','account/providers','security/privacy']],
['account/workspaces','Account access and workspaces','Private working projects are accessed through an authenticated account. Keep account identity, plan capacity and the project’s source revision distinct when diagnosing workspace access.','Sign in with the account that created the working copy or holds the required access. A public listing URL does not authorize entry to a private project.',[
'Confirm the account in Settings, then open Projects from account navigation.',
'Choose the intended working copy and inspect its source/preview status.',
'If access is denied, check whether the account, entitlement or creation operation differs from what you expected.',
'Contact Account Help for identity issues or General Support for a project access error, including safe account/project references when available.'
],'The workspace should open only within the supported account context. Its accepted source and history should remain separate from marketplace publication state.','Do not assume team invitations, shared editing or account transfers exist unless the live product offers them. Sharing passwords is not a collaboration workflow. A plan-capacity message affects allowed operations but should not be confused with an authentication failure.',['working-copies/open','working-copies/capacity','purchases/entitlements']],
])
