import { family } from '../doc-types'
export default family('AI editing', [
['ai-editing','AI editing','AI editing proposes changes to the working project’s source. Review the proposal and its diff before applying it; generation and source acceptance are separate steps.','Open an editable project, check your available AI Actions and resolve important unsaved drafts. The proposal is based on a source revision, so intervening saves can make it stale.',[
'Open AI and choose the available intent: edit source or explain source. Describe a bounded task and identify relevant files or behavior.',
'Choose Standard or Deep using the cost shown in the panel. Generate and wait for a proposal or a clear failure state.',
'Review the changed files and diff. Check whether the proposal does more than you asked or removes useful code.',
'Apply only when the proposal still matches the current revision. Inspect History and the preview after acceptance.'
],'An applied edit should become a source revision. An explanation should not silently mutate files. Export includes accepted changes, not an unaccepted proposal.','AI output can be incorrect and still look plausible. Review behavior, licenses and security-sensitive changes yourself. Failed generations, stale revisions and settlement states have distinct meanings; do not repeatedly generate or apply without reading the status.',['ai-editing/modes','ai-editing/review-diffs','ai-editing/apply']],
['ai-editing/modes','Standard and Deep modes','Standard and Deep are AI generation modes with different displayed Action costs. Choose based on the task and the cost shown before generation, not an assumption that one mode guarantees correctness.','The current source panel labels Standard as 1 Action and Deep as 3 Actions. Live product configuration and the confirmation shown for your request remain the authority if those values change.',[
'Write a concrete request that states the desired source change and any constraints. Keep unrelated tasks in separate proposals.',
'Inspect the selected mode and displayed Action cost. Check that your account has enough available balance.',
'Generate once and wait for the request status. Read the proposal before deciding whether another generation is necessary.',
'If a proposal is unsuitable, refine the request with a specific correction rather than relying on mode selection alone.'
],'The request should use the mode and cost presented by the product. The resulting proposal should still require review before source application.','A successful proposal can consume Actions even if you choose not to apply it; application is a separate decision. Failure and reservation settlement are handled by request state. Deep does not promise a particular model, unlimited context or error-free results.',['ai-editing/actions','ai-editing/context','ai-editing/failures']],
['ai-editing/actions','AI Action costs and settlement','AI Actions account for generation work. A successful proposal and an accepted source edit are different events, so review the request status before interpreting a balance change.','Check the cost shown for the selected mode and your current available balance. Included plan allocations and purchased balances can have different rules; use the account’s live usage information.',[
'Before generating, confirm the displayed cost and selected intent. Avoid duplicate submissions while a request is pending.',
'After generation, inspect whether the request produced a proposal or failed validation/provider processing.',
'If source application succeeds but settlement is reported pending, preserve the request reference and reload the authoritative state before retrying.',
'Contact Billing Help about unexplained usage with the safe request reference, approximate time and visible status.'
],'The product should expose a request outcome that can be reconciled with usage. A generated proposal is not proof that its changes have been applied to source.','Do not assume that declining a valid proposal refunds its generation cost. Failed generations release reservations according to server processing, but temporary settlement states can require reconciliation. This guide does not promise fixed allowances, expiry rules or manual credits outside the live plan and billing policy.',['billing/ai-allowance','ai-editing/failures','ai-editing/apply']],
['ai-editing/context','Provide useful source context','Give AI a bounded source task with relevant context so the proposal can be evaluated against a clear goal. Avoid sending credentials or unrelated private data in the prompt.','Know the current component or files involved and save intended draft changes first. AI works from the allowed source context for a revision, not from every unsaved idea in your browser.',[
'State the visible problem and desired result. Name the relevant component or file when you know it.',
'Add constraints such as preserving routes, keeping a public API unchanged or limiting the edit to styling.',
'Describe how you will verify the result, including responsive states or existing behavior that should continue working.',
'Read the generated diff against those constraints before applying. Ask for a narrower revision if unrelated files changed.'
],'A good proposal should have an understandable relationship to your request and the available source. You should be able to reject or accept it based on concrete behavior.','Source context is bounded and may omit files or external systems. Do not assume the model inspected private services, production databases or runtime secrets. Never paste auth tokens, passwords, customer records or proprietary material unrelated to the task into an AI request.',['ai-editing/review-diffs','ai-editing/security','code-editor/saving']],
['ai-editing/review-diffs','Review AI diffs','Review every proposed file operation before applying AI edits. A plausible summary is not a substitute for checking the source changes and their scope.','Keep the original task visible and identify the current source revision. A proposal may update, create or delete files; each operation should be intentional.',[
'Read the proposal summary, then inspect each changed file. Look for deleted behavior, changed imports and unexpected new dependencies.',
'Check source changes against the requested scope. Pay special attention to authentication, payments, network requests and credential handling.',
'Consider shared components and responsive styles that could affect pages beyond the current preview.',
'If the diff is acceptable and current, apply it. Otherwise leave it unapplied and refine the request or edit the source yourself.'
],'You should understand what will change before the source transaction runs. After application, verify the actual preview and History rather than treating review as a runtime test.','Diff review cannot guarantee correctness. Generated code may compile while introducing logical or accessibility problems. Do not apply a stale proposal by bypassing revision protection; regenerate or reconstruct the intended edit against the latest source.',['ai-editing/apply','ai-editing/stale-revisions','ai-editing/security']],
['ai-editing/apply','Apply an AI proposal','Applying a proposal submits reviewed operations against the source revision used to generate them. Wait for a confirmed outcome before making another source change.','Save or resolve drafts and check that the proposal is still current. Review creates no source revision by itself; the apply action is the point where accepted changes can enter project history.',[
'Inspect the diff and the proposal status. Use Apply to source only when the product reports that application is available.',
'Wait for the operation to complete. Do not repeatedly click or close the tab while the result is uncertain.',
'Check History and the accepted source after success. Inspect the preview for the intended behavior and obvious regressions.',
'If the UI reports an unknown apply outcome or pending settlement, reload the authoritative project/request state before trying again.'
],'Accepted operations should form a source revision that can be inspected and exported. An explanation-only request should not apply file changes.','A stale revision rejection protects intervening work. An uncertain response is not proof that nothing happened; retrying without checking can duplicate intent. Generation costs and application state are separate, so a usage entry alone does not establish source acceptance.',['ai-editing/stale-revisions','history/ai-changes','ai-editing/actions']],
['ai-editing/stale-revisions','Resolve stale AI proposals','A proposal becomes stale when accepted source changes after the revision it was generated against. Revision protection prevents old operations from silently overwriting newer work.','Check whether you saved Code, applied a Visual edit, restored history or used another tab after generation. Preserve the proposal intent, but treat the latest accepted source as authoritative.',[
'Read the stale-revision message and open the latest source or History entry.',
'Compare the intervening changes with the proposal’s intended task. Decide which parts are still relevant.',
'Generate a new proposal against the current revision, or make a deliberate manual edit in Code.',
'Review the new diff and verify the accepted result after applying. Keep simultaneous editing operations limited while a proposal is under review.'
],'The eventual change should build on current source rather than restoring an older snapshot accidentally. A rejected stale proposal should not create a new accepted revision.','Do not alter revision IDs or replay old network requests to force application. Browser recovery text and unsaved drafts can add another layer of differences; resolve them before generating again. If the reported revision remains inconsistent after reload, report the request and project references without private source.',['history/conflicts','ai-editing/context','code-editor/drafts']],
['ai-editing/failures','Handle failed AI generations','When generation fails, use the reported request state to distinguish unavailable service, insufficient balance, validation failure and an uncertain network outcome.','Keep the request reference and visible error if provided. Avoid immediately submitting the same task several times, because a delayed response can be different from a request that never started.',[
'Check the AI panel status and available Actions. If the service is unavailable, wait for availability rather than changing unrelated source.',
'For a validation failure, narrow the task and inspect whether the requested files or operations fit the supported context.',
'For an uncertain network result, reload the request state before generating again.',
'If a reservation or usage state remains unresolved, contact Billing Help with the safe request reference and approximate time.'
],'A failed generation should not be mistaken for an applied source edit. Check History if you are uncertain whether a later apply operation completed.','Provider and validation failures release reservations through server processing; the visible account state can need reconciliation. Do not promise yourself a particular settlement time from a client error. Never include provider keys, prompts containing secrets or private source in a public bug report.',['ai-editing/actions','ai-editing/apply','security/support-data']],
['ai-editing/security','AI editing security boundaries','AI output is proposed source, not authority to bypass project, revision or account checks. Review generated changes with the same care as code from another contributor.','Keep credentials and sensitive personal data out of prompts and source files. Know which files are relevant to the task before asking for broad changes.',[
'Ask for a bounded change and inspect every proposed operation. Treat instructions embedded in project comments or content as project data, not trusted authority.',
'Check new network requests, dependencies and any code touching authentication or payment behavior.',
'Apply only through the supported review flow so current-revision and project checks remain in force.',
'If generated content appears to expose a secret or create a vulnerability, stop using that change and contact Security Report with a minimal description.'
],'Accepted AI work should remain traceable in source history and subject to the same export and compatibility rules as other edits. A model response should never count as proof that a sensitive operation is authorized.','AI can generate unsafe or incorrect code. Controlled runtime admission does not replace your production security review. Do not test suspected vulnerabilities against other users’ projects or send auth tokens as evidence; use responsible disclosure and a minimal safe reproduction.',['security','security/disclosure','ai-editing/review-diffs']],
])
