import { family } from '../doc-types'
export default family('Plans, billing & AI Actions', [
['billing/plans','Choose a plan','Compare plans using the current Plans page and your account’s actual subscription state. Project capacity, AI allowance and other limits come from live configuration rather than fixed numbers in this guide.','Decide which constraint matters for your work: active projects, AI usage or another explicitly offered capability. A subscription and a marketplace project purchase are separate acquisitions.',[
'Open Plans and inspect the current features, billing period, currency and availability.',
'Compare the plan against your expected working-project count and AI usage. Read limitations rather than only the plan name.',
'Use the available checkout action and review the provider’s final amount before confirming.',
'After returning, inspect account billing state and the feature allowance actually applied to your account.'
],'The account should reflect the confirmed subscription state before you rely on a higher limit. Existing marketplace entitlements should remain distinguishable from plan features.','Do not infer fixed prices, unlimited usage or guaranteed checkout availability from old screenshots. Tax, currency and billing terms belong to the actual checkout and applicable policy. If the displayed plan and available operations disagree, contact Billing Help with safe references.',['billing/checkout','billing/subscription-state','billing/ai-allowance']],
['billing/checkout','Plan and credit checkout','Checkout is the provider flow for an offered subscription or AI credit purchase. The return URL is not itself proof that the payment and account update are complete.','Confirm the account, selected product and displayed amount. Keep a non-sensitive order reference if the provider supplies one.',[
'Open the checkout action offered by Plans or the relevant account screen.',
'Review the billing period, currency and final terms at the provider before completing payment.',
'Return to Webcanbe and wait for the current account state. Inspect the relevant plan or balance rather than only a success-looking URL.',
'If state remains pending or inconsistent, contact Billing Help before submitting another payment for the same intent.'
],'A confirmed transaction should reconcile to the appropriate account entitlement or balance. A canceled or failed checkout should be shown distinctly.','Payment methods and checkout availability depend on live configuration. Do not manipulate callback parameters or replay provider requests to force account access. Never include card security codes, auth tokens or full payment callback URLs in a support request.',['billing/orders','billing/subscription-state','ai-editing/actions']],
['billing/subscription-state','Understand subscription state','Use the account’s reported subscription state to understand current plan access. Provider approval, webhook processing and the visible account view can represent different stages of a change.','Have the plan name, billing period and non-sensitive subscription/order reference available. Check that you are signed into the account used during checkout.',[
'Inspect the current plan and status in the account billing area.',
'After a recent checkout or change, refresh the account state once the product has had a chance to confirm it.',
'Compare the applied limits with the displayed plan. Record the exact message when an operation is blocked.',
'Contact Billing Help if the status remains inconsistent, including the relevant reference and approximate time.'
],'The plan display and allowed account operations should agree after confirmation. A pending state should not be advertised as fully active access.','This guide does not promise a specific processing interval, automatic grace period or permanent retention of paid limits. Cancellation, failure and renewal behavior depend on applicable terms and live state. Do not repeatedly purchase a plan to solve an identity or synchronization issue.',['billing/plans','billing/changes','account/identity']],
['billing/ai-allowance','AI allowances and balances','AI availability depends on the account’s usable Action balance and request limits. Included plan allocations and purchased credits can have different lifecycle rules.','Inspect the balance and selected mode cost before generating. Standard and Deep can consume different amounts, and a successful proposal can be chargeable even if you decide not to apply it.',[
'Open the AI panel or usage view and check the current available balance.',
'Read the cost shown for the selected request mode. Keep concurrent pending requests in mind when interpreting availability.',
'After generation, inspect request outcome and usage state together.',
'If the balance does not reconcile after an unresolved request, send Billing Help the safe request reference and visible status.'
],'You should be able to decide whether to start a request based on the amount displayed by the product. Generation settlement should remain separate from whether source application succeeded.','Do not assume all balances roll over indefinitely or share the same expiry rules. This guide does not invent allowances, refunds or credit-transfer rights. Failed or uncertain operations should be reconciled through server state rather than repeated client submissions.',['ai-editing/actions','ai-editing/failures','billing/credits']],
['billing/credits','Purchase AI credits','Purchase an AI credit pack only through the available account flow and review its current terms. A configured pack is not evidence that checkout is active in every environment.','Confirm the account that will use the credits and inspect the displayed quantity, price and any applicable conditions. Keep plan-included usage separate from a purchased balance.',[
'Open the available credit purchase action and select the pack shown by the live product.',
'Review the final checkout amount and currency before confirming payment.',
'Return to Webcanbe and inspect the account balance after confirmation.',
'If the balance is missing or pending, use Billing Help with the order reference rather than purchasing the same pack again immediately.'
],'A confirmed purchase should appear in the appropriate usable balance according to its terms. The account identity should match the one used at checkout.','Credit quantity, availability and conditions can change with configuration. Do not infer unlimited use, refund eligibility, transferability or perpetual validity from the word credits. Never send payment credentials or provider access tokens to demonstrate a purchase.',['billing/ai-allowance','billing/checkout','billing/orders']],
['billing/changes','Change or cancel a plan','Use the subscription-management actions actually offered by the account UI. Review their effect before confirming a plan change or cancellation.','Check current billing state, project capacity and AI usage. Save and export important source as appropriate before making any change that could affect available account operations.',[
'Open the account billing or subscription area and inspect the available management actions.',
'Read the displayed effective date and any changes to limits, renewal or charges before confirming.',
'Complete the supported provider or account flow and return to Webcanbe.',
'Check the resulting subscription state. Contact Billing Help if the action is unavailable or the account does not reflect the confirmed result.'
],'The account should clearly identify the resulting plan state and the limits currently in effect. A request to cancel should not be confused with a completed refund.','Do not assume prorated credits, immediate downgrades, a grace period or automatic deletion behavior unless explicitly stated by the applicable terms and UI. This guide does not create those policies. Preserve references and ask Billing Help when the effect is unclear before taking the action.',['billing/subscription-state','billing/plans','export']],
['billing/orders','Report a billing discrepancy','Give Billing Help a specific transaction reference and the state you expected. Separate a marketplace purchase, subscription and AI usage request so the right record can be investigated.','Collect only safe context: order/subscription/request reference, approximate time, amount/currency if relevant and the visible error. Redact credentials and unrelated personal details.',[
'Confirm the signed-in account and identify which product or operation the question concerns.',
'Compare the provider’s result with the Webcanbe purchase, plan or usage state.',
'Open Billing Help and describe the discrepancy in one clear sequence, including any retry you already made.',
'Keep the response and transaction reference for follow-up. Avoid paying again while a duplicate-charge concern is unresolved.'
],'Support should be able to locate the relevant record without receiving payment secrets. A clear distinction between pending, failed and confirmed states makes investigation faster.','A support submission is not confirmation of a refund, credit or entitlement change. Never include full card details, security codes, passwords or callback tokens. Use Account Help instead when the underlying problem is that you cannot access the original identity.',['purchases/missing','ai-editing/actions','security/support-data']],
['billing/limits','When a plan limit blocks an action','A limit message should identify the operation your current account cannot perform. Distinguish active-project capacity, AI balance and concurrent-request limits before choosing a remedy.','Read the exact message and check live Plans/account information. A generic upgrade assumption can miss a pending request or account mismatch.',[
'Identify the blocked action and whether it concerns projects, AI usage or another offered feature.',
'Check the current account and plan state. For AI, inspect pending requests and usable balance.',
'Finish or reconcile pending operations before retrying. Review plan options only when the confirmed limit requires it.',
'Contact Billing Help if the enforced limit disagrees with the displayed entitlement, including a safe reference and error message.'
],'The next step should address the actual constraint rather than repeatedly performing the same rejected operation. A failed capacity check should not be reported as completed work.','Do not create alternate accounts or manipulate API requests to bypass limits. Limits and allowances can change with live configuration and subscription state. This guide does not guarantee a fixed number of projects, unlimited concurrency or special exceptions outside the applicable plan.',['working-copies/capacity','billing/ai-allowance','billing/subscription-state']],
])
