import { family } from '../doc-types'
export default family('Code editor & Split view', [
['code-editor','Code editor','Code mode edits the actual files in your working copy. Save a draft to make it part of the accepted source used by preview, history and export.','Open an editable project and identify the relevant file. Keep the distinction between the current editor draft and the latest accepted revision visible while you work.',[
'Switch to Code and select a file from the project tree. Read nearby definitions and imports before changing a component.',
'Make one coherent edit. Keep unrelated formatting or dependency changes separate so the resulting revision is easy to inspect.',
'Save the draft and wait for acceptance. If validation or revision checks fail, read the message before retrying.',
'Inspect the preview and History, then export if you need to verify the portable source result.'
],'The saved file should become part of the accepted project revision. Visual and Split should operate against that same source rather than a generated alternative.','A visible draft is not a completed save. Browser recovery can preserve unsaved text without making it authoritative. Code mode does not bypass compatibility or security admission, and changing package files does not authorize arbitrary installs or lifecycle scripts.',['code-editor/files','code-editor/saving','split-view']],
['code-editor/files','Navigate project files','Use the source tree to understand a project before editing it. File names, imports and component definitions provide more reliable context than a preview screenshot alone.','Open Code or Split in a working copy. Identify the entry files and styles from the source actually included in the release rather than assuming a particular folder convention.',[
'Locate the page or component associated with the visible interface. Follow imports to shared components and style files.',
'Inspect the file extension and neighboring definitions. JSX/TSX, CSS and configuration files have different roles.',
'Before changing a shared file, check which components import it. Keep the edit scoped to the intended behavior.',
'Save and inspect the accepted change, then check the relevant preview states. Preserve license and attribution files during cleanup.'
],'You should know which file owns the intended change and whether that file is shared. A saved source edit should explain the preview result without relying on a hidden visual layer.','Not every file is executable in the controlled preview. Configuration, server code and package scripts can remain source artifacts without being run by Webcanbe. Do not remove unfamiliar files simply because the current preview does not visibly use them.',['code-editor','code-editor/styles','compatibility/dependencies']],
['code-editor/saving','Save code changes','Saving submits a Code draft against the current project revision. Only an accepted save becomes the source used by history and export.','Check whether another operation or tab has changed the project since you began editing. Keep a recoverable copy of important draft text before resolving a conflict, without exposing secrets in support messages.',[
'Finish a small coherent edit and use the workspace Save action. Wait for its completion state.',
'If the save succeeds, inspect the refreshed preview and new History entry. Confirm that the file contains the intended accepted text.',
'If the save is rejected, read whether the issue is syntax, validation, connectivity or a stale revision.',
'For a revision conflict, inspect the latest accepted source and reapply the intended difference deliberately rather than repeatedly resubmitting the old draft.'
],'An accepted save should survive reopening the project. The preview may take time to catch up, but a completed revision provides a concrete source reference.','Unsaved drafts are excluded from export and are not equivalent to server history. Recovery text can help after interruption, but it must be reviewed and saved again. Do not assume that leaving the editor or switching views automatically commits every draft.',['history/drafts','history/conflicts','export/accepted-source']],
['split-view','Split view','Split keeps source and preview visible together so you can connect a file edit with its rendered result. It uses the same working revision as Visual and Code.','Open a working copy and ensure the preview state is understood. A narrow browser window may constrain the useful preview width; choose the workspace arrangement that lets you inspect the task clearly.',[
'Switch to Split and open the relevant source file. Use the preview to identify the area you intend to change.',
'Edit the source or use a supported visual control. Keep track of unsaved Code drafts before applying another operation.',
'Save and wait for the accepted revision. Inspect both the file and the refreshed preview rather than judging only one pane.',
'Check another viewport when the change affects layout. Use full Code or Visual temporarily when more space is needed.'
],'The two panes should agree after a successful save and preview update. Switching modes should preserve the distinction between draft text and accepted source.','Split does not make unsupported elements visually editable or guarantee instant preview transport. If source is saved but the preview is stale, inspect connection state instead of duplicating the mutation. A shared component edit can affect more than the selected visible instance.',['working-copies/modes','code-editor/saving','working-copies/preview']],
['code-editor/styles','Edit CSS and layout in Code','Use Code for style rules that need broader context than the visual inspector can safely expose. Inspect selectors, shared classes and responsive conditions together.','Identify the style file or inline definition actually controlling the element. CSS Modules, utility classes and ordinary CSS can coexist; avoid assuming the nearest visible class is the only source of a value.',[
'Follow the component’s style imports and inspect the relevant selector or class expression. Check parent layout rules for flex and grid behavior.',
'Make a focused declaration change and preserve existing responsive conditions unless the task requires changing them.',
'Save the source and check the affected component at narrow and wide widths. Inspect shared instances and hover/focus states.',
'If the result is overridden, inspect the cascade and source origins before increasing specificity or adding duplicate rules.'
],'The accepted source should contain an understandable rule that produces the intended layout. The same rule should remain meaningful after export.','The controlled runtime may not support every preprocessor, plugin or dynamic styling system. Editing configuration does not cause uploaded tooling to execute automatically. When Visual cannot resolve a declaration, Code remains useful, but you must verify its effect in the supported preview or your own local environment.',['visual-editor/style-origins','visual-editor/responsive','compatibility/styling']],
['code-editor/drafts','Work safely with drafts','A Code draft is text you are editing before it has been accepted as a source revision. Treat draft recovery as assistance, not as proof that a save completed.','Before changing views, applying AI edits or closing the tab, check the editor’s unsaved state. Multiple drafts can make it harder to understand which source version a preview represents.',[
'Keep each draft focused on a single task. Save when the file is ready to become the next accepted source state.',
'If the browser offers recovery after interruption, compare the recovered text with the current accepted file.',
'Resolve differences deliberately and save again. Do not overwrite a newer accepted revision just because recovered text is available.',
'Export only after the intended drafts have been accepted and the project state has been checked.'
],'You should be able to distinguish the draft in the editor from the revision in History. Once saved, the intended content should survive reopening and appear in export.','Draft storage can depend on browser state and is not an independent backup guarantee. Clearing site data, using another device or working in private browsing can affect recovery. Preserve important work through accepted saves and source exports rather than relying exclusively on an open tab.',['code-editor/saving','history/recovery','ai-editing/stale-revisions']],
['code-editor/errors','Resolve source errors','When a code change fails, identify whether the error is in source validation, preview compilation or the save operation itself. These states require different fixes.','Keep the visible error message and the file you changed available. Avoid editing several unrelated files while trying to locate the first failure.',[
'Check whether the save was accepted. If not, read the validation or revision message and preserve the draft before changing it.',
'For a syntax problem, inspect brackets, imports and the changed expression in its surrounding component.',
'For a preview failure after an accepted save, inspect the runtime message and dependency compatibility. The source may be saved even though it cannot render.',
'Fix the smallest identified problem, save and recheck. If you need to return to an earlier source state, use History deliberately.'
],'The accepted source should be valid for the intended workflow, and the preview should either render or explain a separate compatibility limitation. A cleared editor warning alone is not full runtime verification.','Do not install arbitrary dependencies or enable uploaded scripts just to silence a preview error. Keep credentials out of diagnostic logs. If the error remains unclear, send Report an Issue the file name, operation and safe error text without private source by default.',['history/undo-redo','compatibility/dependencies','troubleshooting/preview']],
['code-editor/shortcuts','Workspace keyboard shortcuts','Keyboard shortcuts provide quick access to workspace views and source actions. Their effect depends on focus, so text inputs and the code editor may handle keys differently from the workspace chrome.','Open the workspace shortcut help when available and use the bindings shown by the current product. On macOS, Command is used where other platforms commonly use Control.',[
'Use Shift+V, Shift+C or Shift+S from the workspace context to choose Visual, Code or Split. Shift+H opens History.',
'Use the workspace Undo and Redo actions or their displayed keyboard equivalents. Confirm whether focus is in a text editor before interpreting the result.',
'Use the displayed export shortcut, Shift+Command/Control+E, when the intended source has been saved.',
'If a shortcut does not fire, leave a text input and try the visible control. Check the browser or operating system for a conflicting binding.'
],'The selected workspace view or action should match the visible control. A shortcut does not relax save, revision, compatibility or entitlement checks.','Do not rely on shortcuts alone for an irreversible decision or when focus is ambiguous. Undo inside a draft and a project-level history operation can affect different states. Accessible visible controls remain the reliable fallback when a browser intercepts a key combination.',['working-copies/modes','history/undo-redo','export']],
])
