import { family } from '../doc-types'
export default family('Compatibility & runtime', [
['compatibility','React & Vite compatibility','Webcanbe currently focuses on admitted React/Vite projects. Runtime rendering, visual editability, source export and hosted readiness are separate capabilities, so inspect the project’s report instead of assuming universal support.','Know the release’s framework, dependencies and style conventions. JSX/TSX, ordinary CSS, CSS Modules, inline styles, Flex, Grid and supported Tailwind patterns are relevant to the current source-editing workflow.',[
'Read the listing and release compatibility information before acquisition.',
'After creating a working copy, inspect admission and preview status. Separate an unsupported runtime from a specific read-only visual target.',
'Use Code for source that is editable but not safely exposed through Visual. Verify the result with the supported preview path.',
'Export and use your own development environment when the project requires tooling or services outside the controlled runtime.'
],'You should understand which operations are supported for the actual source version. A partial report can still support a useful Code/export workflow.','Compatibility is not a promise that every React package, Vite configuration, server framework or lifecycle script will execute. Uploaded configuration and arbitrary installs are not trusted instructions. A working preview also does not certify production security or deployment readiness.',['compatibility/runtime','compatibility/visual-support','compatibility/admission']],
['compatibility/runtime','Understand the controlled runtime','The runtime renders admitted source through a controlled preview path. It does not simply run every command or configuration file uploaded with a project.','Inspect the project’s runtime compatibility separately from its visual capabilities. A source package can contain files that remain useful after export without being executed in the hosted preview.',[
'Open the workspace and read the runtime status or compatibility report.',
'Connect the available preview and wait for a ready or failed state. Keep source save status separate from runtime connection status.',
'If rendering fails, identify whether the report points to dependencies, unsupported configuration or missing external services.',
'Use the documented local export workflow for requirements outside the supported runtime, reviewing scripts before running them yourself.'
],'A ready preview should render the admitted source under the supported environment. Unsupported behavior should be explained rather than silently replaced with invented functionality.','Do not expect arbitrary backend processes, uploaded build plugins or package lifecycle hooks to run inside the editor. The controlled runtime is a safety and compatibility boundary, not a general-purpose server hosting product. External API access still requires appropriate configuration and permissions.',['compatibility/dependencies','working-copies/preview','export/local-setup']],
['compatibility/visual-support','Understand partial visual support','Visual compatibility is assessed at the source-pattern and target level. A page can render successfully while some elements remain read-only or require Code.','Select an element and inspect the capabilities shown by the workspace. Dynamic expressions, inherited styles and shared source definitions can make a visually obvious change ambiguous in source.',[
'Check that the preview is connected and selection works before diagnosing a particular target.',
'Inspect the selected target’s supported text and style operations. Use only the controls that the product makes available.',
'For a read-only or unresolved value, open the corresponding source in Code and make a deliberate edit.',
'Save and verify the result. Keep the source structure meaningful rather than simplifying application logic solely to enable an inspector control.'
],'The project remains a source code project even where Visual exposes fewer controls. Accepted Code edits should still appear in History and export.','Runtime support, source ownership and visual editability are not interchangeable. Repeated attempts cannot make an unsafe target safe. If the reported capability seems inconsistent with a simple source pattern, send a minimal reproduction and safe project context through Report an Issue.',['visual-editor/unsupported','visual-editor/shared-source','troubleshooting/visual-target']],
['compatibility/styling','Supported styling patterns','Styling support depends on how declarations are represented in source. Webcanbe targets common CSS, CSS Modules, inline styles and supported utility-class patterns without promising every dynamic styling system.','Identify whether the relevant value comes from a local declaration, shared class, responsive rule or runtime expression. The rendered style alone does not establish an editable source location.',[
'Inspect style origins for the selected element. Check the active authoring breakpoint and any inherited or overridden values.',
'Use Visual for a declaration the inspector supports. Keep the change scoped to the intended source definition.',
'Use Code for complex selectors, dynamic class construction or unsupported generated styling.',
'Check the result at relevant widths and interaction states, then inspect the accepted source change.'
],'A supported style edit should remain an ordinary source declaration that makes sense after export. A read-only origin should direct you toward explicit source work.','A framework name in the package manifest does not guarantee that its custom plugins or configuration execute in the controlled runtime. Avoid adding preview-only overrides that conceal the underlying source issue. Review shared component scope before changing a common class or token.',['visual-editor/style-origins','visual-editor/responsive','code-editor/styles']],
['compatibility/dependencies','Dependencies and project tooling','Project dependencies and scripts are source information that must be evaluated against the supported runtime. Webcanbe does not grant uploaded package configuration authority to execute arbitrary code in the editor process.','Read the package manifest and compatibility report. Distinguish a package used by browser source from build tooling, a server dependency or a lifecycle script.',[
'Identify the dependency involved in a preview error and check whether it fits the supported runtime profile.',
'Inspect imports and source usage before changing versions or removing packages.',
'Use Code for deliberate source changes, then save and check the runtime result.',
'If the project needs unsupported tooling, export it and follow a reviewed local setup in your own trusted environment.'
],'Supported dependencies should resolve through the controlled workflow. Unsupported requirements should remain explicit rather than causing arbitrary installs or script execution.','Editing package.json is not permission for the platform to run install hooks or uploaded Vite plugins. Do not paste private registry credentials into source to bypass a failure. A local build can require additional setup even when the Webcanbe preview renders a supported subset.',['compatibility/runtime','compatibility/admission','export/local-setup']],
['compatibility/preview-modes','Interactive and snapshot previews','Preview modes differ in what they can demonstrate. An interactive runtime can exercise supported behavior, while a snapshot is primarily a rendered inspection surface.','Read the workspace’s preview status and available controls. A screenshot-like result should not be presented as proof that forms, navigation or external services are live.',[
'Connect the available preview and identify whether it supports interaction or source selection only.',
'Use selection mode to inspect supported elements. Switch to interaction mode only when the runtime offers it.',
'Check responsive layout with viewport controls, keeping those controls separate from source authoring breakpoints.',
'For behavior that the preview cannot exercise, inspect the source and test in an appropriate local environment after export.'
],'You should know whether you are evaluating appearance, source mapping or live interaction. Each is useful, but none should silently stand in for the others.','Snapshots may not respond to clicks, and runtime previews may still lack external credentials or services. A preview connection error is separate from a save failure. Report the mode and visible connection state when asking for help so support can reproduce the right path.',['working-copies/preview','marketplace/previews','troubleshooting/preview']],
['compatibility/admission','Project admission and safety','Admission checks determine whether a source package can enter the supported workflow. They are separate from marketplace licensing and from whether every element is visually editable.','Use a project you are authorized to upload or publish. Inspect package contents for secrets and understand its dependencies before submitting it to any hosted workflow.',[
'Read the admission result and its specific reason when a package is rejected or limited.',
'Correct the source or packaging issue described by the report rather than trying to bypass the check through renamed files.',
'Keep unsupported scripts and configuration as source artifacts only where the product permits them; do not assume they will execute.',
'Resubmit through the supported flow and review the resulting compatibility state before claiming the project is ready.'
],'An admitted project should have an explicit supported path for source handling and preview. Admission should not be confused with legal approval of all assets or a production security certification.','Uploaded lifecycle hooks, arbitrary installs and project configuration are not trusted editor instructions. A successful admission cannot establish ownership of third-party code. If a rejection seems wrong, provide the safe report and a minimal non-sensitive reproduction to support.',['security/runtime-isolation','creators/submissions','compatibility']],
['integrations','API and integrations overview','Webcanbe projects can contain integration code, but a project interface does not provision the external services it references. This overview separates project integrations from Webcanbe’s own internal service endpoints.','Inspect the acquired release’s setup instructions and source. Identify which services are required and whether configuration belongs in browser code or on a trusted server.',[
'List external APIs, authentication, storage and payment services used by the project.',
'Configure your own authorized accounts in a suitable development or deployment environment. Keep server secrets outside public source.',
'Test the integration with safe non-production data and verify error states as well as successful responses.',
'Contact Seller Support when a release does not explain required configuration. Use General Support for questions about Webcanbe’s supported public integration surface.'
],'The project should have explicit service requirements and a clear boundary between editable source and external infrastructure. Export lets you continue integration work in your own environment.','Internal Webcanbe endpoints used by the product are not a documented public automation API. Do not build against guessed private routes or share account tokens to automate them. This page does not promise API keys, webhooks or repository synchronization that the public product does not offer.',['export/environment','security/secrets','compatibility/runtime']],
])
