import { family } from '../doc-types'
export default family('Creators, listings & releases', [
['creators','Creator documentation','Creators publish versioned source projects through a submission and release workflow. Prepare a useful, rights-cleared project whose description matches what buyers actually receive.','Sign in and inspect Creator Studio’s current access and submission state. Seller access, review readiness and payment availability are separate from having a normal buyer account.',[
'Prepare the source and its setup instructions. Remove secrets and verify rights to bundled code, images, fonts and other assets.',
'Create a submission in Creator Studio and complete the requested metadata, category, compatibility and licensing information.',
'Review validation and review feedback. Publish only through the action made available for an approved release.',
'Maintain the listing and publish new releases when source changes, keeping buyer-facing descriptions accurate.'
],'A published listing should identify a specific source release and explain its intended use and limitations. Buyers should be able to distinguish your project’s interface from services they must configure themselves.','Submission is not automatic approval or a payout guarantee. Do not publish credentials, unlicensed assets or misleading claims about compatibility. Fees, payout eligibility and distribution rights belong to the applicable creator agreement and live account configuration.',['creators/studio','creators/submissions','creators/licensing']],
['creators/studio','Creator Studio','Creator Studio is the account area for managing project submissions, listings and releases. Use its reported state to understand the next available action.','Sign in with the creator account. Keep listing, submission and release identifiers available when discussing a specific item with Seller Support.',[
'Open Creator Studio from your account navigation. Review existing submissions and listings before creating another item for the same project.',
'Open a submission to inspect its metadata, source and review status. Address concrete validation messages before resubmitting.',
'Use the available release or publication action when the workflow permits it.',
'After publishing, inspect the public listing in a separate public view and confirm that its description matches the released source.'
],'Studio should provide a traceable path from submission to an identifiable published release. The public listing should not expose private account details or unpublished source.','Controls can be unavailable while access, review or payment setup is incomplete. Do not interpret a saved draft as a public listing. If state appears inconsistent, contact Seller Support with safe identifiers and the visible status instead of creating duplicate submissions.',['creators/submissions','creators/review','creators/listing-updates']],
['creators/submissions','Create a project submission','A submission packages source and listing information for validation and review. Prepare it as a reproducible source project rather than a set of attractive screenshots.','Confirm that you have distribution rights and remove credentials or private data. Read the current compatibility guidance and include enough setup information for a buyer to understand external requirements.',[
'Open the new-submission flow in Creator Studio and supply the requested project source through its supported input.',
'Write an accurate title and description, choose a useful category and identify the project’s stack.',
'Provide licensing, release and compatibility information requested by the form. Explain services or assets the buyer must supply.',
'Submit for the available checks and review the result. Correct specific errors before sending another version.'
],'The submission should identify the source being reviewed and contain enough public metadata to support a truthful listing. A successful upload alone should not be described as publication.','Do not include secrets, customer data or assets with unclear resale rights. Uploaded configuration and scripts are not executed merely because they are included. If the submission is rejected, preserve its reference and address the stated cause rather than bypassing admission checks.',['creators/review','compatibility/admission','creators/licensing']],
['creators/review','Understand the review process','Review checks whether a submission is ready for the available marketplace publication workflow. Treat review feedback as actionable state rather than assuming a saved submission is approved.','Keep the submitted source version stable while evaluating feedback. Changing unrelated files can make it harder to confirm that a reported issue was resolved.',[
'Open the submission and read its current validation and review status.',
'For source or compatibility findings, reproduce the issue against the submitted version and make a focused correction.',
'For metadata or rights questions, provide accurate information and supporting references through the appropriate private channel.',
'Resubmit through the offered workflow and wait for a new result before attempting publication.'
],'An approved path should make the relevant publication action available and identify the source release to be published. Rejected or incomplete submissions should remain distinguishable from public listings.','This documentation does not promise a review deadline, guaranteed acceptance or a certification of all legal/security properties. Do not advertise approval that has not occurred. Use Seller Support with the submission ID when a status is unclear or appears stuck.',['creators/submissions','creators/rules','creators/releases']],
['creators/releases','Create and publish releases','A release identifies a version of the source you distribute. Publish a new release when source changes instead of implying that existing buyers’ working copies have been rewritten.','Review the source, setup instructions and applicable rights for the exact version being released. Keep changes understandable enough to describe to buyers.',[
'Prepare the updated source through the supported submission/release flow and address validation or review requirements.',
'Write release notes that identify meaningful changes, compatibility effects and any setup or migration work.',
'Use the offered publication action only for the intended release. Confirm the listing points to the expected public version.',
'Inspect the public detail page and preview after publication. Keep the release identifier for support and future updates.'
],'The listing should refer to an identifiable published source snapshot. Buyer working copies remain separate projects with their own revisions.','Do not promise automatic merging of buyer edits or access to all future versions unless the applicable terms and product explicitly provide it. A release can be immutable while external services still change. Avoid describing dependency or backend readiness that you have not verified.',['creators/immutable-releases','marketplace/releases','creators/listing-updates']],
['creators/immutable-releases','Immutable releases','An immutable release is a fixed source snapshot. It gives buyers and support a stable reference while allowing the creator to publish later versions separately.','Distinguish release source from mutable listing description and from a buyer’s working copy. These objects have different purposes and should not share ambiguous version language.',[
'Before publication, verify the source version and associated metadata you intend to release.',
'When source changes later, create a new release through the supported process rather than describing the old snapshot as updated.',
'Reference exact release versions in support replies and change notes.',
'Explain whether a change concerns the original release, a later release or a buyer’s own customization.'
],'A buyer should be able to identify what source their working copy began with. The creator should be able to reproduce an issue against the same published version.','Immutability applies to the released source snapshot, not to every external API, remote asset or dependency service it references. It also does not grant legal rights that were absent from the submission. Correct listing descriptions promptly when they misrepresent a fixed release.',['releases-introduction','creators/releases','working-copies/source-release']],
['creators/rules','Marketplace rules for creators','Publish projects whose source, rights and descriptions can be understood by buyers. Marketplace presentation should accurately distinguish included functionality from integrations the buyer must configure.','Review the Creator Distribution Agreement, Acceptable Use and licensing guidance before submitting. Prepare source that does not contain secrets, personal data or misleading third-party branding.',[
'Check ownership or distribution permission for code, fonts, images and other bundled assets.',
'Describe supported behavior and compatibility honestly. Label requirements in normal useful prose, including any external services or setup.',
'Use previews that represent the released source. Do not fabricate customer reviews, performance results or certifications.',
'Keep listing information current and respond to release-specific issues through the supported seller channels.'
],'Buyers should have a clear basis for deciding whether a project fits their task. Reviewers should be able to connect public claims to the actual submitted release.','A category or review result does not authorize prohibited content or unlicensed distribution. Do not use hidden content, misleading metadata or unsupported guarantees to attract discovery traffic. Questions about a specific submission should include its identifier in Seller Support.',['creators/licensing','creators/review','security/support-data']],
['creators/fees-payouts','Fees and payouts','Creator earnings depend on the applicable fee arrangement, payment processing and payout eligibility. Read the current creator terms and account information before relying on a net amount or payout date.','Keep platform fees separate from processor, currency-conversion, payout and tax costs. A zero platform-fee program does not make every part of a transaction free.',[
'Confirm the fee arrangement that applies to your creator account and release before setting pricing.',
'Review transaction and available-balance information. Sales can remain on hold before becoming eligible for payout.',
'Complete the payout information requested through the supported private process. Provide only the details necessary for that process.',
'For discrepancies or delayed availability, contact Seller Support with sale/payout references and the visible balance state.'
],'You should understand the difference between a sale, an available balance and a completed payout. A payout is complete only when the supported process records its actual result.','The current operating approach includes a sale hold and scheduled payout review, but this guide does not guarantee a date or override the creator agreement. Refunds, reversals and disputes can adjust balances after a sale. Founding Creator terms apply only where confirmed for the account; do not infer eligibility from general marketing.',['creators/pricing','creators/licensing','billing/orders']],
['creators/pricing','Set project pricing','Set a project price using the constraints and currency shown in Creator Studio. Consider the release’s scope and your applicable fees rather than copying a price from another listing.','Check whether the current configuration allows free listings and what minimum paid price applies. Those values come from live product configuration and can differ from old screenshots.',[
'Prepare an accurate release description so buyers understand the value and required external setup.',
'Enter pricing through the supported listing/submission controls and inspect validation messages.',
'Review the buyer-facing amount and currency before publication. Keep platform fees and other transaction costs separate in your own calculations.',
'After publication, inspect the public detail page and use Seller Support if the displayed terms do not match the intended configuration.'
],'The published listing should show the approved acquisition terms for its release. A pricing change should not be represented as rewriting completed orders or their original terms.','Do not promise tax treatment, payout timing or net proceeds from the list price alone. Founding Creator or other special fee arrangements require confirmed eligibility. If checkout is unavailable, a configured price is not proof that buyers can complete a live transaction.',['creators/fees-payouts','marketplace/free-and-paid','billing/checkout']],
['creators/licensing','Creator licensing guide','Only distribute source and assets you have the right to include. Make the release’s buyer permissions clear without claiming rights over third-party material you do not own.','Inventory original code, dependencies, fonts, images, icons and copied content. Open-source availability is not the same as unrestricted resale permission for every asset in a project.',[
'Review each component’s license and retain required notices. Replace material whose distribution rights cannot be established.',
'Select or describe the buyer license through the supported submission process, consistent with the creator agreement.',
'Explain separate asset requirements in the listing and source instructions when buyers must obtain their own rights.',
'Before publishing a new release, repeat the rights review for added dependencies or media.'
],'A buyer should be able to understand the permission attached to the released source and identify separate third-party obligations. Keep a record of the rights supporting your distribution.','This guide does not provide a universal license template or legal determination for your project. Do not strip notices or assume an AI-generated asset is automatically unrestricted. Ask Seller Support about marketplace policy questions and seek appropriate advice for unresolved rights issues.',['marketplace/licenses','export/ownership','creators/rules']],
['creators/listing-updates','Update listing information','Keep a listing’s public description aligned with its published release. Metadata corrections and source releases are different operations and should be communicated clearly.','Identify whether the problem is a title, description, category, price or the actual source. A description edit cannot repair a defect in a fixed source snapshot.',[
'Open the listing in Creator Studio and inspect the fields the current workflow allows you to update.',
'Correct inaccurate claims or missing setup information with precise language. Avoid describing unreleased work as already included.',
'For source changes, prepare a new release and follow its review/publication process.',
'Inspect the public listing after the update and verify that its release reference, preview and acquisition information remain coherent.'
],'The public page should tell buyers what the currently offered release actually contains. Release notes should explain source changes separately from editorial corrections.','Do not imply that updating a listing modifies existing buyer working copies or prior purchase terms. Changes may require review or be constrained by publication state. If the UI does not offer the needed correction, send Seller Support the listing reference and exact requested change.',['creators/releases','creators/studio','marketplace/project-details']],
])
