import { family } from '../doc-types'
export default family('Export & ownership', [
['export','Export source code','Export downloads the working project’s accepted source so you can continue outside Webcanbe. It is a source handoff, not a deployment or a transfer of every third-party right.','Save the changes you want to include and inspect the latest accepted revision. Resolve pending source operations and keep the project’s license requirements available.',[
'Open the intended working copy and confirm its identity. Use Export from the workspace.',
'Wait for the download and save the archive with a meaningful project/version name.',
'Extract it into a separate directory and inspect the source, package manifest and included instructions.',
'Continue in your own development environment, retaining required license notices and supplying your own service configuration.'
],'The archive should contain the source represented by the accepted revision, including saved Visual, Code and applied AI changes. Your unsaved editor text should not be assumed to be included.','Export does not provision hosting, domains, databases or production secrets. External assets and dependencies remain subject to their own terms. Runtime compatibility in Webcanbe does not guarantee that every local environment is configured correctly.',['export/accepted-source','export/local-setup','export/ownership']],
['export/accepted-source','What an export includes','An export represents accepted working source. Drafts, unaccepted AI proposals and temporary preview state are not the same source state and should be checked before downloading.','Inspect History and the editor’s unsaved indicators. If the preview is delayed, use the accepted revision as the reference rather than repeatedly applying the same change.',[
'Save intended Code drafts and wait for acceptance. Apply reviewed AI work only if it is still current.',
'Confirm the project and latest revision before starting Export.',
'After extracting the archive, inspect a file you recently changed and verify that the accepted edit is present.',
'Keep the archive alongside a note of the working project and revision if you need to reproduce a handoff later.'
],'The files should agree with accepted source. A mismatch should be reported with project/revision context and a minimal description of the missing change.','An export is not a dump of your Webcanbe account or session, and it should not be expected to contain service credentials. Files committed into the project can still contain sensitive data if you put it there; review source before sharing the archive externally.',['history/drafts','export/review','export/troubleshooting']],
['export/local-setup','Run exported source locally','Treat the exported project as a codebase you inspect before running. Follow its manifest and instructions in your own development environment rather than assuming every release uses identical commands.','Extract the archive into a new directory. Install a runtime version suitable for the project and review package scripts and dependencies before executing them on your machine.',[
'Read the project instructions, package manifest and available lockfile. Identify required runtime versions and documented commands.',
'Review installation and lifecycle behavior. Choose your own trusted local workflow for dependency installation.',
'Provide local environment configuration through the project’s supported mechanism. Keep secrets outside committed public source.',
'Run the documented development/build commands and inspect the result. Use local errors to identify missing services or dependencies.'
],'The exported files should be usable in a conventional source workflow. Your saved changes should appear when the project is configured and run successfully.','Webcanbe’s controlled preview does not execute arbitrary uploaded lifecycle hooks; your local environment may. Review scripts before running them. A browser-only preview also does not supply databases, API accounts or credentials needed for the full application.',['compatibility/dependencies','export/environment','export/troubleshooting']],
['export/environment','Configure external services','Exported source may reference services that you must configure independently. A marketplace preview is not a transfer of the creator’s accounts, API keys or production infrastructure.','Inspect the project’s setup instructions and environment-variable references. Classify each value as public browser configuration or a secret that belongs on a trusted server.',[
'List the external services used by the project, including APIs, storage, authentication and payment systems.',
'Create or use your own authorized service accounts and follow their official configuration process.',
'Place secrets in the appropriate local or hosting environment, not in browser-bundled source or a public repository.',
'Test with non-production data first and verify that the exported application points to your intended environment.'
],'The project should use your configuration and accounts when run outside Webcanbe. Sensitive values should not appear in browser code, logs or shared source archives.','The exact environment setup depends on the project and provider. Documentation cannot infer missing backend behavior from a UI category. If the release does not explain a required service, ask Seller Support with the release reference rather than using credentials found in a preview.',['export/local-setup','security/secrets','compatibility/runtime']],
['export/ownership','Source ownership and permissions','Keeping real source gives you a portable development artifact. Your rights to use or redistribute the original release still come from its applicable license and third-party terms.','Read the release license and inspect notices included with exported files. Separate your own modifications from the creator’s original source and bundled dependencies or assets.',[
'Retain the listing/release reference and license terms associated with acquisition.',
'Preserve required copyright, attribution and dependency notices when moving source into your repository.',
'Check permissions for your intended use, especially client delivery, redistribution or sale of a derivative template.',
'Ask Seller Support about unclear rights before publishing or transferring source beyond the permitted use.'
],'You should have both the editable code and a record of the permissions that govern it. Continuing outside Webcanbe does not require converting a proprietary canvas back into source.','This page does not grant a universal resale license or claim ownership of third-party code. Exportability and legal permission are separate. Changes you make do not automatically remove obligations attached to dependencies, fonts, images or the acquired release.',['marketplace/licenses','creators/licensing','purchases/access']],
['export/review','Review an archive before sharing','Inspect an exported archive before handing it to a client, colleague or public repository. A successful download verifies packaging, not readiness for every audience.','Know which revision you exported and who will receive it. Check the applicable license before transferring source to another person or organization.',[
'Extract the archive and inspect recently edited files to confirm the intended accepted source is present.',
'Search your own source for credentials, private endpoints and personal data before sharing. Remove sensitive material through a deliberate source revision if needed.',
'Keep required license notices and add accurate setup instructions for configuration that the recipient must supply.',
'Run the project’s relevant checks in your trusted environment and document known limitations for the recipient.'
],'The recipient should receive the intended source with enough context to use it responsibly, without accidental secrets or misleading claims about configured services.','Do not assume a source archive includes a production database, deployment history or account entitlements. Automated packaging cannot establish that every file is safe to publish. If a secret was already exposed, rotate it with the provider rather than merely deleting the visible text.',['security/secrets','export/ownership','export/local-setup']],
['export/troubleshooting','Troubleshoot export failures','If export fails, preserve the accepted source state and identify whether the problem is the request, the download or local extraction. Repeated source edits are not a useful way to fix a packaging error.','Check that the intended changes were saved and that you are still signed into the correct account. Record the visible error and project/revision reference.',[
'Retry once after checking connectivity and the browser’s download handling. Look for a completed file before requesting another export.',
'If a file downloaded, inspect its size and whether extraction completes. Keep the original archive while investigating.',
'Compare a recently changed source file with the accepted revision when content appears missing.',
'Report persistent failures through Report an Issue with the operation, browser and safe project reference. Share private source only through an agreed appropriate channel if it becomes necessary.'
],'You should identify whether the archive was never produced, the browser blocked it, extraction failed or the wrong accepted revision was exported. These are distinct support cases.','Do not clear browser data before preserving important drafts. A missing unsaved edit is expected export behavior, not necessarily corruption. An export failure does not imply that the server source was deleted or that a new purchase is required.',['export/accepted-source','history/recovery','security/support-data']],
['export/version-control','Continue in version control','After export, place the source in your own version-control workflow to track development outside Webcanbe. Keep release provenance and license notices with the initial import.','Review the archive for secrets and confirm you have permission to share the repository with its intended audience. Choose repository visibility before pushing any files.',[
'Extract the accepted source into a new local directory and inspect its contents.',
'Initialize or import into your chosen version-control system using your own tooling. Record the source release and exported revision in a useful initial commit note.',
'Keep generated dependencies and sensitive environment files out of the repository according to the project’s needs.',
'Run local checks, commit coherent changes and configure hosting separately when you are ready.'
],'You should have an understandable starting commit containing the exported source and required notices. Later local changes can be reviewed independently of Webcanbe history.','Export does not automatically establish two-way synchronization with a remote repository. Do not assume local commits will appear in the Webcanbe working copy or that a later export will merge them. Plan how you will reconcile divergent copies before editing both simultaneously.',['export/review','export/ownership','working-copies/source-release']],
])
