import { family } from '../doc-types'
export default family('Getting started', [
['what-is-webcanbe','What is Webcanbe?','Webcanbe is a source-first web project marketplace with a browser workspace for visual and code editing. Start with a published project, create a working copy, and keep the real source code as you change it.','A marketplace listing describes a project; a release identifies a version of its source. Your editable working copy is separate from that release. Acquiring a project gives the entitlement described by its license, not ownership of every dependency or third-party asset.',[
'Browse a listing and inspect its release, preview, license and compatibility information before acquiring it.',
'Create an editable working copy from an entitled release. Open Visual for supported element changes, Code for direct source edits, or Split to keep source beside the preview.',
'Use AI editing to propose source changes, review the diff, then apply deliberately. History records accepted revisions. Export packages the accepted source for work outside Webcanbe.'
],'You have a normal source project, not a proprietary drawing that must be converted into code. Visual, Code and AI edits belong to the same working source. Export does not remove the license obligations attached to the original project.','Current compatibility focuses on admitted React/Vite projects. Runtime support and visual editability are different: a page can render while some expressions or styling require Code. Arbitrary servers, uploaded configuration and lifecycle scripts are not automatically executed. Review the compatibility report rather than assuming every web stack runs here.',['getting-started','compatibility','export','marketplace']],
['getting-started','Getting started','Complete a small edit before making a large redesign. This guide takes you from a marketplace release to a saved working copy and a source export.','Use a supported browser and sign in to the account that will acquire the project. Read the listing license and inspect the public preview. If checkout or workspace creation is unavailable, do not treat a button click as confirmation that you own an editable copy.',[
'Choose a project in Marketplace. Check its published release and compatibility details, then follow the available acquisition action.',
'Open Purchases and create or open a working copy. Keep the original release name available so you can distinguish it from your edited project.',
'Select a simple text element in Visual. Apply a supported text change, or switch to Code when the target cannot be edited visually.',
'Wait for the save to finish, inspect the preview, and open History. Export the accepted source once the result is correct.'
],'The text change should survive reopening the working copy and appear in the exported source. An unchanged marketplace listing is expected: editing your copy does not publish a creator release.','Do not judge success from preview appearance alone. Unsaved Code drafts and failed operations are not accepted source. Resolve save conflicts before exporting. If the runtime cannot preview the project, inspect its compatibility report and use the source workflow appropriate for that project.',['marketplace','working-copies','history','export']],
['create-account','Create an account','Create or access your Webcanbe account through the sign-in flow before acquiring projects or opening a private workspace.','Choose a sign-in method you can continue using. Account access, marketplace entitlements and working copies belong to an authenticated account; a browser tab or a payment return screen alone does not establish that identity.',[
'Open Sign in from the public header. Choose one of the methods actually offered by the current authentication screen.',
'Complete the provider or email verification step in its own flow. Return to Webcanbe and confirm the account shown in Settings.',
'If you already bought a project, use the original account rather than creating a second account to troubleshoot a missing purchase.',
'Keep recovery access to the underlying provider or email address. Use Account Help if the account identity does not match your expectations.'
],'After authentication, account-specific navigation should open without asking you to repeat sign-in. Purchases and projects may be empty for a new account; this is different from a failed session.','Available providers depend on the live authentication configuration. Never send a support agent a password, one-time code or provider token. If a provider returns an error, record the visible message and method used, then follow the sign-in troubleshooting guide.',['sign-in','account/identity','troubleshooting/login']],
['sign-in','Sign in to Webcanbe','Sign in with the account that owns your projects and purchases. A successful provider login must return to Webcanbe before the workspace session is ready.','Keep cookies and required browser storage available for the authentication flow. When using multiple Google or GitHub accounts, check the selected identity at the provider prompt rather than assuming your usual account was chosen.',[
'Open /login or use Sign in in the public navigation. Select the available provider or email method.',
'Complete the requested verification. Allow the flow to return to Webcanbe; do not copy callback URLs into a support ticket.',
'Open Settings and confirm the account. Then open Purchases or Projects to check the content associated with it.',
'If the session is rejected, retry once from a fresh sign-in entry and note the visible error rather than repeatedly submitting the same callback.'
],'Your private pages should become accessible under the confirmed account. Signing in does not acquire a marketplace release or create a working copy by itself.','A missing purchase under a different identity is not proof of lost data. Switch back to the original account or contact Account Help with safe account/provider details. Private browsing restrictions and blocked authentication redirects can interrupt the return step.',['create-account','account/providers','troubleshooting/login']],
['first-project','Choose your first project','Choose a first project by its source, license and compatibility, not by its preview alone. A small project makes it easier to understand the complete editing and export workflow.','Decide whether you need a marketing site, application interface, editorial project or another category. A preview can demonstrate layout without proving that a backend, payment service or external integration is configured for your account.',[
'Browse a relevant category and open a project detail page. Read the release information, included files and any compatibility notes.',
'Inspect the preview at more than one width. Look for the particular pages and components you expect to change.',
'Check the license and acquisition terms. Identify any third-party assets, service accounts or environment variables that you will need to provide.',
'Acquire only when the listing fits your requirements, then create a working copy and attempt one representative edit.'
],'You should be able to explain what the release includes and what remains your responsibility. The first edit should confirm that the workflow fits the task before you invest in a larger redesign.','Categories describe discovery, not a guarantee of feature completeness. A Commerce project does not automatically include a live merchant account. Ask Seller Support about unclear release details and avoid entering production credentials into a public preview.',['marketplace/project-details','compatibility','purchases/acquire']],
['releases-introduction','Understand project releases','A release is a versioned source snapshot associated with a marketplace listing. It separates the project you acquired from later changes a creator may publish.','Before acquiring a project, note the listing and release version. A listing can change its public description independently of the working copy you already created. Treat version identifiers as references, not promises that every change is backward-compatible.',[
'Open the project details and find its release information. Read the description of what the published version contains.',
'When creating a working copy, confirm the release you are starting from. Keep the version in your project notes if you are comparing several copies.',
'If the creator publishes another release, compare the new notes before adopting it. Do not assume it silently rewrites your edited files.',
'For a release-specific problem, send Seller Support the listing and release identifiers together with a concise description.'
],'Your working copy starts from an identifiable source version. Later edits belong to your copy and its history; the creator release remains a separate reference.','An immutable release does not guarantee that external APIs, hosted images or third-party services never change. Check dependency and asset requirements before relying on a preview for production. Availability of upgrades depends on the listing and entitlement rules shown in the product.',['marketplace/releases','working-copies','creators/releases']],
['first-edit','Make your first edit','Start with one visible text or style change and verify that it becomes accepted source. This makes the relationship between Visual, Code and the preview concrete.','Open an editable working copy with a connected preview. Choose ordinary visible text instead of a value generated from an API, a loop or a complex expression. Keep the initial edit small enough to inspect in History.',[
'In Visual, enable element selection and click the target. Check that the inspector identifies an editable source-backed element.',
'If text editing is available, change the text and apply it. For styles, inspect the property and active breakpoint before saving.',
'If the target is unavailable or read-only, switch to Code, locate the source definition and make the small edit there. Save the draft.',
'Wait for acceptance, inspect the refreshed preview, and review the new history entry before making another change.'
],'The accepted source, preview and history should agree. Reopen the working copy if you need to confirm persistence; a draft in an open editor is not that confirmation.','A shared component may update several instances. Undo or restore deliberately if the scope is wrong, then inspect the source definition. A disconnected preview may lag behind saved source; do not repeat the mutation merely because rendering is delayed.',['visual-editor/select-elements','code-editor/saving','history']],
['first-export','Export your first project','Export the accepted source after your first successful edit so you can inspect exactly what leaves Webcanbe.','Save open Code drafts and resolve pending operations first. The export is a source package; it does not include your Webcanbe session, a hosted production account or a guarantee that external services will be configured locally.',[
'Open the working copy you intend to export and check its latest accepted revision in History.',
'Use Export in the workspace. Wait for the download to complete and save the archive in a location you can identify.',
'Extract the archive into a new local directory. Inspect its source files, package manifest and project instructions before running commands.',
'Follow the project’s documented local setup in your own development environment. Provide your own service configuration where required.'
],'Your saved edit should be present in the downloaded source. You can version that source in your own repository and continue development subject to the project and dependency licenses.','Unsaved drafts are excluded. Exporting source is separate from deploying a site, transferring a domain or acquiring third-party asset rights. If the archive is missing or incomplete, retain the working-copy reference and report the failure without sending private source by default.',['export','export/local-setup','export/troubleshooting']],
])
