import { family } from '../doc-types'
export default family('History, save & recovery', [
['history','History','History records accepted changes to a working project. Use it to understand how Visual, Code and applied AI edits changed the same source over time.','Open the correct working copy and finish or preserve outstanding drafts. A draft, an AI proposal and a preview refresh are not necessarily accepted source revisions.',[
'Open History and inspect the most recent accepted entry. Compare its operation and source changes with the task you just completed.',
'Locate an earlier entry when investigating when a behavior changed. Keep the original release reference separate from your working revision.',
'Use the available history action deliberately when returning to an earlier state. Preserve important current source through an export first when appropriate.',
'After any restoration or undo, inspect the preview and current source before making a new edit.'
],'The history should explain accepted project changes across editing modes. The current accepted revision should be the basis for subsequent saves, AI proposals and export.','History is not a record of every keystroke or every failed request. External services and remote assets can change without a source revision. Do not infer a retention or backup guarantee beyond what the product and applicable terms provide.',['history/inspect','history/undo-redo','history/drafts']],
['history/inspect','Inspect a source revision','Inspect a revision to understand what changed and whether it explains a visible behavior. Start from the source difference rather than only the operation’s label.','Identify the working project and the approximate time or task associated with the change. If the issue involves a creator release, keep that version alongside the working revision.',[
'Open History and choose the relevant accepted entry. Read the changed files or operation details available in the UI.',
'Compare the change with neighboring revisions. Look for shared component edits that could affect more than the current page.',
'Check the current preview and source to determine whether later edits superseded the behavior.',
'When reporting an issue, include the safe project/revision reference and a description of the difference without attaching private source by default.'
],'You should be able to identify the accepted change associated with the problem or conclude that it is likely a runtime/external-state issue. Keep that distinction in the support request.','A revision does not capture payment provider state, external APIs or every browser interaction. AI proposal generation can exist without source application. Do not treat a request timestamp or preview screenshot as an accepted revision identifier.',['history','history/ai-changes','working-copies/source-release']],
['history/undo-redo','Undo and redo source changes','Use workspace Undo and Redo to move deliberately through supported source changes. Distinguish project-level operations from undoing text inside an unsaved editor draft.','Check focus and unsaved state before using keyboard shortcuts. Preserve a draft you need before changing the accepted project state beneath it.',[
'Inspect the current revision and identify the change you want to reverse. Use the visible workspace control when keyboard focus is ambiguous.',
'Run Undo and wait for the accepted result. Check the source and preview rather than assuming the previous visual appearance proves completion.',
'Use Redo only when the product offers the intended reversal and no intervening work makes it inappropriate.',
'After returning to the desired state, save subsequent edits against that current revision and regenerate stale AI proposals.'
],'The accepted source should reflect the selected history operation and subsequent edits should use its revision. A Code draft may still need separate review.','Undo is not a substitute for license compliance, payment reversal or deleting an acquired release. An AI generation charge is separate from undoing the resulting source change. If an operation’s outcome is uncertain, reload authoritative history before repeating it.',['code-editor/shortcuts','history/conflicts','ai-editing/stale-revisions']],
['history/drafts','Drafts versus accepted source','Accepted source drives project history and export. Draft text can be visible in Code while the preview and other operations still use the previous accepted revision.','Inspect the editor’s unsaved indicator before applying Visual or AI work. Mixing a long draft with other accepted mutations can produce conflicts that need deliberate reconciliation.',[
'Finish a coherent draft and save it before starting an unrelated mutation.',
'Confirm the save in History and inspect the preview. Treat a loading or validation error as unresolved until the accepted state is clear.',
'If a draft conflicts with newer source, compare the versions and reapply the intended difference rather than overwriting blindly.',
'Before exporting, verify that every intended file change has been accepted.'
],'You should be able to name the revision represented by the export and preview. Reopening the project should show the saved source independently of browser draft recovery.','A recovered draft is not server history and may be stale. Browser storage can be cleared or unavailable. Do not rely on an open tab as your only copy of important work; combine accepted saves with appropriate source exports and your own version control.',['code-editor/drafts','history/recovery','export/accepted-source']],
['history/conflicts','Resolve save conflicts','A save conflict means your edit was based on a source revision that is no longer current. Resolve the difference against accepted source instead of repeatedly submitting the old revision.','Preserve the intended draft safely before reloading. Check whether another tab, a Visual edit, an AI application or a history operation changed the project.',[
'Read the conflict message and identify the latest accepted revision through the workspace or History.',
'Compare the latest file with your draft. Keep changes that remain relevant and avoid removing intervening work accidentally.',
'Reapply the smallest intended difference to the current source and save again.',
'Inspect the accepted result and preview. Close redundant editing tabs if they are causing repeated conflicts.'
],'The next accepted save should include your intended change on top of current source. The rejected request should not be treated as a successful revision.','Do not change revision identifiers or replay captured requests to bypass conflict checks. If the source keeps changing unexpectedly, stop mutations and inspect account/project context. Support needs safe project references and the operation sequence, not session cookies or private file contents by default.',['code-editor/saving','ai-editing/stale-revisions','history/recovery']],
['history/recovery','Recover after an interruption','After a connection loss or browser interruption, establish the accepted project state before recovering unsaved work. A lost response can leave the operation outcome uncertain.','Keep the tab or recovery prompt available if it contains draft text. Avoid starting duplicate saves, exports or AI applications while you do not know what the server accepted.',[
'Reopen the working copy under the correct account and inspect History for the last accepted revision.',
'Compare any recovered draft with that source. Preserve only the intended differences and resolve conflicts deliberately.',
'Check preview connection separately. A stale preview does not prove a save failed.',
'Save the reconciled draft and verify it by reopening or inspecting the accepted file. Export a known-good result if appropriate.'
],'You should recover useful draft work without replacing a newer accepted revision. The final source, History and preview should agree once rendering is ready.','Recovery depends on available browser and service state; it is not a promise of unlimited backups. Clearing site data can remove local drafts. If a source operation has an unknown result, report its safe reference and visible state before attempting an unsafe replay.',['history/drafts','history/conflicts','working-copies/missing']],
['history/ai-changes','Find AI changes in History','Applied AI edits enter source history as accepted project changes. Generated proposals that were never applied are not equivalent to source revisions.','Keep the request reference if you are investigating AI usage, and the source revision if you are investigating code behavior. They describe different stages of the workflow.',[
'Open History after a confirmed AI application and inspect the affected files.',
'Compare the accepted changes with the proposal you reviewed. Check the preview and relevant interactions.',
'If the change is wrong, use the supported history operation or make a corrective source edit. Resolve any open drafts first.',
'For a usage discrepancy, send Billing Help the request context separately from a report about incorrect source behavior.'
],'History should show the actual accepted source result, regardless of whether generation used Standard or Deep. Export should contain the current accepted AI changes along with other saved edits.','Undoing source does not necessarily reverse the Action cost of a successful generation. Pending settlement and uncertain application status require authoritative reconciliation. Do not infer application from a balance decrease or assume a missing preview update means the source stayed unchanged.',['ai-editing/actions','ai-editing/apply','history/undo-redo']],
['history/multiple-tabs','Work across browser tabs','Multiple tabs can observe the same working project at different revisions. Keep one active editing context when possible to reduce stale saves and proposals.','Identify which tabs have unsaved drafts or pending operations. A second tab can be useful for reading docs, but two editors do not automatically coordinate your intended changes.',[
'Choose the tab that will make the next source mutation. Save or safely preserve drafts in other tabs.',
'After a successful change, refresh the accepted state in another editor before using it to save or generate AI work.',
'If a stale-revision error appears, compare the current source rather than retrying the older operation.',
'Close redundant editor tabs once their drafts have been resolved. Keep documentation and public previews in separate tabs as needed.'
],'Subsequent operations should use the latest accepted revision. You should not need to guess which tab contains the authoritative source.','Browser tab state is not collaborative conflict resolution. Do not share account sessions as a collaboration mechanism. If the same account shows inconsistent source after reload, collect project and revision references for support without exporting cookies, tokens or unrelated private data.',['history/conflicts','ai-editing/stale-revisions','account/sessions']],
])
