import { family } from '../doc-types'
export default family('Marketplace & discovery', [
['marketplace','Browse marketplace projects','Marketplace organizes published web projects so you can compare a release before creating an editable copy. Browsing is public; acquiring and editing a project require the relevant account access.','Know the kind of project you need and distinguish visual appearance from included functionality. Marketplace category images illustrate a category; only a published listing represents a specific available release.',[
'Open Marketplace and inspect the available projects. Use category discovery to narrow the collection by the type of site or interface.',
'Open a listing card to read its detail page. Check the title, creator-provided description, release and any displayed license or compatibility information.',
'Inspect the public preview when one is available. Return to the detail page before choosing the acquisition action.',
'If the collection is empty or unavailable, use the visible state to distinguish no matching projects from a catalog loading error.'
],'A listing card should open an identifiable project detail route, while a category card opens that category’s collection. Neither action should create a purchase or mutate your workspace.','Inventory is supplied by the public catalog. An unavailable listing is not an invitation to acquire a different version through a guessed URL. Category labels do not certify runtime support; review the project’s own compatibility information.',['marketplace/search','marketplace/categories','marketplace/project-details']],
['marketplace/search','Search projects','Use project search to find published listings whose names or descriptions match the task you want to build. Search narrows discovery; it does not inspect private project source.','Start with a concrete term such as portfolio, editorial or dashboard. Very broad phrases can hide useful matches, while exact internal filenames are unlikely to be meaningful public search terms.',[
'Open Marketplace and enter a short term in the search field. Wait for the results or error state before changing several controls at once.',
'Combine the query with a category only if you need a narrower set. Clear the category when a reasonable search returns no matches.',
'Open a promising result and verify the release details. A matching title does not guarantee that a specific backend or integration is included.',
'Clear the query to return to the collection. If search fails, retry the catalog rather than interpreting the failure as an empty marketplace.'
],'Results should reflect the visible search and category controls. Opening a result takes you to its stable listing URL, where acquisition and release information can be checked separately.','Search coverage depends on the metadata published with each listing. It is not semantic code analysis and should not be used to infer compatibility. Do not put credentials, private source or account identifiers into a public search query.',['marketplace','marketplace/categories','marketplace/project-details']],
['marketplace/categories','Filter by category','Categories group projects by their intended presentation or use, such as marketing websites, commerce, directories and editorial experiences. They help you explore without prescribing a technical stack.','Choose a category based on the job the interface needs to do. A SaaS or Dashboard label can describe an application interface without including a hosted backend, authentication provider or production data.',[
'Open a category from Marketplace or the footer. The category has a readable public route you can bookmark and share.',
'Review the collection heading and description, then open individual projects for release-specific details.',
'Switch to All projects to remove the category restriction. If search is also active, clear it independently when broadening results.',
'Compare the project’s compatibility report and license before deciding that the category is enough to establish fit.'
],'You should reach a collection for the selected category, not a generic contact page or an unrelated listing. An empty category should explain that no published projects currently match.','A project can fit more than one use case. Categories are discovery aids rather than technical certifications or guarantees of inventory. Query-based category links, when encountered, should resolve to the corresponding canonical category route instead of creating duplicate indexed collections.',['marketplace/search','first-project','compatibility']],
['marketplace/project-details','Read a project detail page','A project detail page is the place to verify what a listing offers before acquiring its release. Treat the preview, source release and license as related but distinct information.','Have your intended use in mind: a personal site, client work, a commercial application or a starting point for further development. Different uses may be governed by the release’s displayed license.',[
'Check the project identity and published release. Read the full description rather than relying on the card summary.',
'Inspect the preview and any compatibility information. Identify external services, assets or setup that you will need to supply.',
'Read the price and acquisition state shown by the live product. If a price or checkout is unavailable, do not assume the project is free.',
'Follow the available acquisition action only after confirming the terms. Keep the listing URL and release reference for later support.'
],'You should understand which source version you are acquiring and what the next action will do. Opening details alone does not create an entitlement or a working copy.','Descriptions are not a substitute for the applicable license. Missing or unpublished listings should return a clear unavailable/not-found result. If details conflict with the checkout display, pause and contact Billing Help or Seller Support before paying.',['marketplace/previews','marketplace/licenses','purchases/acquire']],
['marketplace/previews','Use public previews','Public previews help you evaluate a project’s interface before acquisition. They are a view of a published project, not your own editable workspace.','Do not enter production credentials, personal customer data or payment details into a project preview. A preview may show representative interface states without connecting to a live service.',[
'Open Preview from a listing that offers it. Check the visible page structure, navigation and responsive presentation.',
'Try ordinary interface interactions only when the preview supports them. Note whether the preview is interactive or a rendered snapshot.',
'Return to the listing to review release and compatibility information. If an interaction matters to your use case, verify that it is included in the source.',
'If the preview cannot load, record the listing reference and visible error. Inspect the remaining release information or contact Seller Support.'
],'You can evaluate layout and supported interactions without changing the published release. Edits you make later belong to a working copy created through your account.','A rendering success does not certify visual editability, deployment readiness or third-party service availability. Snapshot previews may not support clicks and dynamic behavior. Do not mistake an unavailable preview for proof that a purchase failed; those are separate systems.',['compatibility/preview-modes','marketplace/project-details','troubleshooting/preview']],
['marketplace/releases','Compare release versions','Release versions identify published source snapshots. Compare the release you own with the version currently offered before starting new work or requesting support.','Keep the version associated with your purchase or working copy. A creator can publish new work without changing the snapshot from which your existing copy was created.',[
'Open the listing and read its current release information. Compare that reference with the release attached to your purchase or copy.',
'Review the creator’s release notes when provided. Look for dependency changes, removed pages, compatibility changes and migration instructions.',
'If a newer release is available to your account, create or inspect it separately before deciding how to carry over your custom edits.',
'Use exact listing and release identifiers in a support request so the creator can reproduce the correct source version.'
],'You should know whether you are inspecting the original release, a newer publication or your own edited revision. These identifiers solve different problems and should not be treated as interchangeable.','Do not assume automatic upgrades, permanent access to all future releases or a merge of your changes unless the live product and applicable terms explicitly provide it. Immutable source cannot freeze third-party services or external network resources.',['releases-introduction','creators/immutable-releases','working-copies/source-release']],
['marketplace/free-and-paid','Free and paid projects','A project’s displayed acquisition terms determine whether payment is needed. Free acquisition and paid checkout can both lead to an entitlement; neither should be confused with creating a working copy.','Sign in with the account that should own the entitlement. Check the listing license even when the price is zero, because free pricing does not mean unrestricted redistribution or ownership of third-party assets.',[
'Open the listing and read the current price, currency and release details. Use the live checkout display for the amount rather than an old screenshot.',
'For a free project, complete the offered acquisition flow. For a paid project, complete the available checkout and return to Webcanbe.',
'Check Purchases for the entitlement before creating an editable copy. If settlement is pending, allow the product to confirm the payment state.',
'Keep the order reference if payment appears complete but the purchase is missing. Contact Billing Help without sending payment credentials.'
],'An acquired project should appear under the correct account with its release reference. You can then follow the working-copy action supported by the product.','Checkout availability and supported payment methods depend on the current configuration. A canceled return or pending provider screen is not purchase confirmation. Prices, tax and fees should be read from the actual checkout, not inferred from general documentation.',['purchases/acquire','purchases/missing','marketplace/licenses']],
['marketplace/licenses','Check a project license','Read the license attached to the release before using, modifying or distributing its source. Export provides files; it does not replace the terms governing those files.','Identify how you plan to use the project, including client delivery, commercial use, resale or redistribution. The project license and the licenses of bundled dependencies or assets can impose different obligations.',[
'Open the listing and locate the displayed license or linked terms. Check that they apply to the release you intend to acquire.',
'Review permitted use, redistribution limits and attribution requirements. Inspect bundled license files after export.',
'List third-party fonts, images, icons and packages that need separate attention. Do not assume the creator can grant rights they do not hold.',
'If a permission is unclear, ask Seller Support with the listing and release reference before relying on it.'
],'You should have a record of the terms relevant to the acquired release and understand any notices that must accompany your use. Keep those notices with the project when moving it into another repository.','This guide explains where to check permissions; it does not grant a universal commercial or resale license. The Buyer License page describes the policy framework and points to the release-specific terms. Contact support if the listing and included files disagree.',['export/ownership','creators/licensing','purchases/entitlements']],
])
