import { family } from '../doc-types'
export default family('Purchases & entitlements', [
['purchases/acquire','Acquire a project','Acquisition associates a marketplace release with your account. Create an editable working copy only after the product confirms the entitlement.','Sign in and inspect the listing’s release, license and live price. Use the same account throughout acquisition so that the resulting purchase and your workspace are connected.',[
'Open the project detail page and choose the acquisition action currently offered. Read the confirmation or checkout screen before continuing.',
'Complete a free acquisition or the provider checkout as applicable. Return to Webcanbe through the supported flow.',
'Open Purchases and locate the project. Verify its release reference and the displayed status.',
'Use the working-copy action from that confirmed purchase. Give the editable project a name that distinguishes it from the original release.'
],'The purchase should be attached to your account, with a separate working project created only when that action succeeds. The marketplace release itself remains unchanged.','A payment provider approval is not always the final settled state. Do not repeatedly pay because the return page is slow. If the purchase remains absent, retain the order reference and contact Billing Help; never include full card details or provider credentials.',['purchases/entitlements','purchases/checkout-return','working-copies']],
['purchases/entitlements','Understand entitlements','An entitlement records your account’s access to an acquired release. It is different from the downloaded files, the public listing and the editable project you create from it.','Confirm which account you are signed into. A release can be publicly visible while acquisition is still required to create a private working copy. Access is checked by the service, not inferred from a public URL.',[
'Open Purchases and find the acquired project. Read the release and access state shown for that item.',
'Use the available action to open or create a working copy. If the operation is rejected, preserve the visible error instead of modifying request parameters.',
'Compare the account identity with the account used during checkout when a purchase appears missing.',
'Ask Billing Help about entitlement discrepancies using an order or purchase reference and the listing URL.'
],'A valid entitlement enables the operations offered for that release under its terms. Your edited source and revision history belong to a separate working copy.','An entitlement is not a blanket grant to all future versions or to unrelated third-party assets. Refunds and payment reversals can affect access according to applicable policy. Do not attempt to restore access by sharing session cookies or another person’s account.',['marketplace/licenses','purchases/missing','purchases/refunds']],
['purchases/checkout-return','Return from checkout','After checkout, verify the purchase in Webcanbe rather than relying solely on the payment provider’s return screen. Payment confirmation and entitlement creation may not be visible at exactly the same moment.','Keep the checkout tab until you have returned and checked your account. Record the provider’s non-sensitive order reference if one is displayed; do not copy payment tokens or the full callback URL.',[
'Complete checkout and use its return action. Wait for Webcanbe to show the current order state.',
'Open Purchases under the same signed-in account and look for the acquired release.',
'If the order is pending, refresh the purchase view after allowing confirmation to complete. Avoid submitting a second payment for the same intended purchase.',
'If the status stays inconsistent, contact Billing Help with the order reference, approximate time and visible message.'
],'A confirmed purchase should resolve to an entitlement for the selected release. A canceled or failed checkout should not be presented as a completed purchase.','Browser navigation is not payment authority. Closing a tab, reaching a success-looking URL or editing query parameters cannot establish a paid order. Support can investigate a reference, but you should never send passwords, card security codes or provider access tokens.',['purchases/acquire','purchases/missing','billing/orders']],
['purchases/missing','Find a missing purchase','First check account identity and order status when a purchased project is not listed. Creating another account or paying again can make the investigation harder.','Have the listing URL, approximate checkout time and any non-sensitive order reference available. A receipt can help identify the transaction, but redact payment credentials and unrelated personal details before sharing it.',[
'Open Settings and confirm that this is the account used to acquire the project. Check the provider identity if you use several accounts.',
'Open Purchases and refresh its state. Distinguish a loading error from a successfully loaded empty list.',
'Check whether checkout was completed, canceled or still pending. Do not infer completion from a redirect alone.',
'Contact Billing Help with the listing, order reference and observed status. Explain whether the purchase previously appeared or has never appeared.'
],'The investigation should identify either the correct account, a pending/failed transaction or an entitlement discrepancy that support can trace. Keep the original working copy if you already created one.','A public listing can become unavailable independently of the account’s purchase history. Do not send private source, auth cookies or full callback URLs to prove ownership. Account Help is the better channel when the original sign-in identity cannot be accessed.',['purchases/checkout-return','account/identity','billing/orders']],
['purchases/working-copy','Turn a purchase into a working copy','A purchase supplies access to a release; a working copy supplies the editable source and revision history. Creating the copy is a distinct operation.','Open Purchases under the entitled account. Check your plan’s current project capacity before starting another copy, and choose the release you actually want to customize.',[
'Find the acquired release and select its create/open working-copy action. Read any capacity or compatibility message before proceeding.',
'Wait for the materialization operation to finish. Avoid repeatedly clicking while the product reports that creation is in progress.',
'Open the resulting project from Projects. Confirm its title and source-release reference.',
'Make a small edit and save it. Inspect History to ensure that you are changing your own source revision rather than a public listing.'
],'The new working project should appear in your account and reopen with its accepted source. The original release remains a reference that is not rewritten by your edits.','An acquisition does not guarantee every runtime or visual operation is supported. A failed creation can reflect capacity, admission or service availability; record the error and purchase reference. Never try to bypass a failed operation by changing entitlement or project identifiers in requests.',['working-copies','working-copies/capacity','compatibility/admission']],
['purchases/receipts','Keep purchase references','Keep enough transaction context to identify an order without storing or sharing payment secrets. Purchase references are useful for billing investigations and project provenance.','Use the records actually provided by checkout and your account. Do not assume Webcanbe offers a tax invoice, receipt download or accounting integration unless that action is present in the live product.',[
'Record the project listing, acquired release and order reference after a confirmed purchase.',
'Keep the payment provider’s receipt through its normal account or email workflow. Verify the amount and currency against the checkout you completed.',
'When contacting Billing Help, include the order reference and the specific discrepancy, such as a missing entitlement or an unexpected status.',
'Redact full payment details, unrelated transactions and private account data from any supporting attachment.'
],'You should be able to connect a billing question to a particular purchase without sending credentials. The source-release reference also helps separate a payment question from a project compatibility issue.','An order reference is evidence for investigation, not a transferable entitlement or license. If you need a particular invoice format or tax detail that is not offered, ask Billing Help before assuming it can be issued. Avoid publishing receipts in public issue trackers.',['billing/orders','purchases/missing','marketplace/releases']],
['purchases/refunds','Request help with a refund','Use Billing Help for a refund question and identify the exact purchase and problem. Eligibility must be assessed under the applicable terms and mandatory consumer protections.','Read the Refund Policy and the terms displayed when you acquired the release. Do not assume a universal refund window, automatic approval or that deleting a working copy reverses a payment.',[
'Collect the order reference, listing URL, release version and a concise explanation of the issue.',
'For a technical problem, describe the steps that failed and the visible error. Keep private source out of the initial message.',
'Open Billing Help and choose a billing request. State whether you are asking for troubleshooting, clarification or a refund review.',
'Wait for the decision and payment status through the supported channel. Keep records of the outcome for your own accounting.'
],'Support should have enough context to identify the transaction and explain the applicable next step. A submitted request is not confirmation that a refund has been issued.','Payment reversals can affect entitlements and seller balances. Existing local copies remain subject to applicable license and refund terms. This documentation does not create new refund promises or waive legal rights; unresolved policy questions should be clarified before purchase.',['billing/orders','purchases/entitlements','security/support-data']],
['purchases/access','Use acquired source responsibly','Access to a release and the right to use its source depend on the account entitlement and applicable license. Keep those records together as the project moves into your own development workflow.','Read the release license before sharing files with colleagues, clients or another account. The ability to download an archive is not permission to redistribute the original project as a competing template.',[
'Identify the release from which your working copy was created and retain the associated license notices.',
'Use Webcanbe under your own authorized account. Do not share login credentials as a way to transfer a purchase.',
'When exporting, include required notices and review separate third-party asset terms.',
'Ask Seller Support about unclear permissions before transferring source to a client or publishing a derivative project for sale.'
],'You should know both where the source came from and which permissions apply to your intended use. Your own edits do not erase obligations attached to the original project or dependencies.','This page does not define a universal seat policy, transfer right or client-use license. Those details belong to the applicable agreement and release terms. If your entitlement changes after a reversal, contact Billing Help rather than assuming previously visible controls establish continuing permission.',['marketplace/licenses','export/ownership','creators/licensing']],
])
