import { family } from '../doc-types'
export default family('Security, troubleshooting & reference', [
['security','Security overview','Webcanbe separates public discovery from authenticated source operations and runs project previews through controlled boundaries. Use the supported account and editing flows rather than sharing credentials or replaying private requests.','Treat source projects, prompts and support attachments as places where secrets can be exposed accidentally. Runtime admission and revision checks reduce specific risks but do not certify an application for production.',[
'Keep passwords, API keys and customer data out of project source and AI prompts.',
'Use supported sign-in and account controls. Verify account identity before acquiring or editing projects.',
'Review source changes, especially generated code that affects network requests, authentication or payments.',
'Report suspected vulnerabilities privately through Security Report with a minimal reproduction and no live credentials.'
],'Public pages should expose only public metadata, while private projects require authorized access. Accepted source operations should remain attached to the correct project and revision.','No software boundary eliminates all risk. Do not test other users’ data or bypass access checks while investigating. This overview describes product boundaries, not an audit certification or a guarantee of security for every marketplace project.',['security/runtime-isolation','security/secrets','security/disclosure']],
['security/runtime-isolation','Preview isolation and source admission','Project source is untrusted input to the editor and preview system. Uploaded configuration, scripts and dependencies are not automatically granted authority to execute inside the editor process.','Understand the difference between source files being stored, source being admitted for a supported preview, and code being run in your own local environment after export.',[
'Read the compatibility/admission report before relying on a project’s preview.',
'Use the supported runtime path and inspect explicit failure states rather than attempting to enable arbitrary uploaded hooks.',
'Keep production credentials out of previews and use safe data when testing interfaces.',
'After export, review package scripts and tooling before executing them on your own machine.'
],'The preview should have a defined supported environment and clear separation from account authority. A source package can remain exportable without every included tool being executed by Webcanbe.','Isolation does not make malicious application content harmless in every context or establish legal rights to its assets. Do not enter sensitive data into untrusted project interfaces. Report suspected boundary failures privately without attempting access to another user’s project.',['compatibility/admission','compatibility/runtime','security/disclosure']],
['security/secrets','Keep credentials out of source','Do not put credentials in marketplace submissions, browser-bundled source, AI prompts or support reports. A secret exposed in a file remains compromised even after the visible text is removed.','Identify public configuration separately from server-only secrets. Browser source and exported archives can be read by their recipients, and public listings or repositories can spread accidental disclosures.',[
'Review source and environment files before uploading, publishing or sharing an export.',
'Use your own provider’s supported secret storage in the appropriate trusted environment. Do not embed server keys into client code.',
'If a secret was exposed, revoke or rotate it with its provider and review the exposure scope.',
'Report any Webcanbe-related security concern through the private security channel using redacted evidence.'
],'Shared source should contain configuration instructions and safe examples rather than usable private credentials. Your application should obtain secrets only through the appropriate server-side configuration.','Deleting a committed key does not invalidate copies or logs. Do not ask support to test with your password or token. If a project appears to contain someone else’s credential, avoid using it and report the issue responsibly.',['export/review','export/environment','security/disclosure']],
['security/privacy','Privacy and account data','Use the Privacy Policy to understand Webcanbe’s published data practices and the Privacy Requests route for account-specific questions. Keep private source and sensitive identifiers out of public reports.','Separate public listing information from account, purchase and working-project data. A support investigation may need a reference, but it should not begin with your full project archive or authentication material.',[
'Read the current Privacy Policy and identify the data or account question you need answered.',
'Use Privacy Requests for access, correction, deletion or other applicable privacy-rights questions.',
'Provide a safe account reference and a clear description of the request through the supported private channel.',
'Follow any appropriate identity-verification process without sending passwords, session cookies or one-time sign-in codes.'
],'The request should reach a channel that can identify its category and explain the next step. Public documentation should not expose account-specific details.','This guide does not promise a particular retention period or automatic deletion outcome beyond the applicable policy and law. Some records can have legal, security or transaction-related handling requirements. Ask for clarification rather than assuming that closing a browser tab removes stored account data.',['security/support-data','account/profile','security/disclosure']],
['security/disclosure','Report a security issue','Report suspected security vulnerabilities privately through /contact/security. Provide enough information to reproduce the issue safely without accessing another person’s data.','Stop testing if it could expose private source, disrupt service or affect other accounts. Use only accounts and projects you control, and keep live credentials out of the report.',[
'Write a concise description of the suspected boundary failure and its potential effect.',
'Include the affected public route or component, approximate time and minimal reproduction steps using your own test data.',
'Redact tokens, cookies, passwords and unrelated personal information from screenshots or logs.',
'Send the report through the security contact flow and coordinate any sensitive evidence through an appropriate private channel.'
],'The report should be clearly categorized as security and contain a safe path for investigation. The initial message should not require opening a private source archive or handling a live credential.','This guidance is not authorization to bypass access controls, perform destructive testing or scan other users’ projects. It does not promise a bounty, legal safe harbor or response deadline. Avoid public disclosure of exploitable details while seeking coordinated handling.',['security','security/runtime-isolation','security/support-data']],
['security/support-data','What to include in support requests','Send the minimum context needed to investigate your issue. Safe references and a clear sequence are usually more useful than a full source archive or raw browser storage.','Choose the appropriate support category: account, seller, billing, bug report, sales, partnership or security. Review any automatically prepared context before opening your email client.',[
'Describe the intended action, what happened instead and whether the issue is reproducible.',
'Include safe account/project/listing/order references only when relevant. For a bug, include browser, build and a sanitized current route.',
'Write reproduction steps and attach a redacted screenshot in your email client if it helps.',
'Remove auth tokens, cookies, passwords, private source and unrelated customer data before sending.'
],'Support should receive a categorized request with enough context to route it correctly. The form should explain whether it actually sends a message or prepares an email for you to send.','Never assume a query string is safe: callback URLs and copied console output can contain credentials. Do not attach entire local storage, network archives or private repositories by default. Use Security Report for vulnerabilities and a private agreed channel for any later sensitive evidence.',['troubleshooting/contact','security/disclosure','billing/orders']],
['troubleshooting/login','Troubleshoot sign-in','Identify where sign-in fails: choosing a provider, completing verification, returning to Webcanbe or accessing the intended account. Each stage points to a different next step.','Keep the visible error and sign-in method available, but do not copy callback URLs or verification codes. If you already own projects, avoid creating new accounts while investigating.',[
'Retry from the normal /login entry using the intended provider account. Check browser restrictions that could block the return flow.',
'If verification is the problem, follow the provider or email instructions and use the current attempt.',
'After returning, inspect Settings to confirm account identity before checking missing purchases.',
'Contact Account Help with the method, stage, safe error text and approximate time if the problem persists.'
],'You should distinguish a failed session from a successful session under the wrong identity. Private pages should become available only after the supported flow completes.','Do not disable account security or share credentials to work around a login issue. A provider’s successful screen does not prove Webcanbe received the return. Repeatedly requesting verification messages can create confusing expired attempts rather than solve the original problem.',['account/google','account/github','account/email']],
['troubleshooting/preview','Troubleshoot an unavailable preview','Check preview connection and compatibility independently of source save state. A failed render does not automatically mean your accepted source was lost.','Open the correct working copy and note the reported preview mode. Keep the last accepted revision available through History.',[
'Read the preview status and use the supported reconnect action if the connection is unavailable.',
'Inspect compatibility or runtime errors for unsupported dependencies, source syntax or missing external services.',
'Check whether the most recent source save succeeded. If it did, avoid applying the same mutation again just to trigger rendering.',
'Report a persistent failure with the project reference, preview mode, browser and safe error text.'
],'The preview should either become ready for the accepted source or expose a specific limitation that can be addressed. Source History remains the reference while rendering is unavailable.','A snapshot may not offer interactive behavior, and a live runtime may still lack external service configuration. Do not paste credentials into source to satisfy a preview error. Export and local testing can be appropriate for requirements outside the supported environment.',['compatibility/preview-modes','code-editor/errors','working-copies/preview']],
['troubleshooting/visual-target','Troubleshoot an unavailable visual target','A missing visual target can mean disconnected selection, a stale source mapping or a source pattern that is not safely editable. Test those possibilities separately.','Use selection mode in a connected preview and inspect whether other elements resolve. Keep the latest accepted source revision in mind after structural edits.',[
'Confirm that selection mode is active rather than interaction mode. Try a simple visible text element.',
'If no target resolves, inspect preview connection and readiness. If only one target fails, inspect its source pattern in Code.',
'After a structural save, reselect against the current preview instead of reusing a stale selection.',
'Use Code for unsupported expressions or styles. Report a minimal reproducible mismatch if a simple supported target remains unavailable.'
],'A supported target should expose its source context and available controls. Unsupported targets should remain explicit rather than pretending a visual change was saved.','Do not remove useful logic or duplicate shared components solely to force visual selection. Third-party components and dynamically generated styles can require Code. Include the operation and safe project reference in a bug report, not an entire private source bundle by default.',['visual-editor/select-elements','visual-editor/unsupported','compatibility/visual-support']],
['troubleshooting/contact','Choose the right support channel','Choose a support channel by the operation that needs help. Distinct categories make it easier to provide relevant context without exposing unnecessary account or source data.','Collect a brief description and safe references before opening the contact form. The public contact flow prepares an email for your own email client; it does not imply a ticket was sent before you send it.',[
'Use Account Help for identity/access, Seller Support for submissions/releases and Billing Help for orders, subscriptions or AI usage.',
'Use Report an Issue for reproducible product errors, including steps, expected result and a redacted screenshot when useful.',
'Use Sales or Partnerships for a specific business request. Use Security Report privately for suspected vulnerabilities.',
'Review the prepared subject, category and context in your email client, attach any safe supporting image and send to hello@webcanbe.com.'
],'Your message should identify its purpose and contain a clear next question. Keep the sent email for follow-up; the web form does not need to store a copy of your message.','Do not send secrets, private source, passwords or session data. A prepared email is not delivery confirmation, and this guide does not promise a response deadline. If your device has no email client configured, copy the displayed category and details into an email you compose yourself.',['security/support-data','billing/orders','security/disclosure']],
])
