import { family } from '../doc-types'
export default family('Workspaces & working copies', [
['working-copies','Working copies','A working copy is the editable project created from an acquired release. It holds your source and accepted revisions separately from the creator’s immutable publication.','You need the appropriate entitlement and available project capacity. Keep the source release reference so you can distinguish a creator update from a revision you made yourself.',[
'Create the copy through the action attached to an acquired release. Wait for source preparation to complete before opening the editor.',
'Open the project from Projects and inspect the initial files or preview. Verify that it is the release you intended to use.',
'Choose Visual, Code or Split for the task. Save changes and inspect History before moving to another large edit.',
'Export an accepted revision when you need portable source for a local repository or development environment.'
],'Your edits should persist in the working project while the marketplace release stays unchanged. Visual and Code are different views of the same source, not independent copies that must be manually synchronized.','Working-copy creation can be blocked by entitlement, capacity or compatibility checks. Do not retry blindly when an operation is still pending. Unsaved drafts are not accepted source and are not included merely because they are visible in an editor tab.',['purchases/working-copy','working-copies/open','history']],
['working-copies/open','Open your workspace','Open a working project from your account’s project list, then wait for its source and preview state to become clear. A public project preview is not an editable workspace.','Sign in with the account that owns the working copy. If you recently acquired a release, create a working copy first; the acquisition and workspace routes have different purposes.',[
'Open Projects and select the working project by name. Use its source-release reference if several copies have similar names.',
'Wait for the workspace to report whether source and preview are available. Read compatibility or connection messages before editing.',
'Use Code to inspect accepted files, Visual for supported source-backed targets, or Split to compare both.',
'Before leaving, finish pending saves and confirm the latest accepted revision. Reopen from Projects when checking persistence.'
],'You should see your editable source under the intended project identity. A connected preview should reflect accepted source; a recovering draft may require an explicit save before it appears there.','If the project is absent, check the signed-in account and working-copy creation result. A preview connection failure does not necessarily mean source was lost. Keep the project reference and visible status when contacting support.',['working-copies/missing','compatibility/preview-modes','history/drafts']],
['working-copies/source-release','Trace the source release','The source-release reference explains where a working copy began. The working revision explains what you have changed since then. Keep both when diagnosing project-specific behavior.','Open the project and its purchase information. A creator’s current listing version can be newer than the release used by your copy, so do not report only the latest marketplace version.',[
'Find the acquired release associated with the project. Record the listing and release reference in your own project notes.',
'Open History to identify the accepted working revision where the issue occurs.',
'Compare a problem against the original release only in a separate copy or source export. Avoid overwriting your current work just to reproduce it.',
'When asking for help, describe whether the behavior existed before your edits and include safe release/project identifiers.'
],'You can separate a release issue from a change introduced by your own edits. This also makes it easier to evaluate creator updates without assuming they have already reached your copy.','A release reference is not a complete record of external service state. Dependencies, network APIs and remote assets can behave differently later. Do not include private source or secret environment values when a version reference and reproduction description are enough.',['marketplace/releases','history/inspect','creators/releases']],
['working-copies/capacity','Understand project capacity','Project capacity determines whether your account can create another active working project. Use the live plan configuration and account state rather than relying on an old numerical limit.','Check Plans and your current account plan. The number of purchased releases is conceptually different from the number of active working projects you can create from them.',[
'Before creating several copies, inspect the active-project allowance shown for your plan.',
'Create one working copy and wait for its result before starting another operation.',
'If the service reports a capacity limit, review existing projects and the available plan options. Preserve source exports before any destructive account action.',
'Contact Billing Help if the plan shown in your account disagrees with the entitlement or capacity message.'
],'Successful creation should add a working project within the account’s current allowance. An unsuccessful capacity check should not be presented as a completed copy or a new purchase.','Limits can change with plan configuration and subscription state. This guide does not promise a fixed project count or an automatic capacity release from actions the UI does not offer. Never delete important work merely to test a limit; confirm the available recovery and export options first.',['billing/plans','purchases/working-copy','export']],
['working-copies/missing','Find a missing working copy','When a project is missing, check account identity and creation status before assuming the source was deleted. Purchases and editable projects are separate lists.','Keep any project reference, source release and approximate creation time you already have. Avoid creating many duplicate copies while trying to locate the original.',[
'Confirm the account in Settings, especially if you use more than one provider identity.',
'Open Projects and distinguish a loading failure from an empty result. Then check Purchases to confirm the release entitlement still appears.',
'If you recently created the copy, review whether the operation completed or returned a capacity, compatibility or service error.',
'Contact General Support with the project/purchase reference and whether the copy ever opened successfully. Do not attach private source automatically.'
],'You should identify whether the issue concerns account selection, list loading, materialization or a previously existing project. That distinction determines the correct recovery path.','An acquired release does not prove that a working copy was successfully created. Conversely, a disconnected preview is not evidence that a project is absent. If a save was in progress when access was lost, preserve any local draft recovery prompt until the accepted server state is known.',['account/identity','purchases/missing','history/recovery']],
['working-copies/modes','Choose Visual, Code or Split','Visual, Code and Split are workspace views over the same project source. Choose the view that makes the intended change easiest to inspect.','Open an editable working copy and understand whether the preview is connected. The view selection itself does not create a revision or convert the project into another representation.',[
'Use Visual for source-backed text and style changes that the inspector explicitly supports.',
'Use Code for logic, complex expressions, unsupported styling or changes that need a broader source context.',
'Use Split when you want the file editor and rendered result visible together. Save Code drafts before expecting the preview to reflect them.',
'After a change, inspect the accepted revision in History regardless of which view initiated it.'
],'A saved edit should be visible across the relevant views because they share accepted source. Switching views should not create separate versions that need manual merging.','Visual support is target-specific. A rendered element can be read-only if its source cannot be resolved safely. Code drafts may remain unsaved while another view shows the accepted version; resolve that state deliberately before exporting or applying an AI proposal.',['visual-editor','code-editor','split-view']],
['working-copies/preview','Connect and inspect the preview','The preview renders your working source in a controlled runtime. Its connection state is separate from whether the source has been saved successfully.','Read the compatibility report and preview status before assuming the page is ready. Some admitted projects support a snapshot workflow; others have an interactive runtime path.',[
'Open the workspace and use the available preview connection action. Wait for readiness or a clear error state.',
'Select a viewport width appropriate to the layout you are checking. Keep preview width separate from the authoring breakpoint used to save styles.',
'Switch between selection and interaction modes as the workspace allows. Use selection to inspect source-backed elements and interaction to exercise supported behavior.',
'After saving, check that the preview reaches the accepted revision before judging whether a change worked.'
],'The preview should show a clear current state, not silently stand in for source authority. The accepted files and History remain the reference when rendering is delayed or unavailable.','A snapshot cannot promise live application interactions. Network services, unsupported dependencies and preview transport errors can affect rendering. Do not repeat source mutations just to force a refresh; first inspect connection status and the accepted revision.',['compatibility/preview-modes','visual-editor/responsive','troubleshooting/preview']],
['customization','Plan a project customization','Customize a working copy in small, reviewable steps so source changes remain understandable. Separate content edits, visual styling and application logic rather than changing all three at once.','Create a working copy and inspect the original release. Note the pages, shared components and external services that your intended design depends on. Export a known-good accepted revision when you need an independent reference.',[
'Begin with content changes such as headings and labels. Use Visual only where the target is explicitly editable.',
'Adjust spacing, typography and colors while checking the affected component scope and responsive breakpoint.',
'Move to Code for behavior, data handling and unsupported source patterns. Save and verify one coherent change at a time.',
'Use AI proposals for bounded source tasks, review their diffs and confirm the preview after acceptance. Finish with a source export.'
],'History should tell a readable story of your changes, and the exported files should match the accepted project. Shared components should remain consistent across their rendered instances.','A marketplace preview can contain presentation-only states. Replacing branding does not configure a backend or grant rights to bundled assets. Keep credentials outside public source and use the project’s own setup guidance for integrations.',['first-edit','visual-editor/shared-source','ai-editing','export']],
])
