import { useEffect, useRef, useState } from 'react'
import { Search } from 'lucide-react'
import { docPages, docsNav } from './docs-content'
import { EmbeddedVideo } from './EmbeddedVideo'
const sectionId=(title:string)=>title.toLowerCase().replace(/[^a-z0-9]+/g,'-')
export function DocsShell({path}:{path:string}) {
  const [query,setQuery]=useState(''),search=useRef<HTMLInputElement>(null)
  const page=docPages[path]
  const ordered:string[]=docsNav.flatMap(([,items])=>items.map(([,href])=>href)).filter(href=>docPages[href])
  const index=ordered.indexOf(path)
  const results=Object.entries(docPages).filter(([,p])=>(p.title+' '+p.intro+' '+p.sections.map(s=>s.title+' '+s.body).join(' ')).toLowerCase().includes(query.toLowerCase())).slice(0,8)
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key==='k'){event.preventDefault();search.current?.focus()}if(event.key==='Escape')setQuery('')};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[])
  const navigation=<>{docsNav.map(([group,items])=><details key={group} open className="docs-nav-group"><summary>{group}</summary><div>{items.map(([label,href])=><a href={href} key={href} aria-current={path===href?'page':undefined}>{label}</a>)}</div></details>)}</>
  return <><div className="wcb-docs-topbar"><a className="wcb-docs-topbar-title" href="/docs">Documentation</a><div className="wcb-docs-search"><Search size={16}/><input ref={search} aria-label="Search documentation" placeholder="Search documentation" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd>{query&&<div className="wcb-docs-search-results" aria-label="Search results">{results.length?results.map(([href,p])=><a key={href} href={href}><b>{p.title}</b><span>{p.eyebrow}</span></a>):<p>No articles match “{query}”. Try source, export, or account.</p>}</div>}</div><nav aria-label="Documentation resources"><a href="/docs" aria-current={path==='/docs'?'page':undefined}>Docs</a><a href="/docs/getting-started">Guides</a><a href="/contact/support">Help</a></nav></div><main className="docs-page"><div className="docs-layout"><aside className="docs-sidebar" aria-label="Documentation navigation"><div className="docs-rail-links"><a href="/browse">Browse marketplace</a><a href="/contact/support">Help center</a></div><div className="docs-desktop-navigation">{navigation}</div><details className="docs-mobile-menu"><summary>Documentation menu</summary>{navigation}</details></aside><article className="docs-content"><div className="docs-breadcrumb"><a href="/docs">Docs</a><span>/</span>{page.eyebrow}</div><h1>{page.title}</h1><p className="docs-lead">{page.intro}</p>{(path==='/docs'||page.video)&&<EmbeddedVideo src={page.video?.src} title={page.video?.title}/>}{page.sections.map(section=><section key={section.title} id={sectionId(section.title)}><h2>{section.title}</h2><p>{section.body}</p></section>)}<nav className="docs-pagination" aria-label="Article navigation">{index>0&&<a href={ordered[index-1]}>Previous: {docPages[ordered[index-1]].title}</a>}{index<ordered.length-1&&<a href={ordered[index+1]}>Next: {docPages[ordered[index+1]].title}</a>}</nav></article><aside className="docs-toc" aria-label="On this page"><span>On this page</span>{page.sections.map(section=><a key={section.title} href={'#'+sectionId(section.title)}>{section.title}</a>)}</aside></div></main></>
}
