import type { categories } from './categories'

type Guide = readonly [string,string]
const guides:Record<string,readonly Guide[]>={
 marketing:[
 ['A clear first screen','A marketing project should make its audience, offer, and primary action understandable before the first scroll. Inspect the actual hero in desktop and phone widths. Check whether the headline, supporting text, image, and call to action are ordinary source content you can edit, and whether the navigation still leaves room for the message. A convincing screenshot is less useful than a working page whose copy and links can be changed.'],
 ['A path beyond the hero','Compare the sections after the opening claim. Look for a sequence that explains the product, proves relevant benefits, answers objections, and ends with a next step. Try each navigation link and call to action in the live preview. Check that anchor targets land on the intended section and that the final action does not assume an integration the project does not include.'],
 ['Responsive composition','Marketing layouts can become awkward when several columns collapse. Preview a narrow width and follow the whole page, not just the first screen. Look for readable headings, image crops, touch targets, and a mobile menu that opens and closes. Source backed breakpoints should be clear enough to change later without making every section a special case.'],
 ['Content and conversion','A template can provide forms and buttons without a configured customer relationship system, mailing list, or payment provider. Inspect what each control actually does. If an external service is needed, identify its configuration points in the source and document the work needed before launch. Do not infer completed lead capture from a polished form in a preview.'],
 ['Images and claims','Hero art and product illustrations shape the first impression. Check the asset license and whether the content describes the product you will actually launch. Replace borrowed brand names, fabricated testimonials, and claims you cannot support. A good starting project should let you alter text, images, colors, and spacing while preserving a coherent layout.'],
 ['What to inspect before copying','Open a project detail page, compare its gallery with the running preview, and check the included files. Create a working copy only when the release or first party template meets your source and license needs. Then make a small edit near the top and one near the end, save them, reopen the project, and confirm the exported files carry the changes.']
 ],
 saas:[
 ['Application screens are more than cards','A software project may include onboarding, settings, lists, and empty or error states. Inspect the preview for those states rather than judging a single overview screenshot. Check whether navigation changes the visible screen and whether controls keep their state. A static dashboard picture cannot tell you how the app behaves when data is absent or a request fails.'],
 ['Authentication boundaries','Look for the difference between a visual sign in page and a real identity integration. A template may provide the layout while your application still needs an identity provider, session handling, and server authorization. Read the release setup notes and source before assuming accounts are already operational. Never place credentials in client code while adapting the project.'],
 ['Realistic data requirements','Tables and metrics need a data source. Identify which fields the project expects, how loading and errors are represented, and whether sample records are clearly marked. Replace demonstration content with your own service or database only after preserving the component contracts. A polished zero state is useful; invented sales, users, or growth numbers are not.'],
 ['State and navigation','Try tabs, filters, search, menus, and dialogs in the running preview. Confirm that each enabled control changes something meaningful and that back and forward navigation preserve the user’s place. Inspect how routes are represented in source and how a direct refresh is served. If a browser route needs host configuration, record that before launching.'],
 ['Workspace to product','After creating a working copy, try changing a label, a spacing value, and a stateful control. Confirm that the preview and saved source agree. Then test a narrow viewport and an export. This is a practical way to learn which parts of a project are ready to edit visually and which parts require a code change.'],
 ['Dependencies and deployment','A SaaS interface can depend on API endpoints, environment settings, and third party services. Read the package and configuration files rather than inferring independence from the preview. The exported source should build, but production accounts, data, domains, and provider credentials remain your responsibility unless a release explicitly includes an integration.']
 ],
 commerce:[
 ['Storefront versus commerce service','A storefront template can give you product discovery, product detail, and cart presentation. It does not create inventory, merchant approval, tax handling, shipping, or payment capture by itself. Inspect the exact boundary between UI state and a real service. If the source expects an API, note the request shape and the provider you plan to connect before taking orders.'],
 ['Product discovery','Try the category links, search, filters, and sorting in the preview. Confirm that the results genuinely change and that an empty match has an honest state. Product photos should fit their cards without cropping important detail. A buyer should be able to return from a detail page to the same browsing context.'],
 ['Product detail quality','Look for readable descriptions, variation choices, availability, images, and licensing or delivery information appropriate to what you sell. Test gallery controls with both pointer and keyboard. If the project includes a purchase button, verify whether it initiates a real server checkout or is only a visual interaction before adapting it to your own store.'],
 ['Cart and checkout handoff','A cart needs clear prices, quantities, and error recovery. A checkout handoff needs a server that validates totals and records an order. Avoid carrying a client side display price into your payment provider as authority. Source inspection should show whether the project includes that backend or whether you need to connect one.'],
 ['Mobile shopping','Many customers browse on a phone. Preview the full page at a narrow width, including filtering, details, cart, and final action. Check touch target size, sticky controls, image loading, and whether important price or delivery terms are hidden behind decoration. Responsive source should make those choices intentional.'],
 ['Catalog ownership','After making a working copy, replace sample products with your own approved content and image rights. Save, reopen, and export to check that the new information lives in source or a documented data integration. A screenshot copied into a page is not an editable catalog and cannot support real stock or orders.']
 ],
 directories:[
 ['Define the collection','A directory works when visitors understand what belongs in it and how entries are chosen. Inspect the card fields, detail layout, and category labels. Decide which information is editorial, which comes from a data source, and which is user submitted. The preview should make the difference visible rather than implying that an empty template already contains verified listings.'],
 ['Findability','Search, filters, and sort controls should change the current collection, not just their labels. Try a query with results and one without. Follow a result into its detail page and back. Check whether the URL retains enough state for a saved link and whether the source makes those relationships understandable to modify.'],
 ['Entry detail','A useful directory entry may need a description, location, status, contact route, related items, and source or verification information. Inspect how the project handles a long title, a missing image, and uneven amounts of text. A good template has a resilient layout rather than identical placeholder cards that assume every record is complete.'],
 ['Submission and moderation','If a project displays Submit listing, inspect where the information goes. An actual public submission flow needs validation, spam handling, review, and permission rules. A client only form cannot truthfully claim that an entry has been published. Read the source and note any backend needed before enabling this feature.'],
 ['Collection growth','Preview enough records to see pagination or loading behavior, but distinguish demonstration content from the published data you will use. Consider how categories evolve, how stale entries are updated, and how users report corrections. Those processes should be documented even if the template only provides the interface.'],
 ['Copy and source','Create a working copy, replace a card and detail with your own example, then use search and filters to verify the new record. Save and reopen the source. If data comes from an external service, the export should include integration code and clear setup requirements, not a frozen preview.']
 ],
 editorial:[
 ['A reading system','Editorial projects need more than an attractive home grid. Inspect a complete article with headings, links, lists, images, captions, and a long reading flow. Look for a clear measure, legible type, and navigation that helps a reader find related work. Preview both a short item and a long piece to see how the layout behaves.'],
 ['Archive and taxonomy','Try the archive, topic links, tags, and search if they are shown. Confirm that navigation changes the set of articles and that a filtered zero state is understandable. Check how an article URL is formed and whether direct refresh returns the same content. A category label should connect to a real archive view.'],
 ['Publishing workflow','A template may keep articles in source files, a JSON collection, or an external CMS. Inspect which approach the project actually uses. If an editor screen is shown, establish whether it persists changes. Choose the model that fits your publishing frequency and team before investing in a layout that depends on an unavailable service.'],
 ['Media and rights','Replace example photography and copy with material you can publish. Check image dimensions, alt text, captions, credit, and loading behavior. Editorial material may carry third party rights even when the page code is licensable. The project detail and release license should help you identify what may be reused.'],
 ['Reading on a phone','Open a long article on a narrow screen. Check line length, title wrapping, inline media, footnotes, tables, and the position of share or navigation controls. Try links and any contents navigation with keyboard as well. A large desktop screenshot cannot reveal reading fatigue or clipped content lower on the page.'],
 ['Make your first issue','In a working copy, change the publication title, one article, and the archive metadata. Confirm that the new item appears in the expected list and opens at a stable route. Save, reopen, and export to understand whether content is carried in the source or needs a connected CMS.']
 ],
 portfolio:[
 ['Projects need stories','A portfolio card is an invitation to inspect a complete case. Open the work page and look for context, process, outcome, role, and enough imagery to explain the result. Avoid implying client work or measurable outcomes that did not happen. Source backed case components should make it practical to replace every part with your own work.'],
 ['A distinct point of view','Compare the two first party templates in their actual previews. Aperture North uses an editorial portfolio direction, while Stillform centers architecture and immersive imagery. Their source and behavior are different; choose according to the work you need to present. A thumbnail alone cannot reveal how navigation, scrolling, or a long project page feels.'],
 ['Navigation and inquiry','Try the top navigation, mobile menu, project links, and final contact path. Determine whether an inquiry control opens an email client, routes to a contact page, or submits to a service. Do not treat a styled form as a working inbox unless the release includes its server path and delivery configuration.'],
 ['Image treatment','A portfolio often stands or falls on the quality of its images. Inspect cropping at different widths, loading order, captions, and alt text. Confirm that image paths are in the editable source or a documented media service. Replace examples with assets you have rights to use and test the layout with your actual aspect ratios.'],
 ['Editing across the page','Change text near the top, a project description in the middle, and a footer or contact statement near the end. Then adjust color, spacing, and typography. Save each accepted revision and reopen the working copy. This shows whether Visual and Code operate on the same files rather than on a disconnected preview.'],
 ['Taking the work elsewhere','Export after your edits and run the source independently. Check that project images, links, and responsive rules remain present. A working copy should be yours to continue under the applicable template or release license; the source archive is more useful than a static screenshot of the site.']
 ],
 dashboards:[
 ['Information hierarchy','A dashboard should help someone make a decision, not merely fill a screen with metrics. Inspect which measures have a real source, their units, and their time range. Check that empty, loading, and unavailable states differ. A template can show layout and interaction, but sample numbers should never be presented as current business performance.'],
 ['Tables as working tools','Try sorting, searching, filtering, row actions, and pagination where shown. The selected state should be visible, and a row action should not accidentally trigger the card or table navigation beneath it. Long names, missing values, and narrow widths reveal whether the table is ready for actual records.'],
 ['Permission boundaries','Administration interfaces often expose sensitive operations. Review the source to see whether it includes server authorization or only client side navigation. Hiding a menu item is not an access control. Connect roles and audit behavior to your own backend before using the template for production administration.'],
 ['Responsive density','A dense desktop console may need a different layout on a phone. Preview tables, filters, drawers, and dialogs at narrow widths. Check that actions stay reachable, that horizontal scrolling is intentional, and that one panel does not trap the user. Keyboard focus should remain visible throughout the interface.'],
 ['State and failure','A real dashboard needs to tell users when data is stale or a request failed. Inspect retry actions and whether old results can overwrite a later selection. If the project has local demonstration data, understand how to replace it with an authenticated API while preserving the components’ empty and error states.'],
 ['Validate your copy','Create a working copy and replace a heading, a table column, and a detail action. Save, reopen, and inspect the source diff. Then export and run the project to confirm that the layout, icons, and responsive behavior survived outside Webcanbe.']
 ],
 all:[
 ['Inspect before committing','Start with a card that speaks to your actual project. Open its detail page, change the gallery image, and explore the full live preview. Look for real navigation, long sections, and working controls. The listing should explain its source, creator, price, included files, and any external setup, so that a polished first screenshot does not conceal missing functionality.'],
 ['First party and published releases','Aperture North and Stillform are Webcanbe first party source templates. Published Creator listings enter the catalog only after review, assessment, rights verification, and release publication. These paths can look similar as cards, but purchase entitlements and immutable seller releases are distinct from making a copy of a first party template.'],
 ['Choose a fit','Category and style filters narrow the visible results. Search for a use case, inspect the resulting detail, and reset filters when you want the full catalog again. A zero result means the current selection has no match; an unavailable catalog response is a different condition and should be retried rather than represented as an empty marketplace.'],
 ['Understand the source','The preview is a running project, while the source is what you edit and export. Review the file structure and compatibility notes. React, Vite, images, fonts, and external service integrations each affect what you will need to run it on your own host. Treat a visible UI as evidence of appearance and behavior, not evidence that every backend is included.'],
 ['Make a safe working copy','Use template or acquisition creates an editable project under an authenticated workspace. Your changes do not rewrite the original source or another buyer’s project. Reopen the working copy after saving to verify persistence. A purchase may grant an entitlement before you create a copy; Purchases should show that next step plainly.'],
 ['Continue after export','Export the accepted source and build it independently. Check that assets, routes, responsive rules, and your edits are present. The applicable license controls what you may do with a published release, and external services still need your own credentials and deployment configuration.']
 ]
}
const checks:readonly Guide[]=[
 ['Preview the entire project','Open the live preview and scroll to its last section. Follow the navigation and try any visible tabs, filters, galleries, or menus. Compare what you see with the gallery and the listing description. If a feature does not respond or only works at one viewport width, treat that as a real limitation before choosing the project.'],
 ['Read compatibility and setup','Inspect the project’s source stack, included files, release version, and external dependencies. Note which integrations require your own account and secrets. A browser preview can show layout while a build or hosted service has different requirements. The documentation should tell you how to reproduce the result locally from exported source.'],
 ['Check the license before acquisition','The license defines reuse of source and bundled content. Look for exclusions on photographs, fonts, brand marks, or third party services. A free template still has terms, and a paid release does not automatically give rights to assets outside its license. Seller Support can clarify a release before purchase if any permission is uncertain.'],
 ['Try an edit and a return visit','After creating a working copy, change a visible text value and one style value. Save the accepted source, refresh, and return to the same project. Compare the preview with the source files and History. This small round trip is a more reliable test of editability than a single successful click in the canvas.']
]
export function MarketplaceCategoryGuide({category}:{category?:typeof categories[number]}){const subjects=guides[category?.slug||'all']||guides.all;return <section className="public-market-deep-guide" aria-label={category?`${category.title} selection guide`:'Marketplace selection guide'}><header><span>Explore with confidence</span><h2>{category?`Choosing a ${category.title.toLowerCase()} project`:'Find a source project that fits your work'}</h2><p>Use the running preview, release information and source contract together. These practical checks help you choose what to edit, what to configure, and what to verify after export.</p></header>{[...subjects,...checks].map(([title,body],index)=><article key={title}><span>{String(index+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}<footer><a href="/docs/marketplace">Marketplace guide</a><a href="/docs/compatibility">Compatibility</a><a href="/contact/sellers">Seller Support</a></footer></section>}
