import { SharedCTA,SharedFooter } from './SharedFooter'
import { DocsShell } from './DocsShell'
import { infoPages,supportChannels } from './content/public-pages'
import { categories } from './categories'
export function PublicHeader(){return <header className="public-header"><a href="/" className="public-brand" aria-label="Webcanbe home"><img src="/brand/webcanbe-mark.svg" alt="" width="25" height="25"/><span>Webcanbe</span></a><nav aria-label="Main navigation"><a href="/browse">Marketplace</a><a href="/docs">Docs</a><a href="/plans">Plans</a><a href="/login">Sign in</a></nav></header>}
export function PublicSite({path,build='development'}:{path:string;build?:string}){
 let content
 if(path.startsWith('/docs'))content=<DocsShell path={path}/>
 else if(path.startsWith('/contact/')){
 const c=supportChannels[path.split('/')[2]]
 content=<main className="public-article"><nav aria-label="Breadcrumb"><a href="/contact">Contact</a> / {c.title}</nav><h1>{c.title}</h1><p className="public-lead">{c.intro}</p><section><h2>What to include</h2><p>{c.guidance}</p></section><form className="support-form" data-category={c.category} data-build={build}><label>Email for replies<input name="requesterEmail" type="email" autoComplete="email" maxLength={320}/></label><label>Subject<input name="subject" required minLength={3} maxLength={160}/></label>{c.fields.map(([name,label])=><label key={name}>{label}<textarea name={name} rows={name==='steps'?4:2} maxLength={2000}/></label>)}<label>Description<textarea name="message" required minLength={10} rows={7} maxLength={5000}/></label><label className="support-context"><input type="checkbox" name="context"/><span><b>Include safe technical context</b><small>Adds only this page path and app version. It never includes browser details, source, or your message.</small></span></label><p>The case stores no attachment, password, token, cookie, payment credential, private source, or Bigperson factor. Email delivery is not claimed.</p><button className="wcb-public-button" type="submit">Create request</button><p role="status" data-support-status/><noscript><p>This form needs JavaScript to create a request.</p></noscript></form><section><h2>Track your requests</h2><p>Signed-in users can review their own case status in <a href="/requests">My Requests</a>. Public cases use the reference shown after submission.</p><a href="/docs/security/support-data">Review safe support context</a></section></main>
 }else if(path==='/browse'||path.startsWith('/browse/')){
 const category=categories.find(c=>'/browse/'+c.slug===path)
 content=<main className="public-marketplace"><nav aria-label="Breadcrumb"><a href="/browse">Marketplace</a>{category&&<> / {category.title}</>}</nav><h1>{category?category.title:'Browse working web projects'}</h1><p className="public-lead">{category?category.description:'Start with a published source project. Inspect the release, create an editable working copy, and make it your own in Visual, Code or Split.'}</p><nav className="category-links" aria-label="Project categories"><a href="/browse" aria-current={!category?'page':undefined}>All projects</a>{categories.map(c=><a href={'/browse/'+c.slug} aria-current={category===c?'page':undefined} key={c.slug}>{c.title}</a>)}</nav><form className="market-search" role="search"><label>Search published projects<input type="search" name="query" autoComplete="off"/></label><button className="wcb-public-button">Search</button></form><section data-catalog-category={category?.tag||''}><h2>Published projects</h2><p data-catalog-status role="status">Projects are loaded from the public catalog. If the catalog is unavailable, you can still review the buying and compatibility guides below.</p><div className="public-project-grid" data-catalog-results/></section><section className="market-guide"><h2>Choose a project with confidence</h2><p>Read the release description and license, inspect the preview, and check compatibility before acquiring a project. A category describes its intended use; external services, assets and production configuration may still be your responsibility.</p><a href="/docs/marketplace/project-details">Read a project detail page</a><a href="/docs/compatibility">Check compatibility</a><a href="/docs/marketplace/licenses">Understand release licenses</a></section></main>
 }else if(path==='/plans')content=<main className="public-article"><h1>Plans for the way you build</h1><p className="public-lead">Compare current project capacity and AI allowances. Marketplace purchases and account plans are separate.</p><section data-public-plans><h2>Current plans</h2><p role="status">Plan availability and prices are supplied by the live account service.</p></section><section><h2>Before choosing</h2><p>Review the billing period, limits and final checkout amount. A paid plan does not grant every marketplace release or configure a project’s external services.</p><a href="/docs/billing/plans">Plan guide</a> · <a href="/contact/billing">Billing Help</a></section></main>
 else if(infoPages[path]){const p=infoPages[path];content=<main className="public-article"><nav aria-label="Breadcrumb"><a href="/">Webcanbe</a> / {path.startsWith('/legal')?<a href="/legal">Legal</a>:p.title}</nav><h1>{p.title}</h1><p className="public-lead">{p.intro}</p>{p.sections.map(s=><section key={s.title}><h2>{s.title}</h2><p>{s.body}</p>{s.links&&<ul>{s.links.map(([label,href])=><li key={href}><a href={href}>{label}</a></li>)}</ul>}</section>)}</main>}
 else content=<main className="public-article"><h1>Page not found</h1><p>This address does not identify a public Webcanbe page.</p><a href="/docs/index">Browse documentation</a> · <a href="/browse">Explore Marketplace</a></main>
 return <div className={'public-product static-public'+(path.startsWith('/docs')?' docs-public-page':'')}><PublicHeader/>{content}<SharedCTA/><SharedFooter/></div>
}
