import { SharedCTA,SharedFooter } from './SharedFooter'
import { DocsShell } from './DocsShell'
import { infoPages,supportChannels } from './content/public-pages'
import { categories } from './categories'
import { MarketplacePage } from './MarketplacePage'
export function PublicHeader(){return <header className="public-header"><a href="/" className="public-brand" aria-label="Webcanbe home"><img src="/brand/webcanbe-mark.svg" alt="" width="25" height="25"/><span>Webcanbe</span></a><nav aria-label="Main navigation"><a href="/browse">Marketplace</a><a href="/docs">Docs</a><a href="/plans">Plans</a><a href="/login">Sign in</a></nav></header>}
export function PublicSite({path,build='development'}:{path:string;build?:string}){
 let content
 if(path.startsWith('/docs'))content=<DocsShell path={path}/>
 else if(path.startsWith('/contact/')){
 const c=supportChannels[path.split('/')[2]]
 content=<main className="public-article"><nav aria-label="Breadcrumb"><a href="/contact">Contact</a> / {c.title}</nav><h1>{c.title}</h1><p className="public-lead">{c.intro}</p><section><h2>What to include</h2><p>{c.guidance}</p></section><form className="support-form" data-category={c.category} data-build={build}><label>Email for replies<input name="requesterEmail" type="email" autoComplete="email" maxLength={320}/></label><label>Subject<input name="subject" required minLength={3} maxLength={160}/></label>{c.fields.map(([name,label])=><label key={name}>{label}<textarea name={name} rows={name==='steps'?4:2} maxLength={2000}/></label>)}<label>Description<textarea name="message" required minLength={10} rows={7} maxLength={5000}/></label><label className="support-context"><input type="checkbox" name="context"/><span><b>Include safe technical context</b><small>Adds only this page path and app version. It never includes browser details, source, or your message.</small></span></label><p>The case stores no attachment, password, token, cookie, payment credential, private source, or Bigperson factor. Email delivery is not claimed.</p><button className="wcb-public-button" type="submit">Create request</button><p role="status" data-support-status/><noscript><p>This form needs JavaScript to create a request.</p></noscript></form><section><h2>Track your requests</h2><p>Signed-in users can review their own case status in <a href="/requests">My Requests</a>. Public cases use the reference shown after submission.</p><a href="/docs/security/support-data">Review safe support context</a></section></main>
 }else if(path==='/browse'||path.startsWith('/browse/')){
 const category=categories.find(c=>'/browse/'+c.slug===path)
 content=<MarketplacePage category={category}/>
 }else if(path==='/plans')content=<main className="public-article"><h1>Plans for the way you build</h1><p className="public-lead">Compare current project capacity and AI allowances. Marketplace purchases and account plans are separate.</p><section data-public-plans><h2>Current plans</h2><p role="status">Plan availability and prices are supplied by the live account service.</p></section><section><h2>Before choosing</h2><p>Review the billing period, limits and final checkout amount. A paid plan does not grant every marketplace release or configure a project’s external services.</p><a href="/docs/billing/plans">Plan guide</a> · <a href="/contact/billing">Billing Help</a></section></main>
 else if(infoPages[path]){const p=infoPages[path],legal=path.startsWith('/legal');content=<main className={'public-article'+(legal?' public-legal':'')}><nav aria-label="Breadcrumb"><a href="/">Webcanbe</a> / {legal?<a href="/legal">Legal</a>:p.title}</nav><h1>{p.title}</h1>{p.version&&<p className="legal-version">Version {p.version}</p>}<p className="public-lead">{p.intro}</p>{p.publicationBlocked&&<aside className="legal-review-notice" role="note"><b>Publication gate</b><p>This reviewed package is implemented but not yet effective. Verified operator and processing details must be supplied before production publication; unresolved source fields are excluded from this page.</p></aside>}{legal&&<nav className="legal-route-nav" aria-label="Legal documents"><a href="/legal/terms">Terms</a><a href="/legal/privacy">Privacy</a><a href="/legal/buyer-license">Buyer License</a><a href="/legal/creator-distribution">Creator Agreement</a><a href="/legal/refunds">Refunds</a><a href="/legal/acceptable-use">Acceptable Use</a><a href="/legal/licenses">Licenses</a><a href="/legal/privacy-requests">Privacy Requests</a></nav>}{p.sections.map(s=><section key={s.title}><h2>{s.title}</h2>{s.body&&<p>{s.body}</p>}{s.paragraphs?.map((paragraph,index)=><p key={index}>{paragraph}</p>)}{s.links&&<ul>{s.links.map(([label,href])=><li key={href}><a href={href}>{label}</a></li>)}</ul>}</section>)}</main>}
 else content=<main className="public-article"><h1>Page not found</h1><p>This address does not identify a public Webcanbe page.</p><a href="/docs/index">Browse documentation</a> · <a href="/browse">Explore Marketplace</a></main>
 const marketplace=path==='/browse'||path.startsWith('/browse/')
 return <div className={'public-product static-public'+(path.startsWith('/docs')?' docs-public-page':'')}>{!marketplace&&<PublicHeader/>}{content}{!marketplace&&<SharedCTA/>}<SharedFooter/></div>
}
