import fs from "node:fs"
import { describe, expect, it } from "vitest"

const auth=fs.readFileSync("worker/bigperson-auth.js","utf8")
const mutations=fs.readFileSync("worker/control-mutations.js","utf8")
const worker=fs.readFileSync("worker/index.js","utf8")
const client=fs.readFileSync("src/hostedProductClient.ts","utf8")
const app=fs.readFileSync("src/App.tsx","utf8")
const schema=fs.readFileSync("deployment/hosted/postgres-control-roles.sql","utf8")

describe("Phase 5 privileged Control mutations",()=>{
  it("turns each successful three-factor proof into session-bound audited step-up evidence",()=>{
    expect(auth).toContain("INSERT INTO wcb_operator_step_up_evidence")
    expect(auth).toContain("'control_high_risk'")
    expect(auth).toContain("evidenceId")
    expect(mutations).toContain("verified_at>=clock_timestamp()-interval '5 minutes'")
    expect(mutations).toContain("session_id=$3")
  })
  it("binds the passkey challenge to the exact mutation body",()=>{
    expect(worker).toContain("operationBody = body?.operationBody ?? {}")
    expect(worker).toContain('{ method: "POST", path, body: operationBody }')
    expect(client).toContain("privilegedMutation")
    expect(client).toContain("operation: { method: \"POST\", path, body: operationBody }")
  })
  it("lets Bigperson change platform roles only through audited server mutation",()=>{
    expect(mutations).toContain("transitionOperator")
    expect(mutations).toContain("operator.authority.transition")
    expect(mutations).toContain('["reviewer","admin","bigperson"]')
    expect(mutations).toContain("wcb_product_operators")
    expect(schema).toContain("wcb_protect_last_bigperson")
    expect(app).toContain("Verify 3 factors & apply")
  })
  it("supports audited seller approval and rejection without reopening rejected intake",()=>{
    expect(mutations).toContain("transitionSellerApplication")
    expect(mutations).toContain("seller.application.transition")
    expect(mutations).toContain("Rejected seller application cannot be reopened.")
    expect(client).toContain("controlTransitionSellerApplication")
    expect(app).toContain(">Approve<")
    expect(app).toContain(">Reject<")
  })
  it("clears the mutation factor before the passkey ceremony",()=>{
    expect(app).toContain('const factor=mutationFactor; setMutationFactor(""); setBusy(true)')
    expect(app).toContain("One factor entry authorizes only the single operation")
  })
  it("revokes a specific first-party session only after a fresh three-factor proof",()=>{
    expect(mutations).toContain("revokeSession")
    expect(mutations).toContain("session.revoke")
    expect(worker).toContain("/__webcanbe/api/ops/sessions/revoke")
    expect(client).toContain("controlRevokeSession")
    expect(app).toContain(">Revoke<")
    expect(app).toContain("Tokens and hashes are never exposed.")
  })
  it("makes immutable review decisions and assessment admission three-factor operations",()=>{
    expect(mutations).toContain("decideSubmissionReview")
    expect(mutations).toContain("submission.review.decision")
    expect(mutations).toContain("admitAssessment")
    expect(mutations).toContain("submission.assessment.admit")
    expect(worker).toContain("/__webcanbe/api/ops/reviews/decide")
    expect(worker).toContain("/__webcanbe/api/ops/assessments/admit")
    expect(client).toContain("controlReviewDecision")
    expect(client).toContain("controlAdmitAssessment")
    expect(app).toContain("Approve review")
    expect(app).toContain("Admit assessment")
  })
  it("promotes only passed immutable assessment lineage into a release",()=>{
    expect(mutations).toContain("promoteAssessmentRelease")
    expect(mutations).toContain("assessment.release.promote")
    expect(mutations).toContain('row.result_status==="passed"')
    expect(mutations).toContain("verifyReleaseSnapshot")
    expect(mutations).toContain("wcb_seller_release_promotions")
    expect(worker).toContain("/__webcanbe/api/ops/releases/promote")
    expect(client).toContain("controlPromoteAssessmentRelease")
    expect(app).toContain("Promote release")
  })
  it("publishes one promoted immutable release as one audited Listing",()=>{
    expect(mutations).toContain("publishPromotedListing")
    expect(mutations).toContain("release.listing.publish")
    expect(mutations).toContain("wcb_listing_publications")
    expect(mutations).toContain("Listing publication does not match one promoted immutable release.")
    expect(worker).toContain("/__webcanbe/api/ops/listings/publish")
    expect(client).toContain("controlPublishPromotedListing")
    expect(app).toContain("Publish Listing")
  })
  it("derives Ready on the server from immutable release source instead of client claims",()=>{
    expect(mutations).toContain("qualifyReleaseReady")
    expect(mutations).toContain("deriveReleaseReadiness")
    expect(mutations).toContain("release.ready.qualify")
    expect(mutations).toContain("wcb_ready_qualifications")
    expect(worker).toContain("/__webcanbe/api/ops/releases/ready/qualify")
    expect(client).toContain("controlQualifyReleaseReady")
    expect(app).toContain("browser cannot submit a Ready score or status")
  })
  it("keeps Control entitlement authority limited to TEST entitlements",()=>{
    expect(mutations).toContain("grantTestEntitlement")
    expect(mutations).toContain("transitionTestEntitlement")
    expect(mutations).toContain("provider='test'")
    expect(mutations).toContain("entitlement.test.grant")
    expect(mutations).toContain("entitlement.test.transition")
    expect(worker).toContain("/__webcanbe/api/ops/entitlements/test/grant")
    expect(worker).toContain("/__webcanbe/api/ops/entitlements/test/transition")
    expect(client).toContain("controlGrantTestEntitlement")
    expect(client).toContain("controlTransitionTestEntitlement")
    expect(app).toContain("Payment-provider entitlements are not mutable here.")
  })
  it("shows bounded audit transition detail without making audit mutable",()=>{
    expect(app).toContain('{label:"Transition",keys:["transition"]}')
    expect(mutations).toContain("INSERT INTO wcb_control_audit")
  })
  it("enforces role thresholds on the server, not only in UI",()=>{
    expect(mutations).toContain('await role(db,session,"bigperson")')
    expect(mutations).toContain('await role(db,session,"admin")')
    expect(mutations).toContain('await role(db,session,"reviewer")')
  })
  it("keeps privileged audit append-only and compares JSONB transitions canonically",()=>{
    expect(mutations).toContain("INSERT INTO wcb_control_audit")
    expect(mutations).toContain("idempotency_key")
    expect(mutations).toContain("canonicalJson(prior.transition)!==canonicalJson(transition)")
    expect(mutations).toContain("A terminal TEST entitlement cannot be re-granted.")
    expect(schema).toContain("wcb_protect_last_bigperson")
  })
})
