// @vitest-environment jsdom
import { act } from 'react'
import { createRoot, type Root } from 'react-dom/client'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { ProductShell, Avatar, CreateWorkspaceDialog, OnboardingStrip } from './app-shell'
import { appRoutes, type DashboardView } from './shellState'
import { hostedProductClient } from './hostedProductClient'
vi.mock('./hostedProductClient',()=>({productionAuthMode:()=>true,hostedProductClient:{account:vi.fn(),workspaces:vi.fn(),createWorkspace:vi.fn()}}))
let host:HTMLDivElement,root:Root
const account={userId:'viewer',displayName:'Oliver Taylor',email:'oliver@example.test',picture:'https://lh3.googleusercontent.com/test-avatar'}
beforeEach(()=>{vi.clearAllMocks();localStorage.clear();sessionStorage.clear();window.history.replaceState({},'', '/dashboard');vi.mocked(hostedProductClient.account).mockResolvedValue(account as never);vi.mocked(hostedProductClient.workspaces).mockResolvedValue(['personal']);host=document.createElement('div');document.body.append(host);root=createRoot(host);(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true})
afterEach(async()=>{await act(async()=>root.unmount());host.remove()})
async function render(element:React.ReactNode){await act(async()=>root.render(element))}
async function click(element:Element|null){expect(element).not.toBeNull();await act(async()=> (element as HTMLElement).click())}
describe('authenticated product shell',()=>{
 it('keeps the project rail focused on real project destinations',async()=>{await render(<ProductShell view="projects" navigate={()=>{}} signOut={async()=>{}}>Projects</ProductShell>);const links=host.querySelectorAll('.rd-sidebar-content a');expect([...links].map(link=>link.getAttribute('href'))).toEqual(['/dashboard']);expect(host.querySelector('.rd-nav-button.active')?.getAttribute('href')).toBe('/dashboard');expect(host.querySelector('.rd-topnav')).toBeNull()})
 it('does not expose a local-only archive for an old archive URL',async()=>{window.history.replaceState({},'', '/projects?view=archive');await render(<ProductShell view="projects" navigate={()=>{}} signOut={async()=>{}}>Projects</ProductShell>);const active=[...host.querySelectorAll('.rd-nav-button.active')];expect(active).toHaveLength(1);expect(active[0].getAttribute('href')).toBe('/dashboard');expect(host.querySelector('a[href="/projects?view=archive"]')).toBeNull()})
 it('keeps page identities while All remains selected on the overview',async()=>{for(const view of ['overview','projects','marketplace','purchases','settings','account','billing','notifications','help'] as DashboardView[]){await render(<ProductShell view={view} navigate={()=>{}} signOut={async()=>{}}><h1>{appRoutes[view][1]}</h1></ProductShell>);expect(host.querySelector('.rd-nav-button.active')?.getAttribute('href')).toBe(view==='overview'||view==='projects'?'/dashboard':undefined);expect(host.querySelector('h1')?.textContent).toBe(appRoutes[view][1])}})
 it('links Upgrade to Pro directly to Plans and opens a real workspace dialog',async()=>{const navigate=vi.fn();await render(<ProductShell view="overview" navigate={navigate} signOut={async()=>{}}>Dashboard</ProductShell>);await click(host.querySelector('[aria-label="Account menu"]'));expect(host.querySelector('.rd-account-dropdown a')?.getAttribute('href')).toBe('/plans');await click([...host.querySelectorAll('.rd-account-dropdown button')].find(node=>node.textContent?.includes('New workspace'))!);expect(host.querySelector('[role="dialog"]')?.getAttribute('aria-label')).toBe('Add workspace')})
 it('renders search results that navigate and closes the search dialog',async()=>{const navigate=vi.fn();await render(<ProductShell view="overview" navigate={navigate} signOut={async()=>{}}>Dashboard</ProductShell>);await click(host.querySelector('.rd-sidebar-search'));expect(host.querySelectorAll('.wcb-search-results a')).toHaveLength(Object.keys(appRoutes).length);await click(host.querySelector('.wcb-search-results a[href="/billing"]'));expect(navigate).toHaveBeenCalledWith('/billing');expect(host.querySelector('[role="dialog"]')).toBeNull()})
 it('renders provider photos and falls back to initials after image failure',async()=>{await render(<Avatar account={account}/>);const img=host.querySelector('img')!;expect(img.getAttribute('src')).toBe(account.picture);expect(img.getAttribute('referrerpolicy')).toBe('no-referrer');await act(async()=>img.dispatchEvent(new Event('error')));expect(host.querySelector('img')).toBeNull();expect(host.textContent).toBe('OT');await render(<Avatar account={{displayName:'New User',picture:'javascript:alert(1)'}}/>);expect(host.querySelector('img')).toBeNull();expect(host.textContent).toBe('NU')})
 it('creates a hosted workspace through the API and preserves selection',async()=>{const close=vi.fn(),navigate=vi.fn();vi.mocked(hostedProductClient.createWorkspace).mockImplementation(async id=>id);await render(<CreateWorkspaceDialog onClose={close} navigate={navigate}/>);await click([...host.querySelectorAll('button')].find(button=>button.textContent==='Create workspace')!);expect(hostedProductClient.createWorkspace).toHaveBeenCalledOnce();expect(JSON.parse(localStorage.getItem('wcb-selected-workspace')!)).toBe(vi.mocked(hostedProductClient.createWorkspace).mock.calls[0][0]);expect(navigate).toHaveBeenCalledWith('/workspace');expect(close).toHaveBeenCalledOnce()})
 it('retains an actionable error and retries the same workspace ID',async()=>{vi.mocked(hostedProductClient.createWorkspace).mockRejectedValueOnce(new Error('Try again')).mockImplementation(async id=>id);await render(<CreateWorkspaceDialog onClose={()=>{}} navigate={()=>{}}/>);const button=[...host.querySelectorAll('button')].find(button=>button.textContent==='Create workspace')!;await click(button);expect(host.querySelector('[role="alert"]')?.textContent).toBe('Try again');await click(button);const calls=vi.mocked(hostedProductClient.createWorkspace).mock.calls;expect(calls[0][0]).toBe(calls[1][0])})
 it('allows dismissing onboarding before completion and preserves that preference',async()=>{sessionStorage.setItem('wcb-onboarding-user','viewer');localStorage.setItem('wcb-onboarding:viewer',JSON.stringify({step:0}));await render(<OnboardingStrip navigate={()=>{}}/>);expect(host.querySelector('nav')).not.toBeNull();await click(host.querySelector('[aria-label="Dismiss onboarding"]'));expect(host.querySelector('nav')).toBeNull();expect(JSON.parse(localStorage.getItem('wcb-onboarding:viewer')!).dismissed).toBe(true)})
})
